### ISSUE TITLE
XeroClient.getReportProfitLoss Bugs

### ISSUE THREAD

**Issue by james-m-85** [XeroAPI/Xero-Java#100]
I have found a couple of bugs with the getReportProfitLoss method in the XeroClient class.

- My understanding is that lines 1624 and 1650 should be changed from:
`addToMapIfNotNull(params, "trackingCategoryID", trackingCategoryId);`
to
`addToMapIfNotNull(params, "trackingCategoryID1", trackingCategoryId);`
as they cause the following error when using the first set of tracking category/option IDs:
> TrackingCategoryID1 must be provided if a TrackingOptionID1 is provided.

Instead of using:
`Report report = client.getReportProfitLoss(null, null, fromDate, toDate, myTrackingCategoryId, myTrackingOptionId, null, null, true, false);`
I've had to use:
`Report report = client.getReportProfitLoss(null, null, fromDate, toDate, null, null, myTrackingCategoryId, myTrackingOptionId, true, false);`
which apparently produces no errors.

- Running the getReportProfitLoss method between two dates (either by specifying a `fromDate` and `toDate` or by specifying a date range in the `where` parameter) does not include entries (e.g. Payable Invoices) that fall under the very last day of the specified range. For example, if I run a PNL report between the 1st Oct and 31st Oct, the result will only include entries between the 1st Oct and 30th Oct. If I specify the date range to be only for the last day of that range (e.g. from 31st Oct to 31st Oct), the returned result will be correct. A similar bug also appears when specifying a `period` and `timeframe`. The date range also appears to be incorrect in the `reportTitle` sometimes.

I would appreciate if these issues can be resolved. Thanks.

**Comment by SidneyAllen** [comment]
@james-m-85 

We've done a  major upgrade to version 2.0 of the SDK, review the README for how to migrate from 1.0 to 2.0.  Please let me know if you are still having issues with the new AccountingApi client (this replaces the XeroClient) with helper methods.

**Comment by SidneyAllen** [comment]
@james-m-85 Thanks for finding that bug.  I've pushed version 2.0.1.

timeframe is now a string arg.

**Comment by james-m-85** [comment]
Thanks for fixing that one, so I modified my code accordingly to produce a Profit & Loss report for the past year broken down by month:

```java
BigDecimal periods = new BigDecimal(11);
String timeframe = "MONTH";
ReportWithRows report = accountingApi.getReportProfitAndLoss(null, null, periods, timeframe, null, null, null, null, true, false);
```

It produces the following JSON but the dates it specifies at the end of each month are sometimes incorrect (as indicated below). It considers every month to have 30 days (except February), so if there are any entries (e.g. Payable Invoices) that have a date of 31st of a month, then they will not be picked up and calculated within the report. I have generated an Excel report through the Xero website to check the numbers and they do not match.

It would require an additional bug fix to 31st as the last day for Jan, Mar, May, Jul, Aug, Oct and Dec. Thanks.

```json
{
	"reports": [{
			"reportID": "ProfitAndLoss",
			"reportName": "Profit and Loss",
			"reportType": "ProfitAndLoss",
			"reportTitle": null,
			"reportTitles": ["Profit & Loss", "...", "...", "1 November 2018 to 30 November 2018"],
			"reportDate": "15 November 2018",
			"updatedDateUTC": "/Date(1542320504048)/",
			"rows": [{
					"rowType": "Header",
					"title": null,
					"cells": [{
							"value": "",
							"attributes": null
						}, {
							"value": "30 Nov 18",
							"attributes": null
						}, {
							"value": "30 Oct 18", (incorrect)
							"attributes": null
						}, {
							"value": "30 Sep 18",
							"attributes": null
						}, {
							"value": "30 Aug 18", (incorrect)
							"attributes": null
						}, {
							"value": "30 Jul 18", (incorrect)
							"attributes": null
						}, {
							"value": "30 Jun 18",
							"attributes": null
						}, {
							"value": "30 May 18", (incorrect)
							"attributes": null
						}, {
							"value": "30 Apr 18",
							"attributes": null
						}, {
							"value": "30 Mar 18", (incorrect)
							"attributes": null
						}, {
							"value": "28 Feb 18",
							"attributes": null
						}, {
							"value": "30 Jan 18", (incorrect)
							"attributes": null
						}, {
							"value": "30 Dec 17", (incorrect)
							"attributes": null
						}
					],
					"rows": null
				}, (etc...)
```

**Comment by SidneyAllen** [comment]
@james-m-85 

Try changing the from and to date parameters.

fromDate = "2018-01-01";
toDate = "2018-12-31";
periods = new BigDecimal("11");
profitLossTimeframe = "MONTH";

**Comment by SidneyAllen** [comment]
Hi @james-m-85 

When you pass the timeframe parameter you are asking to compare to time periods together.  Like in the attached Report from Xero.

If you want to just get a Report for a single month.  Leave out the timeframe and period parameter and just specify the start and end date for that month.  If you want 12 months of P&L, that would suggest 12 unique API calls.

<img width="1280" alt="screen shot 2018-11-16 at 4 34 54 pm" src="https://user-images.githubusercontent.com/595967/48654175-999c9000-e9bf-11e8-9904-1643f25737cf.png">
