### ISSUE TITLE
Proxy setting isn't applied for XeroClient.executeFile

### ISSUE THREAD

**Issue by jinywu** [XeroAPI/Xero-Java#103]
I put proxy setting in config.json as follows.
"ProxyEnabled": "true",
"ProxyHost": "proxy.xxxx",
"ProxyPort": 8080

it's successful to get invoices and other information, but it failed to download attachements. It seems that proxy setting is not applied for the executeFile funciton.

**Comment by SidneyAllen** [comment]
Hi @jinywu 

I've pushed release 2.0.2 with fix for proxy setting.

Thanks for catching this.
