### ISSUE TITLE
Request to improve things in the next version of the API

### ISSUE THREAD

**Issue by faceless2** [XeroAPI/Xero-Java#104]
As you're currently updating the code I'm going to throw in some requests in the hope you can consider these before new new API is set in stone. I've been integrating the Java API (XML-based version) with our internal database.

The big issue: Not retrieving line items when I request the full list of invoices, credit notes or bank transactions is a major mistake.

Most bank transactions have what, one line item? Invoices, the vast majority less than ten. To retrieve this data you're forcing me to make N additional API calls for each individual transaction by ID, waiting 1 second between each call to as not to hit the limit. I don't know what the purpose of this is, network traffic? It's almost certainly higher this way.

A bank transaction without any descriptive text is as useful as a chocolate teapot. Anyone requesting bank transaction data will be requesting the line items.

**Please, please give me a way to request the line item data for all items that have them.**

Next: calling client.getAttachments("Invoices", id) where there is no attachment results in a NPE.
```
Exception in thread "main" java.lang.NullPointerException
	at com.xero.api.XeroClient.getAttachments(XeroClient.java:1867)
```

Finally: Using Calender and BigDecimal are absolutely the wrong choice. I gather you are .NET people and unfamiliar with Java so I'm going to let you off for making this decision, once. But if you're changing the API, this is your chance to get it right.

* java.util.Calender is mainly useful for modifying dates or working with timezones. If are starting with a UNIX timestamp, just use java.util.Date, as that is exactly what it represents. I presume you cannot accept a date in a non-Gregorian Calendar? Do you store the timezone of the dates I specify in your model? Or do you perhaps serialise the Calender I give you in Json by immediately converting it back to a UNIX timestamp for transmission? Hmm? 

Calendar is the wrong choice.

* BigDecimal is absolutely, categorically the wrong choice. You are not solving any rounding issues here, just pushing them elsewhere; the first thing any dev will do is convert it to a double to work with or format. Either do what every other financial package has done since the dawn of time, store the values in the API as a long representing the lowest value currency unit: cents, yen, whatever. Rounding and precision are no longer an issue. Or, if this is too radical, give us the values as a double and note that "values will be rounded to the appropriate number of decimal places for the currency".

IEE754 rounding is an issue in every language, not just Java, but I presume you're not making JavaScript or .NET people jump through this absurd hoop. The code is harder to work with, errors are more likely, and at the end of the process I bet you 0.999 recurring dollars you're still rounding back to 2dp when serializing to Json?

Thank you for your consideration.

**Comment by SidneyAllen** [comment]
@faceless2 Thanks for the feedback.  You've provided a lot and I'm not 100% sure which feedback is related to our API and which is specific to this update to our Java SDK.

If you don't mind, I'd like to look at these one at a time.

The models for this SDK are generated off an OpenAPI Spec.  
https://github.com/XeroAPI/Xero-OpenAPI/blob/master/spec/v3/Xero_accounting_2.0.0_swagger.yaml

This is brand new, so there is time to refine the data types.  I'm interested in clarifying what alternative to BigDecimal you recommend?  Am I right to assume you think for ALL numbers should have a format of double?

https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by faceless2** [comment]
Hi Sidney

Thanks for getting back so quickly.

My feedback relates to the old API as I haven't tried the new one yet. If you're using BigDecimal in the new one it will relate to that too.

My suggestion only relates to points where Calendar and BigDecimal are used; I haven't fully explored your API (and without Javadocs I can't inspect the method signatures). But It appears to be where you have an xs:dateTime or real (non-integer) value in the old XSD schema. In your new Yaml schema I expect it's wherever you have "number"; your OpenAPI defines this type as a "floating point number".

My basic argument against the use of both Calendar and BigDecimal is that you are presenting data with more precision than is available. I'm pretty sure you're transmitting dates as a UNIX timestamp and decimal values (ie. amounts) as a Json number with up to two units of precision (depending on currency).

If that's the case then both of these classes offer way more precision and complexity than the underlying data actually has. What should govern the decision is the format the data is serialized in: Modern Json is governed by RFC8259 and that says:

> Since software that implements IEEE 754 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide

**Comment by faceless2** [comment]
re lineitems - thanks Sidney, I hadn't spotted that in the API docs but now see it is as you described, I'll use that going forward. I'll leave this open as my comments on BigDecimal / Calendar stand, but otherwise I'm happy.

**Comment by SidneyAllen** [comment]
@faceless2 

RE: the NullPointerException when getting attachments.  I've just tested the 2.0 version of the SDK and found that you can check the size of the attachments returned to determine if any attachments exist.  Would this work for your use case?

ApiClient apiClientForAccounting = new ApiClient(config.getApiUrl(),null,null,null);
AccountingApi accountingApi = new AccountingApi(apiClientForAccounting);
accountingApi.setOAuthToken(token, tokenSecret);	
Attachments InvoicesAttachments = accountingApi.getInvoiceAttachments(InvoiceID);

if (InvoicesAttachments.getAttachments().size() > 0)
{
  UUID InvoiceAttachementID = InvoicesAttachments.getAttachments().get(0).getAttachmentID();
  String InvoiceContentType = InvoicesAttachments.getAttachments().get(0).getMimeType();
  ByteArrayInputStream InvoiceInput = accountingApi.getAccountAttachmentById(InvoiceID,InvoiceAttachementID, InvoiceContentType);
				
}

**Comment by faceless2** [comment]
The issue was that retrieving the list itself was failing, that looks like it's fixed to me - great, thanks.

To continue on my previous observations on choosing the correct type for object: Can I respectfully suggest that the "TrueOrFalse" type is replaced with a boolean. Or a Boolean, if you want it to be nullable.

**Comment by SidneyAllen** [comment]
Hi @faceless2,

I am going on the assumption that your feedback about datatypes (BigDecimal, Calendar, TrueOfFalse) are related to our Java SDK and not commentary about Xero's API.

If you can share a file name and line number where you are seeing an issue and I'll take a lot to see if any action is required.
