### ISSUE TITLE
Unpublished dependency 

### ISSUE THREAD

**Issue by errorhandler** [XeroAPI/Xero-Java#105]
Hi There,

The dependency `com.xero:xero-accounting-api-schema:0.1.2` is defined in `pom.xml` but isn't published to Maven Central, this is less than ideal as it requires using the GitHub maven repo.

**Comment by SidneyAllen** [comment]
Hi @errorhandler 

I've moved the schema files to maven central and updated the Java SDK to version 2.1.1 to pull schema dependency from maven central.
