### ISSUE TITLE
No AddressType field in Address

### ISSUE THREAD

**Issue by Golem765** [XeroAPI/Xero-Java#108]
API states that Addresses in Contacts should have AddressType specified, but there is no such field in model

[API docs](https://developer.xero.com/documentation/api/contacts)

[Address object](https://github.com/XeroAPI/Xero-Java/blob/master/src/main/java/com/xero/models/accounting/Address.java)

It also seems as problem with [OpenAPI](https://app.swaggerhub.com/apis-docs/Xero/accounting/2.0.0#/Accounting/getContacts) specification, as there is no such field in the specification

**Comment by SidneyAllen** [comment]
Thanks @Golem765 

I have updated the OAS and deployed version 2.1.3 of Java SDK.

**Comment by Golem765** [comment]
@SidneyAllen Thanks a lot for such a quick update, much appreciated!
