### ISSUE TITLE
Object mapping of nested objects

### ISSUE THREAD

**Issue by Golem765** [XeroAPI/Xero-Java#109]
Nested objects are mapped as `Object` and therefore got resolved as `Map` by object mapper, eg. `contact` in [Invoice](https://github.com/XeroAPI/Xero-Java/blob/master/src/main/java/com/xero/models/accounting/Invoice.java) (line 76) instead of real entities.

Not sure if it is not by design though

**Comment by SidneyAllen** [comment]
@Golem765 Thanks for calling this out.  Big oversight on our part.

See the 2.2.0 release -- found many other data types that needed correction.

**Comment by Golem765** [comment]
@SidneyAllen Thanks so much for your updates
