### ISSUE TITLE
Dates in AccountingApi

### ISSUE THREAD

**Issue by KORPSE** [XeroAPI/Xero-Java#110]
Dates are represented as String in a very specific format, for example in `com.xero.models.accounting.Organisation`, I think they should be represented as `LocalDate` instead (like it used to be in the old XeroClient).

**UPD**: Same for base currency and probably some other fields, they've become strings.

**Comment by Golem765** [comment]
@KORPSE Xero explicitly states in their API [documentation](https://developer.xero.com/documentation/api/requests-and-responses) why those dates look so weird

**Comment by KORPSE** [comment]
@Golem765 I'm talking about this SDK, not about the API

**Comment by SidneyAllen** [comment]
See the 2.2.0 release -- found there was a lot of data types that needed correction.

Have not done the baseCurrency or countryCode yet.  I'll look into that soon.

**Comment by SidneyAllen** [comment]
@KORPSE - appreciate your patience as we transition to this new spec and away from XSDs.

Added CountryCode, CurrencyCode, Timezone and other ENUMs as components.  Also, turned some enums into components for reuse throughout the spec.

Release version 2.2.1
