### ISSUE TITLE
Not able to file import com.xero.model.ApiException;

### ISSUE THREAD

**Issue by prabuskyy** [XeroAPI/Xero-Java#113]
I am not to find the class ApiException in the master branch

**Comment by SidneyAllen** [comment]
Hi @prabuskyy 

The ApiException class is not part of this repo.  It's actually generated by our deprecated XSD schema (model) files.   https://github.com/XeroAPI/XeroAPI-Schemas

The maven dependency is here https://search.maven.org/artifact/com.github.xeroapi/xeroapi-schemas/1.0.0/jar
