### ISSUE TITLE
Custom TaxRates not compatible with Enum values

### ISSUE THREAD

**Issue by aschroder** [XeroAPI/Xero-Java#114]
If you create a custom tax rate in Xero, it is assigned a numeric sequence tax type like this one TAX001:

![image](https://user-images.githubusercontent.com/387235/51009484-32f9b400-15b5-11e9-8905-b3a9cd5c302f.png)

But then when the Java SDK tries to parse that it fails because the TaxType is an enum that does not contain TAX001 as a possible value.

![image](https://user-images.githubusercontent.com/387235/51009540-6d635100-15b5-11e9-8514-de39cf5a13fb.png)

Because users could make potentially 100's of custom taxes it's probably not worth adding TAX001,TAX002...TAX999 to the enum, I wonder I this value should not be an enum?

_This sort of relates to schema problems and enums from:_
https://github.com/XeroAPI/Xero-Java/issues/112

**Comment by SidneyAllen** [comment]
@aschroder thanks for the feedback.  You are correct - I've changed TaxType to a string for version 2.2.4 of SDK - deploying new version now
