### ISSUE TITLE
CreditNote - date

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#116]
Hi,

I noticed that in the JSON API the date of the CreditNote might has the wrong format. The expected format (as stated in the comments) is yyyy-mm-dd

```
@ApiModelProperty(value = "The date the credit note is issued YYYY-MM-DD. If the Date element is not specified then it will default to the current date based on the timezone setting of the organisation")
  public String getDate() {
    return date;
  }

```

But the api Responses with the following json: 
`      "DateString": "2018-10-12T00:00:00",
      "Date": "\/Date(1539302400000+0000)\/",`

So the date is encoded the same way as UpdatedDateUTC, which is a OffsetDateTime. Is this intended or not?

Thanks,

Peter

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - Thanks for catching that.  Updated in version 2.2.8 of SDK - deploying to maven now.
