### ISSUE TITLE
Employee - UpdatedDateUTC missing

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#117]
Hi,

I found another missing field in the new models. The json response looks like the following:

```
    {
      "EmployeeID": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "Status": "ACTIVE",
      "FirstName": "Tracy",
      "LastName": "Green",
      "UpdatedDateUTC": "\/Date(1546399736547+0000)\/"
    }
```

but in `com.xero.models.accounting.Employee` the date is missing. 

I also noticed that the status enum is replaced by a String, wouldn't it be nice if it also is a enum (like the status for Invoies or Customers?). That's not really a problem, just wanted to mention it.

**Update:** also in com.xero.models.accounting.ReportRow there is now a status String, instead of an Enum.

Thanks,

Peter

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - thank you for all the detailed feedback.  Deployed 2.2.10
- added UpdatedDateUTC property
- changed status from string to enum

Did not understand your feedback about ReportRow having a status String? ??

**Comment by pkohout-profitsee** [comment]
@SidneyAllen:

oh I had a mixup. The ReportRow has a type String   `private String rowType = null;`, but in the XML version it has a enum `protected ReportRowType rowType;` Since there are only 3 possible values, as far as I know (Header, Section, Row). I think working with a enum is more convinient.

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - made the change in version 2.2.11
