### ISSUE TITLE
getReportBalanceSheet timeframe parameter

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#118]
Hi,

If I am using the method `AccountingApi.getReportBalanceSheet(String date, Integer periods, Integer timeframe, String trackingOptionID1, String trackingOptionID2, Boolean standardLayout, Boolean paymentsOnly)` I get the following error:
```

com.xero.api.XeroApiException: {
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "The supplied timeframe parameter must be one of the following: 'MONTH', 'QUARTER', 'YEAR'.",
  "Elements": []
}
```

In the old xero Client the timeframe parameter was a String.

Thanks,
Peter

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - thank you for all the detailed feedback.  Fix Deployed 2.2.10
- Bad copy paste from a different report that has same property but it's an INT.  Fixed to be an ENUM for both BalanceSheet and ProfitLoss
