### ISSUE TITLE
API java doc is sub par

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#120]
I'm just trying to use the new 2.0 api.

First statement - not terribly pleased that you felt the need to break the compatibility with the old api.
I can see some changes that make sense but a lot of them just break the api without a lot of reason (e.g returning Accounts rather than List<Account>).

However this issue is about the poor java doc:
Case in point:

````
/**
    * Allows you to retrieve invoices or purchase bills as PDF files
    * <p><b>200</b> - A successful request
    * @param invoiceID The invoiceID parameter
    * @param contentType The contentType parameter
    * @return File
    * @throws IOException if an error occurs while attempting to invoke the API
    **/
    public ByteArrayInputStream getInvoiceAsPdf(UUID invoiceID, String contentType) throws IOException 
````
```
* <p><b>200</b> - A successful request
```
This looks like a meaningless cut and paste from the http doc.

```
@param contentType The contentType parameter
```

Yes I know its the contentType parameter!

Some details on what is expected in the contentType might be useful (an enum would probably be even more useful).

This pattern of meaningless parameter descriptions looks pretty universal.

**Comment by SidneyAllen** [comment]
@bsutton - feedback appreciated as always.

We are building our OpenAPI Specs from the ground up and I can confidently say we've made progress, but it's not 100% perfect.  Since the comments are generated from the spec, we'll need to review the parameters and add better descriptions so the Java Docs are more useful.  

We'll keep iterating on this and improving with input from the community.

**Comment by SidneyAllen** [comment]
@bsutton  I've put some time into adding descriptions to objects, properties and arguments to improve the JavaDocs.  I'm sure it's not 100% yet, but many hours have been spent improving them.  If you see other areas to improve the JavaDocs, please share with me - specifics help.

Release 2.3.0 includes these changes as well as some breaking changes - so I recommend looking at the release notes prior to upgrading.

**Comment by bsutton** [comment]
Thanks for the effort, I will look into it
