### ISSUE TITLE
API uses non-standard LocalDate

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#121]
With Java 8 and beyond we now have a built in LocalDate.
The api instead uses:
org.threeten.bp.LocalDate

It would be nice if the api supported the java LocalDate as I would expect that is what most developers are now using.

**Comment by SidneyAllen** [comment]
Hi @bsutton 

Thanks for the feedback.  The short answer, is we'll be sticking with the org.threeteen.bp.LocalDate library for the time being.

Long answer ....   data types can be a tough topic and ppl have strong opinions. Previously, we used XSD files to generate models.  I received feedback from a developer, upset that "Calendar" was being used for dates.

Our 2.0 of the Java SDK has us moving towards generating our models using the OpenAPI-Generator project.  The templates' we've selected and customized were using org.threeten.bp.LocalDate and we found with some tweaking it could handle the conversion of Xero's use of MS .NET JSON Date Format returned by our API, so it made sense to stick with it.  https://developer.xero.com/documentation/api/requests-and-responses

Lastly, I've interacted with a few developers who are using our SDK on Java 7 and from what I've read org.threeteen.bp.LocalDate is a nice bridge for those developers not using Java 8 yet.

I'm sorry this probably isn't the answer you'd hoped for.
