### ISSUE TITLE
RowType deserialization

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#123]
Hi,

I just tried out the new version with the Enums for the Row types. I noticed that the RowType is null. I took a short look what causes this behaviour.

First the JsonCreator always returns null, because the value in the Json response is `Row` but the values of the enum are all in upper case. I.e `ROW`, so there is never a match. I also think that the Exception is somehow lost (I think I remember that there is a setting in jackson that ignores not mappable enum values).

```
    @JsonCreator
    public static RowTypeEnum fromValue(String text) {
      for (RowTypeEnum b : RowTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
```

I also noticed that there is a ` "RowType": "SummaryRow"`, which I forgot in my last issue. Currently missing in the enum. 

The last thing I noticed is that `ReportRows` still has a type String (with the same values as the type property of `ReportRow`.

I really hope I am not annoying you with my issue opening, but I am eager to use the json version.

Thanks,
Peter

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - please keep the feedback coming.  Your input is very helpful.

i've pushed version 2.2.12 to address the above feedback.
