### ISSUE TITLE
LineItem Invoice Does not Return Results

### ISSUE THREAD

**Issue by Sayyiditow** [XeroAPI/Xero-Java#124]
Hi guys,
When trying to get information on LineItems linked to an invoice. Nothing gets returned. Here is a sample code:
for (LineItem lineItem : invoice.getLineItems()){
                System.out.println("Reached here..." +invoice.getLineItems().size());
                for (LineItemTracking lineItemTracking : lineItem.getTracking()) {
                    System.out.println(lineItemTracking.getTrackingCategoryID());
                }
            }
If you try:  invoice.getLineItems().get(0).getTracking().get(0).getTrackingCategoryID(); - you will get a NPE.

Please check this. I am using the latest java api from maven. <version>2.2.14</version>

**Comment by Sayyiditow** [comment]
I might have found another way to query the lineitem based on the invoice UUID. Just posting this here in case it helps someone.
--> This is in a loop of all invoices being retrieved. For each invoice, use the invoiceID to lookup the lineItem. Kind of a long way but will do for now.
```
for (LineItem lineItem : accountingApi.getInvoice(invoice.getInvoiceID()).getInvoices().get(0).getLineItems()) {
                            for (LineItemTracking tracking: lineItem.getTracking()) {
                                System.out.println(tracking.getName() + tracking.getOption());
                            }
                        }
```

**Comment by SidneyAllen** [comment]
Ahhhh yest @Sayyiditow - you are correct.  LineItem data only available on single invoice or when paging is used.  Didn't realize that was the issue.
