### ISSUE TITLE
invalid type of PaymentTerms property in Contact Class

### ISSUE THREAD

**Issue by GreyDekart** [XeroAPI/Xero-Java#125]
There is a problem with deserialization of Contact with PaymentTerms.
The specification(and SDK) declares an enum PaymentTermType
Actually, it is an object like [Organisation PaymentTerm](http://developer.xero.com/documentation/api/organisation/):

```
"PaymentTerms": {
      "Bills": {
             "Day": 30,
             "Type": "DAYSAFTERBILLDATE"
      },
      "Sales": {
             "Day": 25,
             "Type": "OFCURRENTMONTH"
      }
}
```

**Comment by SidneyAllen** [comment]
Hi @GreyDekart 

Thank you for the feedback.  I've updated the OpenAPI Spec and the Java SDK to version 2.2.15.

I've tested and it's now returning the proper Payment Term object.
