### ISSUE TITLE
upload Attachment to invoice

### ISSUE THREAD

**Issue by vigneshdeivanayagam** [XeroAPI/Xero-Java#126]
when the create attachment api is executed i'm getting this exception attchment and is not attached to the invoice. im calling the create api but its showing the message not found and how is this possible.

<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ErrorNumber>10</ErrorNumber>
<Type>ValidationException</Type>
<Message>A validation exception occurred</Message>
<Elements>
<DataContractBase xsi:type="Attachment">
<ValidationErrors>
<ValidationError>
<Message>A document with id '132132' could not be found</Message>
</ValidationError>
</ValidationErrors>
<AttachmentID>0000**** **** ****-0000-000000000000</AttachmentID>
<FileName>132132.jpg</FileName>
<MimeType>application/jpeg</MimeType>
<ContentLength>3831</ContentLength>
</DataContractBase>
</Elements>
</ApiException>
![screenshot from 2019-02-04 16-24-05](https://user-images.githubusercontent.com/47321175/52207220-b8197580-28a2-11e9-96fc-f636fefba921.png)

**Comment by SidneyAllen** [comment]
@vigneshdeivanayagam 
I would recommend passing in the InvoiceId as the unique identifier.

You are using the old XeroClient which is fine - code examples are still available here https://github.com/XeroAPI/Xero-Java/tree/master/example

Attachment invoiceAttachment = client.createAttachment("Invoices",newInvoice.get(0).getInvoiceID(), fileName, "application/jpeg", bytes,true);

**Comment by vigneshdeivanayagam** [comment]
@SidneyAllen thanks for the assistance on this it worked successfully
