### ISSUE TITLE
OnlineInvoices not working

### ISSUE THREAD

**Issue by marcosbis** [XeroAPI/Xero-Java#128]
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
	at java.net.URI.create(URI.java:852)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:95)
	at com.xero.api.client.AccountingApi.getOnlineInvoice(AccountingApi.java:4706)

 <dependency>
  		<groupId>com.github.xeroapi</groupId>
  		<artifactId>xero-java</artifactId>
  		<version>2.2.16</version>
 	</dependency>

**Comment by SidneyAllen** [comment]
You need to replace {InvoiceID} with a valid invoice id in the xero organization you are connected to.

**Comment by marcosbis** [comment]
the InvoiceID is set after that error.

 public OnlineInvoices getOnlineInvoice(UUID invoiceID) throws IOException {
        try {
            String strBody = null;
            Map<String, String> params = null;
            String correctPath = "/Invoices/{InvoiceID}/OnlineInvoice";
            // Hacky path manipulation to support different return types from same endpoint
            String path = "/Invoices/{InvoiceID}/OnlineInvoice";
            String type = "/pdf";
            if(path.toLowerCase().contains(type.toLowerCase()))
            {
                correctPath = path.replace("/pdf","");
            } 

            // create a map of path variables
            final Map<String, String> uriVariables = new HashMap<String, String>();
  uriVariables.put("InvoiceID", invoiceID.toString());
  UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath() + correctPath); **[ERROR HERE]**
 String url = uriBuilder.buildFromMap(uriVariables).toString();  **[invoiceID added here]**

**Comment by SidneyAllen** [comment]
Hi @marcosbis 

I wrote a bit of sample code to test this. Be sure you wrap your code in a try/catch block.   As documented ONLY invoices of TYPE=ACCREC and NOT status=DRAFT will have online invoices.  If either of those conditions are not met, you'll get a "The resource you are looking for could not be found" message back from the API and this will throw an exception.  

// GET ALL invoices
Invoices invoices = accountingApi.getInvoices(null, null, null, null, null, null, null, null, false, true);
	
for (int i = 0; i < invoices.getInvoices().size(); i++) {
	System.out.println("Type: " + invoices.getInvoices().get(i).getType());
	System.out.println("Status: " + invoices.getInvoices().get(i).getStatus());
	try {
		// Get Online Invoice
		OnlineInvoices onlineInvoice = accountingApi.getOnlineInvoice(invoices.getInvoices().get(i).getInvoiceID());
		System.out.println("Invoice ID : " + i);
		System.out.println("Get Online invoice - URL : " + onlineInvoice.getOnlineInvoices().get(0).getOnlineInvoiceUrl());
			
	} catch (Exception e) {
		System.out.println(e.toString());
	}					
 }

**Comment by marcosbis** [comment]
Hi Sidney,

Thanks for looking at this problem.

I run the code you sent me and still getting same same error on parsing the template uri which is very odd as it works fine for any other URI/query ..
Every other function like, getInvoices, getContacts, etc.. works fine. 


RUN:
> // GET ALL invoices
> Invoices invoices = accountingApi.getInvoices(null, null, null, null, null, null, null, null, false, true);
> 
> for (int i = 0; i < invoices.getInvoices().size(); i++) {
> System.out.println("Type: " + invoices.getInvoices().get(i).getType());
> System.out.println("Status: " + invoices.getInvoices().get(i).getStatus());
> try {
> // Get Online Invoice
> 
> System.out.println("(Before get url) Invoice ID : " + i);
> 
> OnlineInvoices onlineInvoice = accountingApi.getOnlineInvoice(invoices.getInvoices().get(i).getInvoiceID());
> System.out.println("Invoice ID : " + i);
> System.out.println("Get Online invoice - URL : " + onlineInvoice.getOnlineInvoices().get(0).getOnlineInvoiceUrl());
> 
> } catch (Exception e) {
> 	System.out.println(e.toString());
> }					
> }
> 


LOG:

Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 72
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 73
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 74
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 75
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: AUTHORISED
(Before get url) Invoice ID : 76
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice


Looks like is trigger an error on parsing the URI, so I tried the following:

RUN:
import javax.ws.rs.core.UriBuilder;

		String url  = "https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice";
	    	
	    	try {
	    		UriBuilder uriBuilder = UriBuilder.fromUri(url);
	    	} catch (Exception e) {
	    		e.printStackTrace();
	    	}
	    	

LOG:
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
	at java.net.URI.create(URI.java:852)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:95)


I think whatever calls java.net.URI.create(URI.java:852) with a template URI is wrong. 

Thanks
Marcos

**Comment by SidneyAllen** [comment]
@marcosbis 

Can you output to the console the ID you are passing?

System.out.println((invoices.getInvoices().get(i).getInvoiceID());

**Comment by marcosbis** [comment]
Here is:

Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 72
5edef610-0215-41bd-8e45-172d9efb570b
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 73
40d3f71a-720c-4ac2-b723-4cf71d9dede4
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 74
3f539361-31f9-4dce-889b-50a9615fdeb1
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: DELETED
(Before get url) Invoice ID : 75
29e3a779-8631-4a8e-882b-5da71ce00674
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice
Type: ACCREC
Status: AUTHORISED
(Before get url) Invoice ID : 76
de0258dd-7edb-4416-bed1-1cd0394f92b9
java.lang.IllegalArgumentException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Invoices/{InvoiceID}/OnlineInvoice <https://api.xero.com/api.xro/2.0/Invoices/%7BInvoiceID%7D/OnlineInvoice>


The error is from the parsing URI before the query.

Thanks
Marcos

**Comment by SidneyAllen** [comment]
I've tested this with v2.2.17 of the sdk and the getOnlineInvoice method functions properly. 

It sounds like you are passing an invoiceID with some illegal characters like "spaces" or something along those lines.  You'll need to debug this on your end as I can't recreate the issue.

**Comment by marcosbis** [comment]
- As I mentioned before the error happens before send the request to get the online invoice when the URI is parsed, no ID involved at this stage.
 - I passed on the same Id for other functions and has no problem, there is no extra characters on the ID as they come from the previous getInvoice query(unattached). 
- The error has nothing to do with the invoiceID.

I will update to 2.2.17 and try again

**Comment by marcosbis** [comment]
Hi There,

I found the problem. 

The issue when the UriBuilder is created from the delegated class :

UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath() + correctPath);

When the UriBuilder is created calls the class RuntimeDelegate.class which has 2 Delegate options:
 package javax.ws.rs.ext;

1-  public static final String JAXRS_RUNTIME_DELEGATE_PROPERTY = "javax.ws.rs.ext.RuntimeDelegate";
2-  private static final String JAXRS_DEFAULT_RUNTIME_DELEGATE = "org.glassfish.jersey.internal.RuntimeDelegateImpl”;


Option 1: calls this builder line:
  @Override
    public UriBuilder createUriBuilder() {
        return new UriBuilderImpl();
    }
[ this UriBuilder DOSENT WORK]


Option 2: calls this builder:

  @Override
    public UriBuilder createUriBuilder() {
        return new JerseyUriBuilder();
    }
[This UriBuilder WORKS PERFECT]


I dont know why JAXRS_RUNTIME_DELEGATE_PROPERTY is used only in this particular request but that is what creates the problem.

 
I will try to force setup the delegate or update my dependencies see if can fix it that way.

Thanks
Marcos

**Comment by SidneyAllen** [comment]
Hi @marcosbis 

Thank you for sharing the outcome of your investigation.  I wouldn't have known of a dependency conflict.  Something I'll keep in mind in the future.

**Comment by ArtemGro** [comment]
Hi All,

I know that it's been marked as resolved but how can I fix it in my environment?
I use Groovy to pull Xero API into Jira.
Don't think that it's configurable.

Other than rewriting that method in my script are there any other workarounds?

Thanks
Artem

**Comment by grantyb** [comment]
This issue still isn't resolved in this version:
```
<dependency>
	<groupId>com.github.xeroapi</groupId>
	<artifactId>xero-java</artifactId>
	<version>4.12.0</version>
</dependency>
```

The problem stems from using UriBuilder.fromURI instead of UriBuilder.fromPath. The documentation for fromURI says 

```
     * @param uri a URI that will be used to initialize the UriBuilder, may not
     * contain URI parameters.
```

This line in AccountingAPI.class (line 14399 in the version described above) is therefore in error:

```
    UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath() + "/Invoices/{InvoiceID}");
```

The URI parameter `{InvoiceID}` is illegal for `fromUri`, but it might possibly work with `fromPath`.

**Comment by grantyb** [comment]
Actually, possibly that should be more like
```
    UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath()).path("/Invoices/{InvoiceID}");
```
Hope that helps.

**Comment by grantyb** [comment]
For what it's worth; I've tested this change and it resolves the issue.

**Comment by denissudak** [comment]
how is this resolved? 
Version 4.26.0
AccountApi:9772
```
UriBuilder uriBuilder =
        UriBuilder.fromUri(apiClient.getBasePath() + "/Invoices/{InvoiceID}/Email");
```
Same problem with Java17
