### ISSUE TITLE
getAccount exception issue

### ISSUE THREAD

**Issue by vigneshdeivanayagam** [XeroAPI/Xero-Java#129]
when checking for account on xero ("client.getAccount(accountCode);") is showing this exception and also it cant be handled too. so please advise on this issue
**java.lang.IllegalStateException: Got multiple results for query**

**Note : there is no duplicate code on xero account

**Comment by SidneyAllen** [comment]
The SDK does not support passing the AccountCode, you should pass the AccountID to the getAccount method
