### ISSUE TITLE
Info Message on every request

### ISSUE THREAD

**Issue by davidseywald** [XeroAPI/Xero-Java#131]
Hello,
We get the following log info message on every request (from com.xero.api.XeroHttpContext):
"You must use Java 1.8 to skip setting the Key Store Path & Key Store Password in config.json".

We use java 1.8. We do not use the config.json file and have a custom SignerFactory.
Is there any way to remove/disable this log message (it gets annoying and fills the logs).

Thank you.

**Comment by SidneyAllen** [comment]
Hi @davidseywald 

I can look at this in a future

**Comment by SidneyAllen** [comment]
@davidseywald  in version 2.3.0 we changed this message from "INFO" level to "TRACE" level.  This way you can set to "DEBUG" level to get all API call information with out having this same message on every call.
