### ISSUE TITLE
Get custom fields for a manualjournal

### ISSUE THREAD

**Issue by giopagliari** [XeroAPI/Xero-Java#133]
GetTracking() in xero/models/accounting/ManualJournalLine.java

  @ApiModelProperty(value = "Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2 <TrackingCategory> elements.")
  public List<TrackingCategory> getTracking() {
    return tracking;
  }

Does not return the custom fields (tracking cattegories and options) of a ManualJournal.

Steps to recreate:
1) call getManualJournalItems() to get ManualJournals
public ManualJournals getManualJournals(OffsetDateTime ifModifiedSince, String where, String order, Integer page) throws IOException 
2) Then get each ManualJournal using getManualJournals...fine
public List<ManualJournal> getManualJournals() {
3) Then get each journal line - great
public List<ManualJournalLine> getJournalLines() {
4) Then get the tracking lines ....not that great
public List<TrackingCategory> getTracking() {

Iterating through the tracking lines gives us to access to these methods:
getValue() - returns null
getStatus() - returns null
getOptions() - does not seem to return anything
getName() - works

Which one of the above fields is supposed to give me the value of the custom field?

**Comment by SidneyAllen** [comment]
Hi @giopagliari 

Tracking categories are not returned with Manual Journals.  Please refer to the API documentation for full list of properties. https://developer.xero.com/documentation/api/manual-journals

The SDK uses the "lineitems" obejct which is shared with Invoices (which do have tracking categories).

**Comment by giopagliari** [comment]
Thanks Sidney

We're struggling to get the custom fields associated with Manual Journals (clicking on Manual Journals in the UI).  We've tried via Journals without success as well.

How would you get the custom field that appears in a Manual Journal?

We get them via invoices but we need them for (Manual) Journals.  Maybe I don't know what the difference is between a Journal, Manual Journal and/or its relationship with an invoice.  Could you throw in a few comments/tips. Many thanks.

Thanks

Gio

**Comment by SidneyAllen** [comment]
Hi @giopagliari 

Thanks for chasing me up on this.  I dug into the SDK and found a few properties were missing.  I've updated the SDK to version 2.3.3 

I've tested the following code to create a new Manual Journal, and then display the category name returned by the API.

You'll need to substitute in a valid Account Code, Tracking Category NAME and Tracking Category OPTION in the code below.

```
String accountCode = "400";
				
ManualJournals manualJournals = new ManualJournals();
ManualJournal manualJournal = new ManualJournal();
LocalDate currDate = LocalDate.now();
manualJournal.setDate(currDate);
manualJournal.setNarration("Foo bar");
				
ManualJournalLine credit = new ManualJournalLine();
credit.setDescription("Hello there");
credit.setAccountCode(accountCode);
credit.setLineAmount(100.00);
manualJournal.addJournalLinesItem(credit);
				
ManualJournalLine debit = new ManualJournalLine();
debit.setDescription("Goodbye");
debit.setAccountCode(accountCode);
debit.setLineAmount(-100.00);
TrackingCategory tracking = new TrackingCategory();
tracking.setName("Simpsons");
tracking.setOption("Bart");
debit.addTrackingItem(tracking);
manualJournal.addJournalLinesItem(debit);
manualJournals.addManualJournalsItem(manualJournal);
ManualJournals createdManualJournals = accountingApi.createManualJournal(manualJournals);
UUID newManualJournalId = createdManualJournals.getManualJournals().get(0).getManualJournalID();

System.out.println(createdManualJournals.getManualJournals().get(0).getJournalLines().get(1).getTracking().get(0).getName());
```

**Comment by giopagliari** [comment]
Thank you
