### ISSUE TITLE
Journal

### ISSUE THREAD

**Issue by giopagliari** [XeroAPI/Xero-Java#135]
With reference to https://github.com/XeroAPI/Xero-Java/issues/133

Does the same issue exist with the Journal model to get the tracking data?

**Comment by SidneyAllen** [comment]
@giopagliari   They use the same TrackingCategory component in the API spec. So, the fix I made should have been applied to Journals as well.  If you find an issue, please share the details with me.

**Comment by giopagliari** [comment]
Ok thanks
