### ISSUE TITLE
PUT endpoints not working accounting API

### ISSUE THREAD

**Issue by nany3surf** [XeroAPI/Xero-Java#136]
Hi, im trying to update an account using your accounting API, I keep getting an error "java.net.URISyntaxException: Illegal character in path at index 42: https://api.xero.com/api.xro/2.0/Accounts/{AccountID}" produced in AccountingAPI class. The error is on line 6512 
"UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath() + correctPath);" caused because "fromUri" function doesn't work? I've seen that using "fromPath" it does work. Can this be fixed and updated, or can it be caused by something else? I can't update anything at the moment as you use the same functionality on all update endpoints.
The accountID is coming through fine but its not set until the next code line after the error is thrown, so it never reaches that point. 

Hope you can help.

Thanks.

**Comment by SidneyAllen** [comment]
Hi @nany3surf 

This sounds similar to this issue #128 

Take a look at the bottom for how they proposed solving the issue.

Thanks
