### ISSUE TITLE
unitdp support

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#139]
Hi,

currently it is not possible to use the unitdp=4 parameter explained in [the docs](https://developer.xero.com/documentation/api-guides/rounding-in-xero#unitamount). Can you please add support for that flag? It is also available for some more endpoints, not only the invoices.
I am also wondering if it is possible to get Reports in Xero with 4 decimal places, or are those cut to 2?

Thanks,
Peter

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - i have added unitdp param in version 2.3.4
