### ISSUE TITLE
oauthAccessToken issue connection limit reached 

### ISSUE THREAD

**Issue by vigneshdeivanayagam** [XeroAPI/Xero-Java#140]

**Comment by vigneshdeivanayagam** [comment]
We are currently facing  issues on XERO connectivity. When connecting to XERO, we are able to receive an error message. Please find the error message shared below.

ERROR com.xero.api.OAuthRequestToken - com.xero.api.XeroApiException: oauth_problem=connection limit exceeded&oauth_problem_advice=Maximum number of tenants already connected

From the above error, we get to know that, This error from XERO is thrown when connection limits are exceeded.Please update criteria for this exception and also provide any solutions for this issue. Please find the referred link here. Is this error has anything to do with the number of auth_access_token's received by our application? Please share us your views on this.

Please note, we have only one organisation connecting to XERO  and still we received a connection limit error. If you can share the existing number of connections in XERO from ezyprocure, it would be helpful. Kindly reply at the earliest.

**Comment by SidneyAllen** [comment]
Hi @vigneshdeivanayagam 

This is not an issue with the SDK, but indicates your partner app has reached the max number of allowed organisation connections.  Each time you connect a Xero org a slot is taken from an allotted amount.

Xero places organisation connection limits on uncertified partner apps.  You'll need to connect with your assigned developer evangelist to discuss increasing the connection limit during development or complete certification to have the limit removed.  

You can contact your assigned developer evangelist directly or is you can share the  name of your company and app I can help connect you.
