### ISSUE TITLE
PUT currencies endpoint not working

### ISSUE THREAD

**Issue by nany3surf** [XeroAPI/Xero-Java#141]
Hi,
Im trying to update a currency but i keep on getting the same error message: "\"Message\": \"A currency code must be provided.\""
The body im sending is:
```
{
  "Currencies": [ 
    { 
      "Code": "SGD", 
      "Description": "Singapore Dollar"
    }
  ]
}
```
I've been debugging and it all seems to work fine, it sets the currency properly but the apiClient keeps returning the same error. Can you help?
Thanks.

**Comment by SidneyAllen** [comment]
Hi @nany3surf 

This is a known issue when creating a currency using JSON payload.

I recommend utilizing the old XML (XeroClient) and older models.  Here is an example code.

try {
	// Initialize XeroClient (based on XML req/resp)
	com.xero.api.XeroClient client = new com.xero.api.XeroClient();
	client.setOAuthToken(token, tokenSecret);
			
	// Init old models based off XSD files
	com.xero.model.Currency newCurr = new com.xero.model.Currency();
	newCurr.setCode(CurrencyCode.SGD);
	newCurr.setDescription("Singapore Dollars");
	List<com.xero.model.Currency> currencies = new ArrayList<com.xero.model.Currency>();
	currencies.add(newCurr);
			
	// Create new currency.
	List<com.xero.model.Currency> currency = client.createCurrencies(currencies);
	System.out.println("Create a new Currency : " + currency.get(0).getDescription());
				
} catch (XeroApiException e) {
	System.out.println(e.getResponseCode());
	System.out.println(e.getMessage());	
}

**Comment by nany3surf** [comment]
Hi @SidneyAllen,

My project configuration is ready to use the new accounting API, so I'd have to modify quite a lot of my code only for this. Do you know if there'll be an early solution for currencies working using JSON payload?

Thanks in advance.

**Comment by SidneyAllen** [comment]
@nany3surf - if you can wait - it might be a month, it might be several months.  The API team have prioritized getting oAuth 2 built and they may not get to fixing this for some time.  I've made them aware of it, and it will get fixed, just unsure how quickly.

You can use both the old and the new client in your code.  I've kept the 1.0 xml client and models in the SDK.

The tested the code example (I shared previously) with the new client code and they run fine together.  As you can see,  in the code example I reference the specific model via com.xero.model.Currency.  This way I know it's the old model I want to use.

As long as you can initialize XeroClient and set the token/secret you should be good to go.

com.xero.api.XeroClient client = new com.xero.api.XeroClient();
client.setOAuthToken(token, tokenSecret);

**Comment by nany3surf** [comment]
Hi @SidneyAllen , that's the problem, I can't initialize the XeroClient, I initialize apiClientForAccounting in the configuration phase of the proyect and set the tokens, we don't get any control of those tokens anymore so we can't initialize the XeroClient later. 
We'll have to wait for the fix...
Thanks.

**Comment by SidneyAllen** [comment]
@nany3surf - quick update on this.  The API team are shipping some major platform features (like oAuth2), but have assured me they will be prioritizing fixing this.  Hopefully before the end of the year.

**Comment by ofirk12** [comment]
> Hi @nany3surf
> 
> This is a known issue when creating a currency using JSON payload.
> 
> I recommend utilizing the old XML (XeroClient) and older models. Here is an example code.
> 
> ```
> try {
> 	// Initialize XeroClient (based on XML req/resp)
> 	com.xero.api.XeroClient client = new com.xero.api.XeroClient();
> 	client.setOAuthToken(token, tokenSecret);
> 			
> 	// Init old models based off XSD files
> 	com.xero.model.Currency newCurr = new com.xero.model.Currency();
> 	newCurr.setCode(CurrencyCode.SGD);
> 	newCurr.setDescription("Singapore Dollars");
> 	List<com.xero.model.Currency> currencies = new ArrayList<com.xero.model.Currency>();
> 	currencies.add(newCurr);
> 			
> 	// Create new currency.
> 	List<com.xero.model.Currency> currency = client.createCurrencies(currencies);
> 	System.out.println("Create a new Currency : " + currency.get(0).getDescription());
> 				
> } catch (XeroApiException e) {
> 	System.out.println(e.getResponseCode());
> 	System.out.println(e.getMessage());	
> }
> ```

It is not working on xml also I tried with a postman..

{
  "ErrorNumber": 17,
  "Type": "NoDataProcessedException",
  "Message": "No data has been processed for this endpoint. This endpoint is expecting Currency data to be specifed in the request body."
}

**Comment by SidneyAllen** [comment]
@ofirk12 

hmmmmm, not sure what to say.  I'm using version 2.3.14 of the SDK and just tested the following code and it works successfully.

This is the older XML way to create currencies.

```java
XeroClient client = new XeroClient(config);
client.setOAuthToken(token, tokenSecret);

try {		        
    List<Currency>  currencies = new ArrayList();
    Currency c = new Currency();
    c.setCode(CurrencyCode.AUD);
    c.setDescription("Australian Dollar");
    currencies.add(c);
                
    List<Currency> newCurrency = client.createCurrencies(currencies);
    System.out.println("Created new Currency: " + newCurrency.get(0).getDescription());
} catch (XeroApiException e) {
    System.out.println(e.getResponseCode());
    System.out.println(e.getMessage()); 
} 
```

Looking at the API logs I can see the body is  ...
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Currencies><Currency><Code>AUD</Code><Description>Australian Dollar</Description></Currency></Currencies>

and response is ...
<Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Id>6329fc08-f1a5-4667-bd65-ec0aa4d72cc7</Id>
  <Status>OK</Status>
  <ProviderName>PHP Sample App</ProviderName>
  <DateTimeUTC>2019-08-21T15:18:48.5871654Z</DateTimeUTC>
  <Currencies>
    <Currency>
      <Code>AUD</Code>
      <Description>Australian Dollar</Description>
    </Currency>
  </Currencies>
</Response>

**Comment by SidneyAllen** [comment]
Hi @nany3surf and @ofirk12 

I just discovered the SDK was passing and Array of currencies when it should be a single currency object for a createCurrency.

I've updated to version 2.3.16 of the SDK.

Below is the code to test ....

Currency curr = new Currency();
curr.setCode(CurrencyCode.SGD);
curr.setDescription("Singapore Dollar");
Currencies newCurrency = accountingApi.createCurrency(curr);
