### ISSUE TITLE
AccountingApi#createBankTransactionAttachmentByFileName() doesn't work

### ISSUE THREAD

**Issue by Urugvai** [XeroAPI/Xero-Java#142]
When I'm trying to upload attachment, then I get validation error.
`{ "ErrorNumber": 10, "Type": "ValidationException", "Message": "A validation exception occurred", "Elements": [ { "AttachmentID": "00000000-0000-0000-0000-000000000000", "FileName": "filename", "MimeType": "application/octet-stream", "ContentLength": 1082850, "ValidationErrors": [ { "Message": "The file couldn't be uploaded because it isn't a supported file type." } ] } ] }` 
but I don't have possibility to set right **Content-Type**. Because method **FILE** sets only **"application/octet-stream"**

**Comment by SidneyAllen** [comment]
Hi @Urugvai 

Can you share what file format you are attempting to attach?

**Comment by Urugvai** [comment]
@SidneyAllen Sure. It is `image/jpeg`. Or do you mean I should set file name like `filename.jpeg`?

**Comment by SidneyAllen** [comment]
Hi @Urugvai 

I just tested the method and it works as expected.... I'm testing with a jpg in the resources dir.
https://github.com/XeroAPI/Xero-Java/tree/master/example/src/main/resources

`
try {
  InputStream inputStream = JsonConfig.class.getResourceAsStream("/helo-heros.jpg");
  byte[] bytes = IOUtils.toByteArray(inputStream);
  String newFileName = "foobar.jpg";

  BankTransactions myBanktransactions = accountingApi.getBankTransactions(ifModifiedSince, where, order, null,null);
  if ( myBanktransactions.getBankTransactions().size() > 0) {
    UUID banktransactionID = myBanktransactions.getBankTransactions().get(0).getBankTransactionID();			
    Attachments createdBanktransationAttachments = accountingApi.createBankTransactionAttachmentByFileName(banktransactionID, newFileName, bytes);
    System.out.println("Attachment to BankTransaction ID: " + banktransactionID + " attachment - ID: "  + createdBanktransationAttachments.getAttachments().get(0).getAttachmentID());
  }

} catch (Exception e) {
  System.out.println(e);
}
`

**Comment by Urugvai** [comment]
Hi @SidneyAllen 
What if set file name as just "foobar"?

**Comment by SidneyAllen** [comment]
@Urugvai - that returns the validation error ...  

 "Message": "The file couldn't be uploaded because it isn't a supported file type."

**Comment by Urugvai** [comment]
@SidneyAllen is it ok or no?

**Comment by SidneyAllen** [comment]
You MUST include the file extension in the filename.
foobar.jpg is ok
foobar is not ok
