### ISSUE TITLE
remove helo-heroes.jpg

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#143]
While checking why our jar file has grown so much in the last couple of months I noticed that you added a picture (helo-heroes.jpg) to the xero library. That caused the size to increase from 675KB(2.2.17) to 3.4MB (2.2.18). What I don't understand is why is it showing up in the jar file since release 2.2.18, did you change something in the build? The picture is in the repo for much longer.

As much as i like the pictures of the two of you :).

If possible, please remove it on the next release.

![image](https://user-images.githubusercontent.com/31537911/57521522-cc956000-7320-11e9-9ffa-7d2a60d2aca2.png)

**Comment by SidneyAllen** [comment]
@pkohout-profitsee I've resized it from 3MB to 30kb which is fine.  the file has been there for two years and I use it for testing file attachment uploads.

I doubt the file is the cause - but I can't point to any one thing..  I have been doing a lot of work with our OpenAPI specs adding better descriptions of properties that all result in better JavaDocs, I've added example payloads in the OpenAPI Specs and writing unit tests.   Maybe I added other dependencies.

The real question.. is 675kb and 3.4mb impacting your use of the SDK?
