### ISSUE TITLE
Invoice attachment with FilesApi, Association bug

### ISSUE THREAD

**Issue by hubidubi** [XeroAPI/Xero-Java#144]
I run into an issue while I was creating an Association for a freshly created invoice and a freshly uploaded file.
I use the following code to do the upload and create Associations.
[https://gist.github.com/hubidubi/69930b334aebe93e138a714e660ba061]

From debug I can see the this request was sent:

` {"FileId":"307637df-d21d-40c1-8c5b-1309a4ee0786","ObjectId":"175ddb6a-b9de-478d-b828-827226c13154","ObjectGroup":"Invoice"}`

And I got this response:

` {"FileId":"307637df-d21d-40c1-8c5b-1309a4ee0786","ObjectId":"175ddb6a-b9de-478d-b828-827226c13154","ObjectType":"Accpay","ObjectGroup":"Invoice"}`

It looks like that `ObjectType` has improper value: 'Accpay'. This value should be 'ACCPAY'. Check `ObjectType` enum in the code. With this improper value, json parsing fails every time:

 Can not construct instance of com.xero.models.files.ObjectType, problem: Unexpected value 'Accpay'
 at [Source: {"FileId":"307637df-d21d-40c1-8c5b-1309a4ee0786","ObjectId":"175ddb6a-b9de-478d-b828-827226c13154","ObjectType":"Accpay","ObjectGroup":"Invoice"}; line: 1, column: 113] (through reference chain: com.xero.models.files.Association["ObjectType"])

**Comment by SidneyAllen** [comment]
Hi @hubidubi 

Just ran a test, and the JSON returned from the API includes ObjectType: AccRec, but it's not throwing an error when parsing.  Which is strange.  Anything about your environment you can share that might cause this?

**Comment by SidneyAllen** [comment]
@hubidubi 

Just ran some more tests - and yes - the ObjectType is returning a null value due to the ENUM case not matching.  Let me check with the API team on this.  Not a hard fix, but I want to get the right values as they are returned by the APIs.

**Comment by SidneyAllen** [comment]
Hi @hubidubi 

I've fixed two ENUMs "AccRec" and "Accpay" and deployed v. 2.3.9 to confirm that addresses the immediate issue.  I'm following up with the API team for an accurate list of the enums so I can update in our OpenAPISpec and update the Java SDK accurately.
