### ISSUE TITLE
Missing method getReportBankStatement in AccountsApi

### ISSUE THREAD

**Issue by billy1380** [XeroAPI/Xero-Java#145]
The method getReportBankStatement does not seem to exist in the java sdk (xero-java-2.3.9.jar)

**Comment by SidneyAllen** [comment]
Hi @billy1380 

We are now generating the Java SDK from our public OpenAPI specs.  The BankStatement report is slated for deprecation in the future (not ETA at this time).  We've removed it from our API documentation and don't encourage use of it as it may go away in the future.

We consider our OpenAPI specs as documentation, therefore have not included it to be inline with our developer docs.

**Comment by billy1380** [comment]
@SidneyAllen thanks for the info. If the method is deprecated, do you know what am alternative method might be to get the same data when updating from version 1 of the API?

Thanks again.

**Comment by SidneyAllen** [comment]
Hi @billy1380 

To my knowledge, no alternative endpoints will be provided to this data in the future.  The old endpoint still exists for now.  The only option is to utilize the 1.0 client for that report or modify the 2.x Java sdk to add it.

Like I mentioned, we aren't including that report in our Spec or 2.x sdk as we don't want to encourage it's use by developers.

**Comment by billy1380** [comment]
@SidneyAllen that makes sense. Thanks for the help. Much appreciated.

**Comment by U3R1YXJ0** [comment]
Hi @SidneyAllen, are you aware of any information regarding the deprecation of the BankStatement report? Is the report being deprecated completely, or just from the API? We currently use this functionality so I would be keen to get any further information on the rationale for deprecation and any alternative functionality we could use going forward.

Many thanks, Stuart

**Comment by alastairayliffe** [comment]
Hi @U3R1YXJ0,

There is a community thread below with a little more info  - 

https://community.xero.com/developer/discussion/81094990

Thanks,
