### ISSUE TITLE
Question: how does Invoice hasAttachments get set?

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#147]
I am writing some unit tests. I create some mocked Invoices and add some mocked Attachments. I noticed that the Invoice property hasAttachment (accessed by getHasAttachment) does not seem to be updated when adding an attachment, it remains with the default value which is null.

I don't have any functional issues in my application but I can imagine situations where this might cause a problem. Should the Invoice constructor set hasAttachment to false, and update that property as required? How is the Invoice hasAttachment property set in general?

In my unit tests I have extended the Invoice class and overriden the getHasAttachment property.

**Comment by U3R1YXJ0** [comment]
Note that I haven't tried creating an Invoice and pushing it into the Xero API. I wonder if it would come back with Invoice.hasAttachment set?

**Comment by SidneyAllen** [comment]
Hi @U3R1YXJ0 

I just tested and found "getHasAttachments()" returns true.  I did the following.

1. Get ALL invoices
2. Use the ID from one of my existing invoices
3. Create an attachment on the selected Invoice
(output the invoiceID, so I can see which one I am working with"
4. Get ONE invoice using the invoice Id 

UUID inv = UUID.fromString("20ff01b8-c2d8-49bb-8abf-a9486c9ea665");
Invoices myInvoice = accountingApi.getInvoice(inv);		
System.out.println("Has attachments: " + myInvoice.getInvoices().get(0).getHasAttachments());

OUTPUT
Has attachments: true

**Comment by U3R1YXJ0** [comment]
```
com.xero.models.accounting.Invoice inv = new com.xero.models.accounting.Invoice();
inv.setInvoiceID(UUID.randomUUID());
System.out.print(inv.getHasAttachments()); //output is null
```

```
com.xero.models.accounting.Attachment att = new com.xero.models.accounting.Attachment();
att.setAttachmentID(UUID.randomUUID());
com.xero.models.accounting.Attachments atts = new com.xero.models.accounting.Attachments();
atts.addAttachmentsItem(att);
inv.addAttachmentsItem(att);
System.out.print(inv.getHasAttachments()); //output is null
```

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 

HasAttachments is only set by the API.  I've not heard any reports of issues with this.  I'll keep this open as a lower priority we can try to address in the OpenAPI spec.

**Comment by U3R1YXJ0** [comment]
OK, thanks.

I can't see why anyone would create an invoice locally and then need to check whether they had added an attachment within a functional application. 

It does make some testing a little harder though. My unit tests create some dummy Invoices and I process them as if they came from Xero. In this case my tests don't function correctly. It's a slightly messy work around as there is no public method to set the 'hasAttachments' property. I extended the Invoice class and set the property within my own class, which does the job.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - We've added default:"false" on all HasAttachment properties in our OpenAPI specs and I've confirmed that when creating a new object, the property is false and not "null"
