### ISSUE TITLE
PUT payments endpoint

### ISSUE THREAD

**Issue by nany3surf** [XeroAPI/Xero-Java#149]
Hi, Im trying to update a payment but i've seen there's no function for this. Tried using the POST payment adding the existing payment ID but I got an error back. Is there a way to do this?
Thanks.

**Comment by SidneyAllen** [comment]
Hi @nany3surf 

You can't update a payment, but you can call the "deletePayment" method and then create the payment for the object.  Would that work for your scenerio?
