### ISSUE TITLE
salesTrackingCategories not correctly filled in on a contact

### ISSUE THREAD

**Issue by thehollyhopdrive** [XeroAPI/Xero-Java#150]
I have a contact with two custom tracking catagories set in the Sales Settings. When performing a direct lookup of this contact (via the UUID), I can see that two TrackingCatagory objects are available in the getSalesTrackingCategories() method, however their fields are all null.

Code to replicate:

`Contact contact = accountingApi.getContact(contactUuid).getContacts().get(0);
System.out.println(contact);`

Printout contains the following (relevant lines only):

> salesTrackingCategories: [class TrackingCategory {
        trackingCategoryID: null
        trackingOptionID: null
        name: null
        option: null
        status: null
        options: null
    }, class TrackingCategory {
        trackingCategoryID: null
        trackingOptionID: null
        name: null
        option: null
        status: null
        options: null
    }]

I've included screenshots of the configuration for this contact on the Xero web application just to ensure that what I am expecting to get back is correct.

![Screenshot from 2019-08-02 15-31-17](https://user-images.githubusercontent.com/2649477/62377677-2467ef80-b53b-11e9-9ff6-1f19a24afa4c.png)
![Screenshot from 2018-10-24 13-14-28](https://user-images.githubusercontent.com/2649477/62377689-2e89ee00-b53b-11e9-839a-58549568a136.png)

**Comment by SidneyAllen** [comment]
Hi @thehollyhopdrive 

Thanks for sharing this - fixed in release 2.3.11
