### ISSUE TITLE
Bank Transaction LineItems are not set in SDK2

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#151]
I am using SDK 2.3.9. When I retrieve Bank Transactions from the API, they never have any LineItems set, even though every Bank Transaction I retrieve has a LineItem in Xero.

I was previously using SDK1 and Bank Transactions LineItems were returned.

Invoice LineItems are returned correctly in SDK 2.3.9.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - checkout version 2.3.12
