### ISSUE TITLE
Concurrency Internal Server Error

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#156]
**SDK you're using (please complete the following information):**
 - Version 3.0.1

**Describe the bug**
We have a system that has been running on OAuth1 for a while. We recently upgraded to OAuth2. Our system is unusual in that an accountant typically connects dozens of organisations in a short period of time. Once an Organisation is connected we spend a few minutes syncing data into our own databases. So essentially we have dozens of threads (one per Organisation), all pulling data from Xero at the same time.

We tested our system on OAuth2 with the few test accounts we have and it all worked. Today we had an accountant test the system with 22 Organisations. 15 threads completed successfully, whilst 
7 failed. The 7 threads that failed all had the same error:

```
2019-10-28 11:47:01.241
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getReportExecutiveSummary(AccountingApi.java:11533)
...
```
```
2019-10-28 11:48:11.019
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
```
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
```
2019-10-28 11:48:19.022
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
```
2019-10-28 11:48:43.022
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachmentById(AccountingApi.java:7673)
```
```
2019-10-28 11:52:37.194
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
```
2019-10-28 11:53:26.247
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachmentById(AccountingApi.java:7673)
```
```
2019-10-28 11:54:26.923
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
```
2019-10-28 11:54:46.240
com.xero.api.XeroApiException: Internal Server Error
at com.xero.api.XeroApiExceptionHandler.execute(XeroApiExceptionHandler.java:45)
at com.xero.api.client.AccountingApi.getInvoiceAttachments(AccountingApi.java:7748)
```
The errors occur at different points in the SDK (getting the attachment list of an Invoice, getting specific attachments by ID and getting an executive report). It looks as if there is some issue on the API calls that is not being reported back to the SDK fully. Could this be a firewall or security configuration kicking in? We stay within the API rate limits using a bucket scheduler.

I can provide full logs, user account details and consumer keys etc via direct message.

**To Reproduce**
Unfortunately I don't currently have a reproducible test case, as I do not have the test accounts to support the testing. My assumption is that there is some kind of concurrency issue.

**Expected behavior**
The API calls do not throw an exception

**Screenshots**
N/A

**Additional context**
N/A

**Comment by U3R1YXJ0** [comment]
A follow up on this:
- We re-synced the failed organisations and they completed successfully
- We re-synced all 22 organisations (when there was little to re-sync), and they all completed successfully.
- We deleted all of our data and re-synced the 22 organisation, 4 of them failed with the internal server error.

It appears as if we are hitting an unexpected or undocumented concurrency/rate limit on the API.

We perform just under one API call per organisation per second. Therefore 22 organisations syncing as the same time would perform around 22 API calls per second from one user account.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0  if you can share your Xero App Id (or App Name).

If you aren't comfortable sharing that publicly, please email api@xero.com and include a link to this issue.

**Comment by U3R1YXJ0** [comment]
Hi Sid. I had a look earlier to see if I could contact the API team directly, and found the contact form. I have contacted the team and had a response from Matt in the UK API team. I will update here as appropriate.
Thanks,
Stuart

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - looks like you are hitting a concurrency limit

https://developer.xero.com/documentation/oauth2/limits

There are limits to the number of API calls that your application can make against a particular tenant (organisation or practice):

Concurrent Limit: 5 calls in progress at one time
Minute Limit: 60 calls per minute
Daily Limit: 5000 calls per day

Happy to accept a PR to address this - in the meantime I'll tag this as an enhancement request.

**Comment by U3R1YXJ0** [comment]
Hi Sid, I don't believe we are hitting any of those limits. We got an Internal Server Error rather than a well formed 429.

We don't make any concurrent calls on an individual tenant Id. We have a tried and tested bucket scheduler to stay under 60 calls per minute. A sync job on a tenant would be an absolute maximum of 4100 requests for us (and will typically be a lot less). In the original errors I reported, it was the first time we had ever made calls on those tenants, so we would not have been near the 5000 limit. 

I sent all the details (timestamps, tenant Ids etc) to Matt at the end of today. Hopefully he may have more info soon.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - did we get to the bottom of this one?

**Comment by U3R1YXJ0** [comment]
Hi Sid, I raised the issue with the API team and they confirmed an issue on the Xero side on 29th October.

Maybe you can double check internally (with Matt from the UK API team) but I believe this can be closed on here. I haven't had confirmation on what the underlying issue is so not 100% certain there are no actions on the SDK.

**Comment by U3R1YXJ0** [comment]
The API team ticket number is CX0009178360

**Comment by SidneyAllen** [comment]
This is API not SDK related.  Closing issue
