### ISSUE TITLE
DiscountAmount on Invoice LineItem

### ISSUE THREAD

**Issue by dietrich-crouse** [XeroAPI/Xero-Java#157]
**SDK you're using (please complete the following information):**
 - Version [2.3.18]

**Is your feature request related to a problem? Please describe.**
Our system applies discounts by amount.
The [Xero API ](https://developer.xero.com/documentation/api/invoices#post) allows us to specify this DiscountAmount, but the Java SDK only has the DiscountRate avaiable.

**Describe the solution you'd like**
Can the DiscountAmount be added to the LineItem object?

**Describe alternatives you've considered**
I do not want to calculate what percentage our discount is in order to make use of the DiscountRate field, if the API allows for the DiscountAmount to be specified.

**Additional context**
Here is an example of using the DiscountAmount with the API.
![image](https://user-images.githubusercontent.com/20967222/67933912-761e2580-fbcf-11e9-9dd8-324e02cc7d68.png)

**Comment by SidneyAllen** [comment]
@dietrich-crouse - we've added the property in version 2.3.19

https://github.com/XeroAPI/Xero-Java/releases/tag/2.3.19

**Comment by dietrich-crouse** [comment]
@SidneyAllen thank you!
