### ISSUE TITLE
Include Organisation Email Address 

### ISSUE THREAD

**Issue by davidseywald** [XeroAPI/Xero-Java#159]
**SDK you're using (please complete the following information):**
 - Version 2.3.19

**Describe the solution you'd like**
We would like to have access via the SDK/API to the Email Address entered in the Organisation Settings. We cannot find this information at the moment.

**Comment by MattR-Api** [comment]
Hi @davidseywald 

Thanks for raising this. This isn't a specific Java SDK issue, the Organisation Endpoint currently doesn't include the email address field. We've let our developers know you'd like to see this added however.

Cheers!

Matt
