### ISSUE TITLE
Resolving xero-accounting-api-schema

### ISSUE THREAD

**Issue by slouc** [XeroAPI/Xero-Java#16]
Readme says that it's only needed to add the dependency `"com.xero" % "xero-java-sdk" % "0.0.7"` and resolver `"xero-java-mvn-rep" at "https://raw.github.com/XeroAPI/Xero-Java/mvn-repo"` (I'm using sbt). By the way, JitPack advice is not needed for sbt since xero-java-sdk can be fetched directly from the Maven repository (no need for JitPack). 

So, if I only add the xero-java-mvn-rep resolver, I get: 

> sbt.ResolveException: unresolved dependency: com.xero#xero-accounting-api-schema;0.0.2: not found

I had to also add the resolver `"xero-accounting-api-schema-mvn-repo"`. So this is what worked for me in the end:

    resolvers += "xero-java-mvn-rep" at "https://raw.github.com/XeroAPI/Xero-Java/mvn-repo"

     // this one is not in the readme
    resolvers += "xero-accounting-api-schema-mvn-repo" at "https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo"

    libraryDependencies += "com.xero" % "xero-java-sdk" % "0.0.7"

  
It would be great to either make it work with only one resolver, `xero-java-mvn-rep` (as suggested in the readme) or to add some info about the `xero-accounting-api-schema-mvn-repo` resolver, so that others don't have to investigate like I did. :)

**Comment by gtod** [comment]
Interesting, I just followed the gradle instructions at https://jitpack.io/#XeroAPI/Xero-Java/ where it wants you to add a repo

    maven { url 'https://jitpack.io' }

 but I also got a dependency problem for the `xero-accounting-api-schema;0.0.2` so I added an additional repo line

    maven { url "https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo/" }

and then I could build it.

**Comment by slouc** [comment]
Exactly. So as far as I'm concerned, just adding a line to readme would be enough, but I think the proper way to do it is to link up all the dependencies so that end users only need the xero-java stuff (as intended, judging by the readme).

**Comment by SidneyAllen** [comment]
Just merged a pull request that added a build.sbt file to the root - removed mention of JitPack from README as it's unnecessary now.
