### ISSUE TITLE
XeroApiException does not include API response codes in the log

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#160]
**SDK you're using (please complete the following information):**
3.0.1

**Describe the bug**

`throw new XeroApiException(123, "nasty thing go bad");`
in the log we get: 
`com.xero.api.XeroApiException: nasty thing go bad`

**To Reproduce**
Throw XeroApiException with a response code, the response code is not included in the log output

**Expected behavior**
I would expect the API response code to be included in the log output message. I think this is also the intended outcome because in XeroApiException we have the line
`super(responseCode + " response: " + message);`

I suspect by overriding getMessage in XeroApiException, the RuntimeException getMessage is never called, and rather than returning the RuntimeException message which would have included the code, we get the XeroApiException message which does not include the code.

You could remove the getMessage override, or set the response code in the XeroApiException message, assuming this is a desirable outcome.

**Screenshots**

**Additional context**

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - if you wish to make a PR on this, we'd be happy to review.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - we've refactored our error handling in version 4.x just release.

https://github.com/XeroAPI/Xero-Java#exception-handling

I'll be closing this issue as it's no longer relevant as XeroApiException class has been deprecated.
