### ISSUE TITLE
Token Rejected

### ISSUE THREAD

**Issue by pervez8ktt** [XeroAPI/Xero-Java#161]
Following with previous bug
https://github.com/XeroAPI/Xero-Java/issues/158#issue-517028427

Can you please give me an idea, that I want to Integrate xero API into my application for Invoice generation, and when I need auth token I have to redirect to Allow page. How could I do this process with client end? as user cannot login my xero.

**Comment by MattR-Api** [comment]
Hi @pervez8ktt 

Thanks for getting in touch. As this isn't a Java SDK specific issue, we'll close this thread down, but please feel free to raise a Case with us at either api@xero.com or https://central.xero.com. 

Thanks!

Matt

**Comment by pervez8ktt** [comment]
ok thanks
