### ISSUE TITLE
OrganisationTypeEnum is not complete

### ISSUE THREAD

**Issue by KORPSE** [XeroAPI/Xero-Java#165]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.7]

**Describe the bug**
OrganisationTypeEnum is not complete, at least one value is missing: ACCOUNTING_PRACTICE (got this from Xero API support). We're getting null value for this field for some organisations, probably because of that.

**Comment by revolutdev** [comment]
still relevant to the latest version of the SDK

**Comment by SidneyAllen** [comment]
Added to version 3.1.3.

2.x updates will be prioritized after OAuth 2.0 SDK work.

**Comment by SidneyAllen** [comment]
@KORPSE @revolutdev 

This has been resolved in 2.3.22.

Please be aware that version 2.x is now in maintenance mode and we will be prioritizing work on version 3.x and our other oauth2 SDKs over legacy sdks.
