### ISSUE TITLE
Accounting Api Modified After	parameter does not work

### ISSUE THREAD

**Issue by Sayyiditow** [XeroAPI/Xero-Java#166]
**SDK you're using (please complete the following information):**
 - Version 3.1.3

**Describe the bug**
Fetching records with "if-modified-since" tag using the OffsetDateTime does not return the intended results. It still returns all records.

**To Reproduce**
1. Using the accounting api.
2. Run accountingApi.getContacts(token.getAccessToken(), tenantId,
                "OffsetDateTime", null, null, null, null, null);

**Expected behavior**
The records returned should be only those modified since the given "OffsetDateTime". I have tried out multiple different OffsetDateTimes but all return same results - all records. 

@SidneyAllen any update will be appreciated.

**Comment by Sayyiditow** [comment]
To update this, we are using OffsetDateTime.now().minusDays(7) to get "OffsetDateTime". We have tried other numbers or even OffsetDateTime.now() but does not work.

**Comment by Sayyiditow** [comment]
Another update: With api version 3.1.3 it looks like the methods for getting the HttpResponse are not using the ifModifiedSince parameters at all? In AccountingApi class:

getInvoicesForHttpResponse - OffsetDateTime ifModifiedSince is not used at all when running the method.
getContactsForHttpResponse - same issue.

See below:
``public HttpResponse getInvoicesForHttpResponse(String accessToken, String xeroTenantId, OffsetDateTime ifModifiedSince, String where, String order, List<UUID> ids, List<String> invoiceNumbers, List<UUID> contactIDs, List<String> statuses, Integer page, Boolean includeArchived, Boolean createdByMyApp, Integer unitdp) throws IOException {
        if (xeroTenantId == null) {
            throw new IllegalArgumentException("Missing the required parameter 'xeroTenantId' when calling getInvoices");
        } else if (accessToken == null) {
            throw new IllegalArgumentException("Missing the required parameter 'accessToken' when calling getInvoices");
        } else {
            HttpHeaders headers = new HttpHeaders();
            headers.set("xero-tenant-id", xeroTenantId);
            headers.setAccept("application/json");
            headers.setUserAgent(this.getUserAgent());
            String correctPath = "/Invoices";
            UriBuilder uriBuilder = UriBuilder.fromUri(this.apiClient.getBasePath() + correctPath);
            String key;
            if (where != null) {
                key = "where";
                if (where instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)where).toArray());
                } else if (where instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])where));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{where});
                }
            }

            if (order != null) {
                key = "order";
                if (order instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)order).toArray());
                } else if (order instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])order));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{order});
                }
            }

            if (ids != null) {
                key = "IDs";
                if (ids instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)ids).toArray());
                } else if (ids instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])ids));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{ids});
                }
            }

            if (invoiceNumbers != null) {
                key = "InvoiceNumbers";
                if (invoiceNumbers instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)invoiceNumbers).toArray());
                } else if (invoiceNumbers instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])invoiceNumbers));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{invoiceNumbers});
                }
            }

            if (contactIDs != null) {
                key = "ContactIDs";
                if (contactIDs instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)contactIDs).toArray());
                } else if (contactIDs instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])contactIDs));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{contactIDs});
                }
            }

            if (statuses != null) {
                key = "Statuses";
                if (statuses instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)statuses).toArray());
                } else if (statuses instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])statuses));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{statuses});
                }
            }

            if (page != null) {
                key = "page";
                if (page instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)page).toArray());
                } else if (page instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])page));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{page});
                }
            }

            if (includeArchived != null) {
                key = "includeArchived";
                if (includeArchived instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)includeArchived).toArray());
                } else if (includeArchived instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])includeArchived));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{includeArchived});
                }
            }

            if (createdByMyApp != null) {
                key = "createdByMyApp";
                if (createdByMyApp instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)createdByMyApp).toArray());
                } else if (createdByMyApp instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])createdByMyApp));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{createdByMyApp});
                }
            }

            if (unitdp != null) {
                key = "unitdp";
                if (unitdp instanceof Collection) {
                    uriBuilder = uriBuilder.queryParam(key, ((Collection)unitdp).toArray());
                } else if (unitdp instanceof Object[]) {
                    uriBuilder = uriBuilder.queryParam(key, (Object[])((Object[])unitdp));
                } else {
                    uriBuilder = uriBuilder.queryParam(key, new Object[]{unitdp});
                }
            }

            key = uriBuilder.build(new Object[0]).toString();
            GenericUrl genericUrl = new GenericUrl(key);
            HttpContent content = null;
            Credential credential = (new Credential(BearerToken.authorizationHeaderAccessMethod())).setAccessToken(accessToken);
            HttpTransport transport = this.apiClient.getHttpTransport();
            HttpRequestFactory requestFactory = transport.createRequestFactory(credential);
            return requestFactory.buildRequest("GET", genericUrl, (HttpContent)content).setHeaders(headers).execute();
        }
    }

**Comment by SidneyAllen** [comment]
@Sayyiditow 

Great catch!!  I didn't realize in the rewrite for OAuth 2.0 that headers were not being set properly.  This should be resolved in version 3.1.5

Thank you for raising with us.

**Comment by Sayyiditow** [comment]
Cool thanks! Yw.
