### ISSUE TITLE
ReportTaxTypeEnum is missing some value

### ISSUE THREAD

**Issue by hieuxit** [XeroAPI/Xero-Java#167]
Version 2.3.21

The com.xero.models.accounting.TaxRate$ReportTaxTypeEnum is missing some value. That makes method getTaxRates failure in some organizations. I see all value are exist in 3.x version. Could you please add them to 2.x version also.

Thanks,

**Comment by MattR-Api** [comment]
Hi @hieuxit 

Thanks for getting in touch. 

With the release of OAuth 2.0 and the deprecation of OAuth 1.0a, we'll no longer be updating or supporting any OAuth 1.0a SDK's. We strongly suggest looking at an OAuth 2.0 solution for your app as soon as possible. 

Please feel free to clone the Repository and make any changes you wish. 

Kind Regards

Matt

**Comment by SidneyAllen** [comment]
@hieuxit 

This has been resolved in 2.3.22.
