### ISSUE TITLE
Please revert create attachment by ByteArray

### ISSUE THREAD

**Issue by sevendark** [XeroAPI/Xero-Java#169]
**SDK version:**
 - 3.1.6

**Describe the solution you'd like**
I need create attachment use byte array

**Additional context**
My file is not on my local, it's network file, now, i can only create attachment by File class, so, i need wirte file on local, then delete it, in old xero sdk version, we can create attachment by ByteArray, can we revert it?

**Comment by SidneyAllen** [comment]
@sevendark - no plans to revert to use ByteArray at this time.  I'll leave this issue open for discussion.

**Comment by lancedfr** [comment]
I agree. Writing a file to disk is resource intensive in this context.

The file is picked up by the underlying http client (google-http-client-1.23.0.jar) from disk and converted to byes to make the http request. To improve throughput the content should be accepted as bytes.

Xero-SDK can construct a com.google.api.client.http.HttpRequestFactory request using a com.google.api.client.http.ByteArrayContent instead of com.google.api.client.http.FileContent.

I also switched from using previous SDK and make use of File is not the best solution.

**Comment by lancedfr** [comment]
@SidneyAllen I'm happy to implement a solution to support byte array attachments. Our team will be making use of this feature in the near future.

Please see my commit here as a proposal lancedfr@2b14091 - for now I've only implemented createAccountAttachmentByFileName and createBankTransactionAttachmentByFileName methods to support byte array attachments; will work on the rest if the solution is ok with you. I've left TODO comments in my commit as there are still outstanding bits to complete.

Let me know what you think and if I should continue to implement this?

**Comment by SidneyAllen** [comment]
Hey @lancedfr - thank you for the nudge.  I've implemented a solution this morning that is very close to what you shared on your fork.  FYI @sevendark 

I've release 4.1.4.  I'm overloading the create/update attachment methods (20 of them).  

I used the following code to test the new method and it uploaded the attachment successfully into Xero.  You may take a slightly different approach, but thought I'd share this snippet of code for you and others.


    File input = new File("/Users/sid.maestre/eclipse-workspace/xero-sdk-oauth2-dev-01/resources/youngsid.jpg");
    java.nio.file.Path inputPath = input.toPath();
    String mimeType = Files.probeContentType(inputPath);
    byte[] byteInput = FileUtils.readFileToByteArray(input);
    String newFileName = input.getName();  

    try {
       where = "Status==\"ACTIVE\"";
       Accounts myAccounts = accountingApi.getAccounts(accessToken, xeroTenantId, null, where,null);

       if (myAccounts.getAccounts().size() > 0) {
         UUID accountID = myAccounts.getAccounts().get(0).getAccountID();
         Attachments createdAttachments = accountingApi.createAccountAttachmentByFileName(accessToken, xeroTenantId, accountID, newFileName, byteInput, mimeType);
       }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
