### ISSUE TITLE
The HTTP 400 response, which contains a useful summary for the error, is not completely included into the XeroApiException class

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#171]
### **SDK you're using: Xero-Java OAuth 2.0**
com.github.xeroapi : xero-java : 3.1.8

### **Describe the bug**
When an error is occurred while creating many invoices in a single API call, the information contained in the json error response is not completely deserialize to java.

### **To Reproduce**
In order to reproduce it, I will try to create two invoices without the required minimum data:
1. I invoke the method com.xero.api.client.AccountingApi#createInvoices 
2. And this method generates a single API call:
PUT https://api.xero.com/api.xro/2.0/Invoices
**Request body:** (create two invoices without the required minimum data)
`{ "Invoices": [
        { "InvoiceID": "efb43698-20c8-4906-9df5-66efa899096a", "Reference": "Test 1" }, 
        { "InvoiceID": "27983b5d-72fe-4a23-92d6-acc6116b763b", "Reference": "Red Fish, Blue Fish" }
 ]}`
**Response HTTP Status:** 
400 Bad Request
**Response body:** (useful summary for the error includes the validation errors for each invoice)
`{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "InvoiceID": "efb43698-20c8-4906-9df5-66efa899096a",
      "Reference": "Test 1",
      "Payments": [],
      "CreditNotes": [],
      "Prepayments": [],
      "Overpayments": [],
      "IsDiscounted": false,
      "HasErrors": true,
      "DateString": "2020-01-10T00:00:00",
      "Date": "/Date(1578614400000+0000)/",
      "Status": "DRAFT",
      "LineAmountTypes": "Exclusive",
      "LineItems": [],
      "SubTotal": 0.00,
      "TotalTax": 0.00,
      "Total": 0.00,
      "CurrencyCode": "GBP",
      "ValidationErrors": [
        {
          "Message": "One or more line items must be specified"
        },
        {
          "Message": "Invoice Type must be specified"
        },
        {
          "Message": "A Contact must be specified for this type of transaction"
        }
      ]
    },
    {
      "InvoiceID": "27983b5d-72fe-4a23-92d6-acc6116b763b",
      "Reference": "Red Fish, Blue Fish",
      "Payments": [],
      "CreditNotes": [],
      "Prepayments": [],
      "Overpayments": [],
      "IsDiscounted": false,
      "HasErrors": true,
      "DateString": "2020-01-10T00:00:00",
      "Date": "/Date(1578614400000+0000)/",
      "Status": "DRAFT",
      "LineAmountTypes": "Exclusive",
      "LineItems": [],
      "SubTotal": 0.00,
      "TotalTax": 0.00,
      "Total": 0.00,
      "CurrencyCode": "GBP",
      "ValidationErrors": [
        {
          "Message": "One or more line items must be specified"
        },
        {
          "Message": "Invoice Type must be specified"
        },
        {
          "Message": "A Contact must be specified for this type of transaction"
        }
      ]
    }
  ]
}`
3. Since we get an http 400 the createInvoices throws an XeroApiException
4. When I browse the informatin contained in the XeroApiException I am only be able to get the "ValidationErrors" information via `xeroApiException.getError().getElements().get(0).getValidationErrors()`
But i am not able to retrieve the information related with the invoice which causes the error like:
` "InvoiceID": "27983b5d-72fe-4a23-92d6-acc6116b763b", "Reference": "Red Fish, Blue Fish", "ValidationErrors": [ { "Message": "One or more line items must be specified" },`

### **Expected behavior**
The XeroApiException raised by the method com.xero.api.client.AccountingApi#createInvoices   should contain the reason for the error and the entity related to each error. This information was available in the version v2.3.16 xeroApiException.getApiException().getElements().get(0).getDataContractBase()

### **Question**
Would be posible to modify the XeroApiException implementation in order to be able to retrieve this information?

**Comment by SidneyAllen** [comment]
Hey @P3R3 

Checkout version 3.1.9.  When you createInvoices (multiple) and set "summarizeError=false" You will get a 200 OK status back from the API. 

The response will return ALL objects both successful and any with validations.  Use the "HasValidations" boolean to see if there were any errors on any objects and then read the array of validation errors.

If you pass summarizeError=true, you will get a status 400 and the response will only contain the objects that had a validation error.

Cheers.

**Comment by P3R3** [comment]
Hi @SidneyAllen ,

you are right, when I pass summarizeError=true I will get a status 400 and the response will only contain the objects that had a validation error:

`{
	"ErrorNumber": 10,
	"Type": "ValidationException",
	"Message": "A validation exception occurred",
	"Elements": [{
		"Type": "ACCREC",
		"InvoiceID": "6ee08ede-64ed-40b5-81bf-498658aa0ab4",
		"InvoiceNumber": "INV-0291",
		"Reference": "anotherInvoice Ref",
		"Payments": [],
		"CreditNotes": [],
		"Prepayments": [],
		"Overpayments": [],
		"AmountDue": 40.00,
		"AmountPaid": 0.00,
		"SentToContact": false,
		"CurrencyRate": 1.000000,
		"IsDiscounted": false,
		"HasErrors": true,
		"Contact": {
			"ContactID": "0aaa0620-225e-4f73-8efe-1d79309613c4",
			"ContactStatus": "ACTIVE",
			"Name": "Mixpanel",
			"Addresses": [{
				"AddressType": "STREET",
				"ValidationErrors": []
			}, {
				"AddressType": "POBOX",
				"ValidationErrors": []
			}],
			"Phones": [{
				"PhoneType": "DEFAULT",
				"ValidationErrors": []
			}, {
				"PhoneType": "DDI",
				"ValidationErrors": []
			}, {
				"PhoneType": "FAX",
				"ValidationErrors": []
			}, {
				"PhoneType": "MOBILE",
				"ValidationErrors": []
			}],
			"UpdatedDateUTC": "\/Date(1551276928767+0000)\/",
			"ContactGroups": [],
			"IsSupplier": true,
			"IsCustomer": true,
			"ContactPersons": [],
			"HasValidationErrors": false,
			"ValidationErrors": []
		},
		"DateString": "2020-01-17T00:00:00",
		"Date": "\/Date(1579219200000+0000)\/",
		"DueDateString": "2018-12-10T00:00:00",
		"DueDate": "\/Date(1544400000000+0000)\/",
		"Status": "DRAFT",
		"LineAmountTypes": "Exclusive",
		"LineItems": [{
			"Description": "Acme Tires",
			"UnitAmount": 20.0,
			"TaxType": "NONE",
			"TaxAmount": 0.00,
			"LineAmount": 40.00,
			"AccountCode": "120",
			"Tracking": [],
			"Quantity": 2.0000,
			"LineItemID": "257cfd6d-b5ef-4ce4-9f81-de2a1d536bba",
			"ValidationErrors": []
		}],
		"SubTotal": 40.00,
		"TotalTax": 0.00,
		"Total": 40.00,
		"UpdatedDateUTC": "\/Date(1579278350477+0000)\/",
		"CurrencyCode": "GBP",
		"ValidationErrors": [{
			"Message": "Invoice not of valid status for modification"
		}]
	}]
}`

But I don't know how to retrieve this information from the java code. When I get a status 400 an XeroApiException is raised. From the XeroApiException I am able to get the validation error: `xeroApiException.getError().getElements().get(0).getValidationErrors().get(0).getMessage();`
How can I to get the invoiceID that causes this validation error from the java XeroApiException class?

I would like to do something like that:
`xeroApiException.getError().getElements().get(0).getInvoiceID();`
But this method doesn't exist.

Would be posible to know which invoiceID causes each validation error from java?

Thanks

**Comment by SidneyAllen** [comment]
@P3R3 about to board a plane and then a 3 day weekend but wanted to let you know I pushed version 3.2.1 (hopefully it made it to maven central).

Added the IDs of objects that support createOrUpdate with summarizeErrors.  Give it a try in an hour.

**Comment by P3R3** [comment]
When an error succeed while invoking the endpoint:
PUT https://api.xero.com/api.xro/2.0/Payments
A XeroApiException is raised, but this exception don't contain the paymentId that has failed, it just contain other null identifiers:
  @JsonProperty("BatchPaymentID")
  @JsonProperty("BankTransactionID")
  @JsonProperty("CreditNoteID")
  @JsonProperty("ContactID")
  @JsonProperty("InvoiceID")
  @JsonProperty("ItemID")
  @JsonProperty("PurchaseOrderID")
Would it be posible to add the field PaymentID in the class com.xero.models.accounting.Element in order to be able to know whitch payment has processed with errors?

**Comment by mikconstantinou** [comment]
I know I'm late to the party, but for anyone else looking for a solution to @P3R3 's question, I extracted the relevant information from the exception by casting the _cause_ attribute of the _XeroBadRequestException_ to a _HttpResponseException_ and pulling the content:
`
((com.google.api.client.http.HttpResponseException)xeroBadRequestException.getCause()).getContent()
`
