### ISSUE TITLE
Xero-Java SDK don't allow specify the SummarizeErrors parameter in some method calls

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#172]
### **SDK you're using: Xero-Java OAuth 2.0**
com.github.xeroapi : xero-java : 3.1.8

### **Describe the bug**
While some methods allow you to specify SummarizeErrors parameter, other methods do not allow it:
- The method com.xero.api.client.AccountingApi#createInvoice(Invoices invoices, Boolean summarizeErrors) allow to create many invoices and also allow to specify the summarizeErrors parameter.
- The method com.xero.api.client.AccountingApi#updateInvoice(UUID invoiceID, Invoices invoices) allow to update many invoices but don't allow to specify the summarizeErrors parameter.

### **Question**
Would be posible to modify the AccountingApi implementation in order to be able to specify the summarizeErrors parameter in all methods that are able to operate with multiple entities (invoices, items, contacts) in a single API call?

**Comment by SidneyAllen** [comment]
@sevendark - thanks for call these out.  Working on a patch  - stay tuned

**Comment by SidneyAllen** [comment]
@sevendark  I've updated the OpenAPI spec and generated the code.

This should now be solved including batchpayments in release 3.2.0
