### ISSUE TITLE
The field "StatusAttributeString" is missing in some entities like Contact and Item class

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#173]
### **SDK you're using: Xero-Java OAuth 2.0**
com.github.xeroapi : xero-java : 3.1.8

### **Describe the bug**
The field "StatusAttributeString" is missing in some entities like Contact and Item class. This field indicates if the entity was successfully processed or could not be saved to Xero.

### **To Reproduce**
In order to reproduce it, I will try to create two items without the required minimum data:
1. I invoke the method com.xero.api.client.AccountingApi#createItems with summarizeErrors = false parameter
2. And this method generates a single API call:
PUT https://api.xero.com/api.xro/2.0/Items?SummarizeErrors=false
**Request body:** (create two items without the required minimum data)
`{
    "Items": [
        {
           "ItemID": "efb43698-20c8-4906-9df5-66efa899096a"
        }, 
        {
           "ItemID": "27983b5d-72fe-4a23-92d6-acc6116b763b"
        }
    ]
}`
**Response HTTP Status:** 
200 OK
**Response body:** (every entity is returned back to you, each having their own status attribute)
`{
  "Id": "e7f50f18-f60f-4c56-a9f4-7d4a70402a56",
  "Status": "OK",
  "ProviderName": "HSBC_Kinetic_localhost",
  "DateTimeUTC": "/Date(1578666563874)/",
  "Items": [
    {
      "ItemID": "00000000-0000-0000-0000-000000000000",
      "UpdatedDateUTC": "/Date(-62135596800000)/",
      "PurchaseDetails": {},
      "SalesDetails": {},
      "IsTrackedAsInventory": false,
      "IsSold": true,
      "IsPurchased": true,
      "StatusAttributeString": "ERROR",
      "ValidationErrors": [
        {
          "Message": "Price List Item Code must be supplied"
        }
      ]
    },
    {
      "ItemID": "00000000-0000-0000-0000-000000000000",
      "UpdatedDateUTC": "/Date(-62135596800000)/",
      "PurchaseDetails": {},
      "SalesDetails": {},
      "IsTrackedAsInventory": false,
      "IsSold": true,
      "IsPurchased": true,
      "StatusAttributeString": "ERROR",
      "ValidationErrors": [
        {
          "Message": "Price List Item Code must be supplied"
        }
      ]
    }
  ]
}`
3. The field "StatusAttributeString": "ERROR" is returned but is not deserialized into com.xero.models.accounting.Item 

### **Question**
Would be posible to modify the com.xero.models.accounting.Item  and com.xero.models.accounting.Contact implementation in order to contain the @JsonProperty("StatusAttributeString") field?

**Comment by SidneyAllen** [comment]
@P3R3 - added in version 3.2.0
