### ISSUE TITLE
Please support timeout param

### ISSUE THREAD

**Issue by sevendark** [XeroAPI/Xero-Java#174]
**SDK you're using:**
 - 3.1.9

** when i create payment by batch, i got Read time out error random**
```
java.net.SocketTimeoutException: Read timed out
 at java.net.SocketInputStream.socketRead0(Native Method)
```

**Describe the solution you'd like**
Can we support timeout param

**Comment by sevendark** [comment]
![image](https://user-images.githubusercontent.com/13547104/72310742-78b3f580-36bd-11ea-9581-fcdf54e86a5e.png)

I init Api Client use request factory, but it haven't check and use my request Factory in Accounting Api, Then, why i still need init Api Client use request factory? actually, i don't need set any param, just use access token to call Accounting api method.

`com.xero.api.client.AccountingApi#createAccountAttachmentByFileNameForHttpResponse`
![image](https://user-images.githubusercontent.com/13547104/72310929-098ad100-36be-11ea-90a8-736727b6af92.png)

Please check ApiClient config before using default http transaport to create request.

**Comment by SidneyAllen** [comment]
@sevendark - I saw the PR for this. Thank you very much!

Since the code you modified is part of our code templates (SDKS are now generated off our OpenAPI specs).  I will take your code and integrate it into the template - stay tuned

**Comment by SidneyAllen** [comment]
@sevendark Added to version 3.2.0
