### ISSUE TITLE
I need help compiling master branch, I would like to contribute to this project

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#177]
### **SDK you're using: Xero-Java OAuth 2.0**
com.github.xeroapi : xero-java : 3.1.9  branch master

### **Describe the bug**
I forked and cloned the repository and I  have found some issues trying to contribute to this project:
- Cannot resolve plugin org.apache.maven.plugins:maven3-deploy-plugin:2.8.1  
- When I execute "mvn compile" I get compilation failures:
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/SuperfundProducts.java:[34,8] class SuperFundProducts is public, should be declared in a file named SuperFundProducts.java
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/Superfunds.java:[34,8] class SuperFunds is public, should be declared in a file named SuperFunds.java
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/Payrun.java:[36,8] class PayRun is public, should be declared in a file named PayRun.java
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/SuperfundProduct.java:[31,8] class SuperFundProduct is public, should be declared in a file named SuperFundProduct.java
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/Superfund.java:[33,8] class SuperFund is public, should be declared in a file named SuperFund.java
    - [ERROR] /projects/Xero-Java/src/main/java/com/xero/models/payrollau/Payruns.java:[34,8] class PayRuns is public, should be declared in a file named PayRuns.java

**QUESTIONS:** Is the pluggin "maven3-deploy-plugin" right? The class name is not the same as the file name (for PayRun, SuperFundProduct, ...) is missing some special configuration to compile? Is it a typo error?

**Trying a little bit harder:**
I fixed these problems (renaming file names as class names, changing plugin to maven-deploy-plugin) on my local  and I was able to compile without errors, but when I execute "mvn test" I get errors like this:
- java.lang.NullPointerException at com.xero.api.client.AccountingApiInvoicesTest.setUp(AccountingApiInvoicesTest.java:66)
- It seems that the line "body = new File(classLoader.getResource("helo-heros.jpg").getFile());" is not able to find the file "helo-heros.jpg"

**QUESTION:** How should I configure my environment in order to do it work? 

**Trying a little bit harder again:**
I fixed this problem  (moving the file "helo-heros.jpg" inside the folder test/resources)  on my local and I was able to execute the tests, but the tests don't pass:
- Tests run: 169, Failures: 72, Errors: 0, Skipped: 0
- All the failures are related to dates:
    - java.lang.AssertionError: Expected: is <2017-10-20T11:14:21.613-07:00> but: was <2017-10-20T20:14:21.613+02:00>
- It seems that the mocked api "https://twilight-grass-2493.getsandbox.com:443/api.xro/2.0" is not returning the expected values.

**QUESTION:** Have the tests been broken? 

I would appreciate your help. Thanks

**Comment by SidneyAllen** [comment]
@P3R3 - Thanks for the feedback and PR on this project.  I'll respond below to your feedback.

1. Cannot resolve plugin org.apache.maven.plugins:maven3-deploy-plugin:2.8.1
*** I'm not getting errors around the dependencies and when I run "mvn compile" I get a BUILD SUCCESS - so not sure what could be the issue there.
I have updated the plugin name in the pom.xml to and it builds successfully
<plugin>
	<artifactId>maven-deploy-plugin</artifactId>
	<version>2.8.1</version>
</plugin>

2. Excellent catch on the file name difference.  I have gone into Github and renamed these
SuperFundProducts
SuperFundProduct
SuperFunds
SuperFund
PayRuns
PayRun

3. location of image we use for testing - it's fine to move it and update the tests to work with the new location

4. java.lang.AssertionError: Expected: is <2017-10-20T11:14:21.613-07:00> but: was <2017-10-20T20:14:21.613+02:00>
*** This one I could use some help fixing.  I work in SF and typically build with my machine clock set to PST.  I'm in Denver at the moment MST and I got the same error last night for the first time.  I wanted to get 3.2.0 released so I just changed my computer timezone to PST and it passed the tests.  If you have suggestion for fixing these in the test for date/time testing I'd be interested.

I'll commit the changes to the pom.xml to master so you can pull that into your fork and confirm we are on the same page moving forward -   Then can you update your PR?

**Comment by P3R3** [comment]
Hi @SidneyAllen , I have already updated my PR "Fix tests #178"
In order to avoid timezone problems I forced timezone for tests to GMT-08:00

**Comment by SidneyAllen** [comment]
@P3R3 - I tested your PR and everything compiled successfully.  I've merged the PR into master.
