### ISSUE TITLE
Serialization  issue

### ISSUE THREAD

**Issue by Prakash020710** [XeroAPI/Xero-Java#184]
Hi Team,

I am using Java SDK 3.1.1.
I am calling bank Transactions api and saving response in database. Before saving it to database, I am transforming this response to JSON string using jackson ObjectMapper. After this I am exposing a GET api to fetch this from database and building Object from again ObjectMapper.readValue(), it is throwing Wrong Date format exception from CustomDateDeserailzer as it is not in the expected format(yyyy-mm-dd).
After analysis I am not able to find any serialzer at your end which can be used for org.threeten.bp.LocalDate. Even if I use ThreeTenModule to do so, it is breaking again while deserializing.

Regards,
Prakash

**Comment by SidneyAllen** [comment]
Hi @Prakash020710 

I recommend you look at the documentation around date format returned by the API.
https://developer.xero.com/documentation/api/requests-and-responses

The SDK used annotation to deserialize MS Dateformat strings into Java date or datetime.

We've not done any testing transforming a Java Object into a Json response to save in a database and then retrieving the Json object from the database for use in the SDK.  This is a bit out of scope.

If you discover a solution and wish to submit a PR or comment on this issues with a solution, we'd be happy to look at it.
