### ISSUE TITLE
Query regarding Bank Transactions api

### ISSUE THREAD

**Issue by Prakash020710** [XeroAPI/Xero-Java#188]
Hi Team,

I am using Java sdk 3.3.0. There is a discrepancy in the number of bank transactions if I compare api with UI portal. Below is the api I am using through code : 
https://api.xero.com/api.xro/2.0/BankTransactions?where=Date%20%3E%3D%20DateTime(2019,%201,%201)%20%26%26%20Date%20%3C%3D%20DateTime(2020,%201,%2031)&page=1 

Number of transactions = 26.

However if I try with same tenantId and same date range in UI portal (https://reporting.xero.com/, 
 Report name : Account Transactions), I get 355 transactions.

Please note I am using Demo company. 

Regards,
Prakash

**Comment by wobinb** [comment]
The two things will return different results. The Account Transacations report in the UI will include all transactions coded to the selected account. This will include Spend/Receive Money transactions, payments, prepayments, overpayments and transfers.

The BankTransactions endpoint will only return Spend/Receive Money transactions. You would need to use the other endpoints to retrieve the remaining items.

**Comment by Prakash020710** [comment]
Hi Wobinb,

Thank you for the response. Could you please let me know the apis which constitute Account transactions of UI portal.

Thank you.

Regards,
Prakash
