### ISSUE TITLE
Ktor uses logback, log4j2 error comes out

### ISSUE THREAD

**Issue by asule90** [XeroAPI/Xero-Java#189]
**SDK you're using :**
 - xero-java version 3.4.0
 - Ktor 1.2.6

**Describe the bug**
I'm using [ktor.io](https://ktor.io/servers/index.html) to build Xero API service. ktor uses logback as its default logging. But xero SDK giving me this error:
`ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2`
although it is not blocking the runtime, but still bothers me showing error everytime i ran the service. Any problem with sdk build? any workaround?

**To Reproduce**
1. Create Ktor project
2. Setup logback logging
3. Add com.github.xeroapi:xero-java:3.4.0 to the gradle dependencies
4. run

**Expected behavior**
No error with dependency used by this sdk

**Additional context**
I did some workaround with creating empty log4j2.xml configuration inside resources folder
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration ></Configuration >
```
it works and not showing error when i run the service. But when i built it (which is using shadowJar minimize) and run the jar, error came back which i presume because shadowjar wiped the empty configuration.

**Comment by asule90** [comment]
solved with [log4j-slf4j adapter](https://logging.apache.org/log4j/2.x/log4j-to-slf4j/index.html). Is it considered as permanent solution or just temporary workaround?

**Comment by SidneyAllen** [comment]
I'll leave this open as an enhancement request.

previous version of the SDK had slf4j but didn't get implemented in the rewrite of the SDK

<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.28</version>
</dependency>

**Comment by SidneyAllen** [comment]
We've removed the Log4J dependency and replaced with slf4j  in  version 4.x of SDK
