### ISSUE TITLE
Unhandled http client exception

### ISSUE THREAD

**Issue by gtod** [XeroAPI/Xero-Java#19]
I called the `creaetContact` method with the simplest possible client, one with just a name.  It worked fine.

Then just to see what would happen I ran it again with the same name.  As expected this is an exception, you can't have duplicate names in Contacts.  But the exception I got came directly from the google HTTP client rather than being handled by Xero-Java itself and turned into (say) a `XeroApiException` exception.

I wonder if that is by design or omission?

```xml
Exception in thread "main" com.google.api.client.http.HttpResponseException: 400 Bad Request
<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>10</ErrorNumber>
  <Type>ValidationException</Type>
  <Message>A validation exception occurred</Message>
  <Elements>
    <DataContractBase xsi:type="Contact">
      <ValidationErrors>
        <ValidationError>
          <Message>The contact name Frodo Widgets is already assigned to another contact. The contact name must be unique across all active contacts.</Message>
        </ValidationError>
      </ValidationErrors>
      <ContactID>00000000-0000-0000-0000-000000000000</ContactID>
      <Name>Frodo Widgets</Name>
    </DataContractBase>
  </Elements>
</ApiException>
```

**Comment by SidneyAllen** [comment]
Hi @gtod - this is an omission.  We will eventually get to it, but welcome any pull requests to address this functionality.

**Comment by SidneyAllen** [comment]
Hi @gtod 

Added improved exception handling to the SDK.  It's mentioned in the README and now handled in the XeroClient.

Pull requests to fill in any cases not currently covered welcome.
