### ISSUE TITLE
Create ManualJournal XeroApiException

### ISSUE THREAD

**Issue by peteraldridge** [XeroAPI/Xero-Java#192]
I have been trying to figure out a way to reference which ManualJournal inside the ManualJournals object is causing an error if multiple ManualJournals are sent together in one request. From the Element list that is provided there is no journalID or any reference that would help in find the culprit. Currently I have been testing this by sending a charge that should be OUTPUT tax type as INPUT for one of two journals. What would you recommend? My clients would like to be able to know which journals are successful and which failed. Using v3.5.0

**Comment by SidneyAllen** [comment]
@peteraldridge 

Have you tried passing in the summarizeErrors param as "false"?

This will return a 200 with an array of all Manual Journals - you will need to loop over the array and evaluate the **StatusAttributeString , Warnings, and ValidationErrors** properties on each object to determine if there were any errors while creating that object.

ManualJournals createdManualJournals = accountingApi.createManualJournals(accessToken, xeroTenantId,
                        manualJournals, false);
