### ISSUE TITLE
The summarizeErrors option is not available in the createPayments method signature

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#199]
**XeroAPI / Xero-Java SDK**
 - Version [v 3.6.0]

**Describe the bug**
When an error succeed while invoking the endpoint:
PUT https://api.xero.com/api.xro/2.0/Payments
A XeroApiException is raised, but this exception don't contain the paymentId that has failed, it just contain other null identifiers:
@JsonProperty("BatchPaymentID")
@JsonProperty("BankTransactionID")
@JsonProperty("CreditNoteID")
@JsonProperty("ContactID")
@JsonProperty("InvoiceID")
@JsonProperty("ItemID")
@JsonProperty("PurchaseOrderID")
Would it be posible to add the field PaymentID in the class com.xero.models.accounting.Element in order to be able to know whitch payment has processed with errors?

**Expected behavior**
Would it be posible to change the current method signature:
`public PaymentServices  createPaymentService(String accessToken, String xeroTenantId, PaymentServices paymentServices) throws IOException;`
Allowing to specify the summarizeErrors parameter like:
`public PaymentServices  createPaymentService(String accessToken, String xeroTenantId, PaymentServices paymentServices, Boolean summarizeErrors) throws IOException;`

It would be great if I could specify the summarizeErrors parameters when I create several payments from the java code.

Thanks in advance :)

**Comment by SidneyAllen** [comment]
@P3R3 - this is resolved in version 4.0.1.  Note this is a breaking change release.  See the README.
