### ISSUE TITLE
Query params

### ISSUE THREAD

**Issue by slouc** [XeroAPI/Xero-Java#20]
Is there a way to set query params? For example, when fetching Reports. 

[Docs](https://developer.xero.com/documentation/api/reports) say:

> Each report has different optional parameters. The report parameters should be added as a separate query strings. For example: 
> GET https://api.xero.com/api.xro/2.0/Reports/AgedReceivablesByContact?fromDate=2010-01-01&toDate=2011-01-01

However, API only allows us to define "where" and "order" clauses (I thought I could do it via "where" by setting e.g. "date=2017-02-02" but nothing I tried worked).

So, how do I set query parameters (e.g. "date" for BalanceSheet)?

**Comment by SidneyAllen** [comment]
@slouc - we haven't added this functionality. Pull requests welcome.

**Comment by SidneyAllen** [comment]
Thanks to @slouc-spotcap for the contribution - additional report specific methods added to XeroClient.
