### ISSUE TITLE
Read socket default timeout of 20s is too short

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#200]
In the OAuth1 SDK the default socket read timeout was 60s. In OAuth2 the default time is 20s.

Since moving to OAuth2 we are seeing a small but significant percentage of API calls fail due to read socket timeout (logs of many examples, across different API calls, available via direct message).

I suggest changing the default SDK APIClient read socket timeout back to 60s.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 

We added support for setting the connectionTimeout in v3.2.0

If this doesn't work for your situation, please reopen this issue.

```
// Init AccountingApi client
ApiClient defaultClient = new ApiClient();
defaultClient.setConnectionTimeout(6000);

// Get Singleton - instance of accounting client
accountingApi = AccountingApi.getInstance(defaultClient);
```

**Comment by U3R1YXJ0** [comment]
I don't have hard data but I'd guess about 0.1% of our calls timeout with a 20s read timeout (and basically 0% at 60s).

Another option for improving the SDK would be to catch the socket exception and throw something more specific, informing the users where they can change the setting.
