### ISSUE TITLE
Found potential runtime exception

### ISSUE THREAD

**Issue by Wushuyi123** [XeroAPI/Xero-Java#201]
Hello,
First of all i want to thank you for sharing your code.
But when I was operating some of my files, there were runtime exceptions of the type  'java.lang.IlegalArgumentException' might happen. The runtime exceptions were from methods:
1. com.xero.models.accounting.Users.equals(java.lang.Object) 
```
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Users users = (Users) o;
    return Objects.equals(this.users, users.users);
  }
```
2. com.xero.models.accounting.OnlineInvoices.equals(java.lang.Object)
```
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnlineInvoices onlineInvoices = (OnlineInvoices) o;
    return Objects.equals(this.onlineInvoices, onlineInvoices.onlineInvoices);
  }
```
if caller pass object which can not be parsed to the target type like User or OnlineInvoices, it might cause the program to crash. But the caller may not know these problems and may cause the program to crash suddenly.
so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop. Thank you!

**Comment by SidneyAllen** [comment]
@Wushuyi123 

i've done a test and found the following results.

    Account a1 = new Account();
    Account a2 = new Account();            
    boolean result1 = a1.equals(a2);
    // true        
    System.out.println(result1);

    Object o = new Object();
    boolean result2 = a1.equals(o);
    // false
    System.out.println(result2);

I'm going to close this  issue - but if others find  a problem and wish to share a code fix I'd be happy to review.
