### ISSUE TITLE
Not propagating error detail from HttpResponseException to XeroApiException

### ISSUE THREAD

**Issue by daveseco7** [XeroAPI/Xero-Java#202]
SDK you're using :
	-xero-java version 3.6.0
	- java 8
Right now, while using **BankFeedsApi** if we, for instance, call `createStatements(token, tenantId, statements) `with an invalid statements object, let's say (inconsistent date objects) SDK throws a `XeroApiException()` containing 400 - Bad Request. While debugging SDK for more information regarding the error, a **HttpResponseException** is thrown and it has an error message detailing the error. Shouldn't the error message be bubbled up to the **XeroApiException** that is created?

**To Reproduce**
1. Create a statement object with the currentTime as _postedDate_ and a date in the past for _StartDate_ and _EndDate_
2. Debug catch statement in `createStatements()` method
3. Verify that **HttpResponseException** has a message detailing the error 
4. Verify that the resulting **XeroApiException** has no detail of the error

**Comment by SidneyAllen** [comment]
@daveseco7 - I see you closed this issue.

I wanted to let you know we are working on more robust exception handling.  This an some other major changes are being worked on for a 4.x release which will have some breaking changes, but will offer improved bubbling up of unique error messages.
