### ISSUE TITLE
Double to float lose percision in java

### ISSUE THREAD

**Issue by mahmoudzaki12000** [XeroAPI/Xero-Java#205]
**SDK you're using (java 8):**
 - Version [e.g. 2.3.10]

For LineItem unitAmount field you use float type, I use for this data in my system Double. when converting from Double to float in java it lose precision with minus or plus 0.01. This make invoice over paid or partially  paid. 

Reason: [https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html](https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html) section 5.1.3

**To Reproduce**
1. Use numbers like 524,094.27 or 557,757.76  in LineItem unitAmount
2. Define number a Double and then cast them to float.
3. Set float in the unitAmount you will find it change + or - 0.01.

**Screenshots**
issue invoice https://in.xero.com/AcJ8uETLb0ZC7iOlOyYQ2DCG3U4QkMTD3fDyXDq8  and
https://in.xero.com/tU5BDhwxzEDeSjk9D3oO2j8S2cdDXXMSeYLaEaQA

these are same invoices with same numbers after i changed float to double LineItem unitAmount :

https://in.xero.com/Rf2hpULp96DXlen4aWxopU1UR6EoK8m9ITqvMHrz
https://in.xero.com/ucNHtd2d6YFyhWmmWQevkKnzDMm8ZiLXSPq2PjRJ

**Comment by SidneyAllen** [comment]
@mahmoudzaki12000 - thanks for reporting this.  We are focusing our developer resources on version 4.x with support for OAuth 2.

If you wish to submit a PR for this issue, we can review it.

**Comment by ibrahimali123** [comment]
@mahmoudzaki12000 Thanks for reporting it, I faced the same issue too.

**Comment by SidneyAllen** [comment]
@mahmoudzaki12000 and @ibrahimali123 

If you or others do wish to submit a PR to address this issue - please do our pull requests against the "oauth1" branch and not master.  Master is version 4.x code base for OAuth 2.

**Comment by SidneyAllen** [comment]
If any folks still on OAuth 1 wish to make a PR - we can review it.  It's been 27 days so I'll close this one as abandoned.
