### ISSUE TITLE
AccountingApi.createBankTransferHistoryRecord() document with the supplied id was not found for this endpoint

### ISSUE THREAD

**Issue by krsadler** [XeroAPI/Xero-Java#209]
**SDK you're using (please complete the following information):**
 - Version 4.1.1

**Describe the bug**
`AccountingApi` method `createBankTransferHistoryRecord()` has a `ValidationError` stating: 

> "The document with the supplied id was not found for this endpoint."

However the `bankTransferID` provided is valid and has been used to retrieve existing history.

**To Reproduce**
Pass a valid `BankTransfer` object and a new `HistoryRecord` object (just create one and `setDetails("1066 Battle of Hastings")`) into the following method:

```Java
   public void updateBankTransferHistory(BankTransfer bankTransfer, HistoryRecord record) throws IOException {
        HistoryRecords history = this.accountingApi.getBankTransferHistory(token.getAccessToken(), config.getTenantId(), bankTransfer.getBankTransferID());
        for (HistoryRecord r : history.getHistoryRecords()) {
            LOG.info(r.getChanges() + " -- " + r.getDetails());
        }
        history.addHistoryRecordsItem(record);
        this.accountingApi.createBankTransferHistoryRecord(token.getAccessToken(), config.getTenantId(), bankTransfer.getBankTransferID(), history);
    }
```

**Expected behavior**
The example method should:

a) Retrieve and LOG the existing history record details.
b) It should add a new record to `history` and then update the BankTransfer with the new history.

It sucessfully performs (a) suggesting to me that the bankTransferID is valid for use with the BankTransfers endpoint, but it does not perform (b). Here is some log... you'll see the call to GET the history, it dumping the History (`Credit Applied...`) and the call to PUT the history...

```
2020-06-24 22:09:55,672 DEBUG [main] client.AccountingApi (AccountingApi.java:6103) - GET https://api.xero.com/api.xro/2.0/BankTransfers/709b575e-032d-4840-9966-310971c1a675/History
2020-06-24 22:09:55,994 INFO  [main] service.XeroClient (XeroClient.java:249) - Credit Applied -- Bank transfer from Amazon (UK) Suspense Account to Business Bank Account on 24 June 2020 for 234.56.
2020-06-24 22:09:55,995 DEBUG [main] client.AccountingApi (AccountingApi.java:752) - PUT https://api.xero.com/api.xro/2.0/BankTransfers/709b575e-032d-4840-9966-310971c1a675/History
2020-06-24 22:09:56,366 DEBUG [main] client.AccountingApi (AccountingApi.java:706) - ------------------ HttpResponseException 400 : createBankTransferHistoryRecord -------------------
2020-06-24 22:09:56,367 DEBUG [main] client.AccountingApi (AccountingApi.java:707) - com.google.api.client.http.HttpResponseException: 400 Bad Request
```
Here's the error:

```JSON
{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "Changes": "Credit Applied",
      "DateUTCString": "2020-06-24T21:09:55",
      "DateUTC": "\/Date(1593032995467+0000)\/",
      "User": "System Generated",
      "Details": "Bank transfer from Amazon (UK) Suspense Account to Business Bank Account on 24 June 2020 for 234.56.",
      "ValidationErrors": [
        {
          "Message": "The document with the supplied id was not found for this endpoint."
        }
      ]
    },
    {
      "DateUTCString": "2020-06-24T21:09:56",
      "DateUTC": "\/Date(1593032996203)\/",
      "Details": "DEV_KRS-BT-03",
      "ValidationErrors": [
        {
          "Message": "The document with the supplied id was not found for this endpoint."
        }
      ]
    }
  ]
}
```
I have also tried to update the history on the To and From `BankTransactions` using `createBankTransactionHistoryRecord()` and the appropriate `bankTransactionId`, but I get the similar results.

**Additional context**
I am trying to do this as a workaround for the lack of reference in BankTransfers. I need a way to be able to "backoff" transfers if there is a problem and I have not been able to do this reliably under SDK version 1, however I thought that with Version 4 I might be able to search on To Account, From Account and Amount, and then check the history records of the resulting transfers to find a note I placed at creation time (using the method above) to find the correct transfer to cancel.

**Comment by SidneyAllen** [comment]
@krsadler - This is a known issue with the API not supporting create history record for several endpoints.

I've raised this with the API team and it has been assessed and I expect a fix in the next 30 to 60 days.

I'll leave this issue open so I can notify you once it has been resolved.

**Comment by SidneyAllen** [comment]
@krsadler - This is a known issue with the API not supporting create history record for several endpoints.

I check with the API team and this won't be prioritized at this time.  The team's roadmap is full. We'll be removing any unsupported endpoints from the documentation and our OpenAPI specs as they shouldn't have been included since the functionality was not implemented.

I'll be closing this issue as it's not something we can solve via the SDK.

**Comment by krsadler** [comment]
@SidneyAllen fair enough. 

What I wanted to do was get a custom reference onto the transfer so I could look for it later (cf. bills and invoices where you can search for the reference) can you think of another "trick" I could use to do this - the only option I can think of now is to create and maintain a database/records outside of Xero to hold our reference and the transfer's UUID.

**Comment by SidneyAllen** [comment]
@krsadler - I'm sorry to say I don't know of any tricks.  Storing foreign key relationships in your db is probably the best path forward.

**Comment by SidneyAllen** [comment]
@krsadler - our API has turned around a fix for creating History records on unsupported endpoints.

We have merged the change into our OpenAPI specs and built version 4.1.3 of Xero-Java SDK to include it.
