### ISSUE TITLE
Not able to update/delete Contact/Invoice/Bill through accounting API 

### ISSUE THREAD

**Issue by njgandhi** [XeroAPI/Xero-Java#214]
Hello,

**SDK you're using (please complete the following information):**
 - Version [4.1.1]

**Describe the bug**
I am using xeroAPI SDK Java version for our integration which mainly do calls api for contacts, invoices, bills, journalentry. While doing so I found issue related to update or delete any object using api as specially when api needs to pass ID for object in url path. It says unexpected character found in URI.

**To Reproduce**
1. try to update any invoice using accounting API.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SidneyAllen** [comment]
@njgandhi - checking in to see if you are still having issues.

I'm not seeing enough details to offer any help with your issue.  You talk about working with several different endpoints and you mention updating or deleting objects say an "unexpected character found".

The SDK has quite a bit of use, and you're the first to report this issue.

Can you select one example and share the snippet of java code that executing the API call?  Also, can you share the error response and the name of your Xero App in case I need to look into the logs.

**Comment by njgandhi** [comment]
Hi @SidneyAllen,

Please find below code snipped for delete Invoice

**Comment by njgandhi** [comment]
@SidneyAllen 

For your reference https://github.com/XeroAPI/Xero-Java/issues/128

**Comment by SidneyAllen** [comment]
@njgandhi - Thanks for the reference to issue 128.

I'm afraid, this doesn't appear to be a problem inherent in the SDK, but most likely has to do with your environment and or a conflicting dependency.  

The last comment in issue #128 eludes to this.

**Comment by grantyb** [comment]
@SidneyAllen I think this actually is a problem inherent in the SDK. The usage of `UriBuilder.fromUri()` is invalid according to the documentation for that method. It states (emphasis mine):

> Parameters:
> _uri_ a URI that will be used to initialize the UriBuilder, **may not contain URI parameters**.

So, for example, this line (from **AccountingApi.java**):

```
UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath() + "/Invoices/{InvoiceID}");
```

should be implemented like this instead:

```
UriBuilder uriBuilder = UriBuilder.fromUri(apiClient.getBasePath()).path("/Invoices/{InvoiceID}");
```

I hope that this would be quite a simple change to your templates, and would enable access to many more of your APIs from Java.

**Comment by grantyb** [comment]
Note; this is a duplicate of #128 and #136. They all have the same underlying template issue.

**Comment by AscendingEagle** [comment]
Please re-open.

#128 and #136 **aren't duplicates**. Even if the underlying template issue is the same, both issues are now marked as closed, since this was apparently fixed for Invoices. However, the bug still remains for Contacts.
