### ISSUE TITLE
JWT.decode leading to javax.servlet.ServletException: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by I2AK** [XeroAPI/Xero-Java#215]
During Token Refresh, when I try to decode the access token using the following code

DecodedJWT jwt = JWT.decode(accessToken);

I am getting the following error:
javax.servlet.ServletException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readerFor(Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/ObjectReader;

I am using the following versions of the jar files
java-jwt-3.8.1.jar
commons-codec-1.12.jar
jackson-core-2.9.10.jar
jackson-databind-2.9.10.1.jar

Can some one help please? Many thanks.

**Comment by SidneyAllen** [comment]
@I2AK 

I'm not sure this question is related to our SDK.   It looks like you are using "java-jwt".  Our SDK includes the Auth0 library.

We have a TokenRefresh class in our "starter" app.
https://github.com/XeroAPI/xero-java-oauth2-starter/blob/master/src/main/java/com/xero/starter/TokenRefresh.java

This class imports these ...

import com.auth0.jwt.JWT;
import com.auth0.jwt.exceptions.JWTDecodeException;
import com.auth0.jwt.interfaces.DecodedJWT;

In order to run this line of code
https://github.com/XeroAPI/xero-java-oauth2-starter/blob/master/src/main/java/com/xero/starter/TokenRefresh.java#L36

**Comment by I2AK** [comment]
Hi Allen,

I have referred to the sample app at https://github.com/XeroAPI/xero-java-oauth2-app

The sample app uses the same jar files as I mentioned in my previous message.

If these are incorrect jar files, could you please recommend the correct jar files?

I am using the same imports as mentioned in your reply. And the Jar files are the same as used by the sample app. Still getting this error. On Windows 10 machine the code succeeds but in Linux environment it fails.

Thanks

**Comment by SidneyAllen** [comment]
@I2AK - check out our Java starter app.  I've updated it with an example of decoding the "id_token" from the tokenResponse.  

https://github.com/XeroAPI/xero-java-oauth2-starter/blob/master/src/main/java/com/xero/starter/AuthenticatedResource.java#L39

This approach should work passing in the access_token as well.

**Comment by I2AK** [comment]
Hi Sid,

The Xero developer website https://developer.xero.com/documentation/libraries/java is pointing to the app at https://github.com/XeroAPI/xero-java-oauth2-app

The sample app at https://github.com/XeroAPI/xero-java-oauth2-app used the xero-java-3.1.7.jar.

The new sample app suggested by you at https://github.com/XeroAPI/xero-java-oauth2-starter uses xero-java-4.0.1.jar.

There are some key differences and we will have to revise our code accordingly.

But I am unable to find any documentation for xero-java-4.0.1.jar.

The key issues are the following:
*The function createContact  from the Accounting API has been removed. The new function is createContacts, but there is a new boolean variable in the function call and we are not sure what it is about.

*The function createInvoice from the Accounting API has been removed. The new function is createInvoices but there are few new parameters and we are not sure what those parameters are all about.

It would be very kind of you if you could point me to the documentation?

Many thanks and I look forward to your helpful reply.

**Comment by SidneyAllen** [comment]
Hi @I2AK 

You may be looking at an old version of the xero-java-oauth2-app code.  We've recently updated the code including the SDK dependency in the pom.xml to 4.1.2

    <dependency>
        <groupId>com.github.xeroapi</groupId>
        <artifactId>xero-java</artifactId>
        <version>4.1.2</version>
    </dependency>

Regarding your question about the "createContact" method.  Without diving into all the details, our new SDKs are built by OpenAPI specifications and we can only define one instance of an endpointpath + method.  The one being used by "createContact" actually needed to be used for "updateOrCreateContact" method.    For this reason, createContact is no longer available in our SDKs.  

How do you create a single contact?  use the "createContacts" method and pass a single contact in the array.

What is the purpose of the boolean variable?  This is for the optional "summarizeErrors" feature.  The default value is FALSE.  

It is possible to submit more than one contact in a single API call. If you plan to submit more than one entity per API call, we recommend that you append the summarizeErrors=false querystring to your API call. This ensures that every entity is returned back to you, each having their own status attribute.

For createInvoices, the two parameters are summarizeErrors (similar to above) and unitDp.  The default is 2 decimal points, but you can specify up to 4.

**Comment by I2AK** [comment]
Hi Sid,

Many thanks for your help. We have now successfully integrated with Xero.

To help others who may face the same issue as we did:
Regarding the errors we were previously facing as per the first post in the thread. The error was occurring because jackson jar file contents were pre packaged twice in another jar file from another third party integration partner we have. The two jar files were conflicting with different versions of jackson jar file contents. After resolving this conflict, the error was gone.

Thanks again. You may close the issue now.
