### ISSUE TITLE
TokenStorage Class not found

### ISSUE THREAD

**Issue by waqarys** [XeroAPI/Xero-Java#22]
I am unable to find TokenStorage.java in xero-java-sdk-0.0.8.jar 
I am unable to make proper imports and run on server.

**Comment by SidneyAllen** [comment]
Hi @waqarys - TokenStoraga.java is not used inside the Xero-Java SDK, but is an "example" interface for saving and retrieving access tokens.   The full example code can be found in this repo - including the TokenStorage.java.

https://github.com/XeroAPI/Xero-Java/tree/master/example/src/main/java/com/xero/example

Hope this helps.
