### ISSUE TITLE
Add application exception hierarchy

### ISSUE THREAD

**Issue by lancedfr** [XeroAPI/Xero-Java#221]
**SDK you're using (please complete the following information):**
 - Version 4.1.2

**Is your feature request related to a problem? Please describe.**
Exception handling in client applications are bulky as they have to handle for 8 different exception types. If we implement an exception super class (or hierarchy) that all other Xero exceptions extend then client application only need to handle a subset of exceptions

**Describe the solution you'd like**
Add an exception hierarchy that all other Xero exceptions extend from.

I am happy to implement if agreed. Proposed exception hierarchy would look something like the below

XeroException (a new base exception)
->XeroAuthenticationException (a new exception for authentication errors extends XeroException)
-->XeroForbiddenException (extends XeroAuthenticationException)
-->XeroUnauthorizedException (extends XeroAuthenticationException)
->XeroApiException (extends XeroException)
->XeroBadRequestException (extends XeroException)
->XeroMethodNotAllowedException (extends XeroException)
->XeroNotFoundException (extends XeroException)
->XeroRateLimitException (extends XeroException)
->XeroServerErrorException (extends XeroException)

**Comment by SidneyAllen** [comment]
@lancedfr - I like that idea and appreciate you offering to work on it.  

Since exception classes are not part of our code generation, your pull request can be merged without conflict.

Look forward to seeing your PR.

I assume this change is not a breaking change and existing integrations won't be negatively impacted?

**Comment by lancedfr** [comment]
Hi @SidneyAllen, the change is not a breaking change and will work fine with existing client implementations. I have not changing any method signatures and all methods still throw the same exceptions.

The change adds 2 new exceptions, XeroException and XeroAuthenticationException. Both of which extend RuntimeException because all existing Xero exceptions already extend RuntimeException. Then I changed the existing Xero exceptions to either extend XeroException or XeroAuthenticationException.

The above means that client implementations can chose to catch and handle XeroException and/or XeroAuthenticationException ;- or they can continue to catch and handle what ever exceptions they already catch and handle.

**Comment by SidneyAllen** [comment]
@lancedfr merged #224 - thank you!

Any interest in updating the README with the improved try/catch 🙂

**Comment by lancedfr** [comment]
Thanks @SidneyAllen , I forgot about the README. Will have this done the next chance I get
