### ISSUE TITLE
Allow Config to be defined without a JSON file

### ISSUE THREAD

**Issue by GuiSim** [XeroAPI/Xero-Java#23]
Right now the Config object is tightly bound to a resource named "Config.json".
Even if you provide another name, the default value is read in various places.

https://github.com/XeroAPI/Xero-Java/blob/84a7010a2592f1d69c5025d309319295f136654f/example/src/main/java/com/xero/example/RequestResourceServlet.java#L24
https://github.com/XeroAPI/Xero-Java/blob/0b31e63d365404f80812516692f5e6e9f6b9ea53/src/main/java/com/xero/api/XeroClient.java#L103

I think it would be better for Xero-Java to avoid coupling itself so tightly to the Config class. Since the Config class is tightly coupled to the JSON file, this makes it so the whole library depends on the existence of this file.

Suggestions:
- Move Config to an interface
- Have an implementation that uses the JSON file
- Never default to a specific file, ask for the config to be provided when constructing objects that need a config

This way, we could create our own implementations of Config that do not depend on a file.

If I were to submit a PR with these changes, is there any chance it would be accepted?

**Comment by SidneyAllen** [comment]
@GuiSim  - I'll be closing issue - looks like PR #30 addresses this.
