### ISSUE TITLE
Files API On 2.0 

### ISSUE THREAD

**Issue by keerthikrishnan1987** [XeroAPI/Xero-Java#232]
We are looking to use Files API which is only on 1.0. But from your description, 1.0 is going to be deprecated by March 2021 without it being in 2.0 at all. 
I cannot see any branch where there is any active development for Files API too on 2.0.
Can you please give an update on it?

**Comment by SidneyAllen** [comment]
@keerthikrishnan1987 

We have been building out our OpenAPI specs we use for generating our SDKs.  We've just completed NZ Payroll and Java SDK is the first to incorporate it.  The next OpenAPI spec to implement is the Files API 

Our goal is to have support for the Files API by the end of 2020.

**Comment by keerthikrishnan1987** [comment]
@SidneyAllen Is there any timeline on Files API? I can see on OpenAPI where it says it is under development but was in the same status from last October I believe. Can you please give us an update? Cheers.

**Comment by SidneyAllen** [comment]
@keerthikrishnan1987 - thanks for following up.  Yes, this is something we'll be starting work on soon.

**Comment by SidneyAllen** [comment]
@keerthikrishnan1987 - version 4.7.0 files released with Files API support
https://github.com/XeroAPI/Xero-Java/releases/tag/4.7.0
