### ISSUE TITLE
Can't create an attachment if the filename contains a '#' character

### ISSUE THREAD

**Issue by GnTeezer** [XeroAPI/Xero-Java#237]
We're using 4.3.0 of the Java SDK.

Calling createCreditNoteAttachmentByFileName or createInvoiceAttachmentByFileName with filenames containing '#' causes the attachment to be rejected with a XeroBadRequestException with a message of "The file couldn't be uploaded because it isn't a supported file type".

If we encode the filename it works but the documentation [here ](https://developer.xero.com/documentation/api/attachments) says that file name only needs to be encoded if it contains brackets and it should not be encoded otherwise.

**Comment by SidneyAllen** [comment]
@GnTeezer  - There are characters which are incompatible with resource URLs.  I suspect "#" is one of them.

Did encoding fix this issue for you?  In an earlier version of the Java SDK we had a method that cleansed any special characters and replaced them with underscores.  I don't believe we kept that approach in the SDK.  If you created a helper method, you could implement the same for your integration.

When performing a GET on attachments, it's recommended you use the AttachmentId and not Get by Filename as special characters can cause problems on GETs as well.

**Comment by GnTeezer** [comment]
@SidneyAllen - encoding seems to fix the problem and we're happy to do that assuming it is ok to encode it. 

Our concern around encoding the filename was that the documentation specifically says that you should not encode the filename unless it contains brackets (see [here](https://developer.xero.com/documentation/api/attachments)).

**Comment by SidneyAllen** [comment]
@GnTeezer - double checked with API team and the docs are incomplete.  You should encode special chars OR you could replace the special chars with dashes or underscores which would make them compatible on GET as well.
