### ISSUE TITLE
Support attachment upload

### ISSUE THREAD

**Issue by GuiSim** [XeroAPI/Xero-Java#24]
Hi! 

Any plans on supporting attachment upload/download?
https://developer.xero.com/documentation/api/attachments

Thanks!

**Comment by trungie** [comment]
Hi @SidneyAllen, sorry i accidentally included this in pull request #30. 

You should be able to close this one.

**Comment by GuiSim** [comment]
Thanks!

**Comment by SidneyAllen** [comment]
Thanks @trungie  - i'll keep it open until I've added "example" how to use the attachment methods you contributed.

**Comment by SidneyAllen** [comment]
version 0.3.3 now supports attachments and examples
