### ISSUE TITLE
Aust Payroll, issue when updating Employee

### ISSUE THREAD

**Issue by rkennewell** [XeroAPI/Xero-Java#241]
**SDK you're using (please complete the following information):**
 - Version [Xero-Java-4.3.5] Australian Payroll API

**Describe the bug**
When making an update to an Employee, I get the following response

```
2020-11-16 23:44:17,900 () ERROR (XeroUsers.java:323) - class Error {
    statusCode: 400
    type: null
    message: 400 Bad Request
    POST https://api.xero.com/payroll.xro/1.0/Employees/be2547cf-6f41-4353-bb25-9db5b1b64c52
    <Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ErrorNumber>0</ErrorNumber><Type>Error</Type><Message>openingBalanceDateAsDate is not a valid element in OpeningBalances</Message></Response>
    elements: []
}
```
**To Reproduce**
On the PayrollAuApi use getEmployee to load an existing employee using the UUID, modify the object and then write back using updateEmployee.

**Expected behavior**
Should be able to update Employee.

**Possible Solution**
In com.xero.models.payrollau.OpeningBalance.java add the @JsonIgnore to the getOpeningBalanceDateAsDate() method. The @JsonIgnore may need to be applied to all getXXXDateAsDate methods as well.
```
  @JsonIgnore()
  public LocalDate getOpeningBalanceDateAsDate() {
    if (this.openingBalanceDate != null) {
      try {
        return util.convertStringToDate(this.openingBalanceDate);
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
    return null;
  }
```

**Comment by SidneyAllen** [comment]
@rkennewell - Thanks for sharing this feedback.  I'm not sure @JsonIgnore would be the correct approach.  I'm going to assume that on deserialization of a  GET for a single employee would not include the OpeningBalance property and that would be problematic for developers looking to retrieve that data.

I did my own test and found the following ....

Performed a getEmployees (to get all employees)

        Employees employees = payrollAuApi.getEmployees(accessToken, xeroTenantId, null, null, null, null);
                
Performed a getEmployee (to get all the details for a unique employee - this included a populated OpeningBalance).

        UUID employeeId = employees.getEmployees().get(0).getEmployeeID();
        Employees oneEmployees = payrollAuApi.getEmployee(accessToken, xeroTenantId, employeeId);
                
Updated the middle name on the returned unique employee and set OpeningBalance and TaxDeclaration to null.
              
       oneEmployees.getEmployees().get(0).setMiddleNames("Chad");
       oneEmployees.getEmployees().get(0).setOpeningBalances(null);
       oneEmployees.getEmployees().get(0).setTaxDeclaration(null);
       Employees empUpdated = payrollAuApi.updateEmployee(accessToken, xeroTenantId, employeeId, oneEmployees.getEmployees());
                
The other option is to create a new Employee object and populate it with just the values you wish to update for that employee.  That is actually, more efficient as you're not passing back a fully populated employee object with only a few properties that have actually changed.

**Comment by rkennewell** [comment]
Thanks @SidneyAllen. That basically solves the problem I have.

>I'm not sure @JsonIgnore would be the correct approach. I'm going to assume that on deserialization of a GET for a single employee would not include the OpeningBalance property and that would be problematic for developers looking to retrieve that data.

Not quite sure what you mean by that. However, I don't think the serialization of the OpeningBalance object (or similar objects) should include tags for helper functions such as getOpeningBalanceDateAsDate as thus should have the @JsonIgnore() tag. It doesn't seem to affect the deserialization of the object.
