### ISSUE TITLE
Wrong date format exception when synchronizing invoice though xero accounting API 

### ISSUE THREAD

**Issue by bolarge** [XeroAPI/Xero-Java#243]
Hi,

I am using xero-java-sdk 4.3.3

I want to sync invoices to xero and am getting  wrong date format issue when making calls with xero accounting api to create invoices. Below is my code.

  Invoices xeroInvoices = new Invoices();
  final com.xero.models.accounting.Invoice xeroInvoice = new com.xero.models.accounting.Invoice();
  xeroInvoice.setType(com.xero.models.accounting.Invoice.TypeEnum.ACCPAY);
  xeroInvoice.setDate(XeroUtils.convertToLocalDate(billforwardInvoice.getPeriodStart()));  //"DateString": "2020-11-28T00:00:00",
  xeroInvoice.setDueDate(XeroUtils.convertToLocalDate(billforwardInvoice.getPeriodEnd()));
  xeroInvoice.setContact(contact);
  Invoices xeroInvoicesBag = client.createInvoices(xeroConfiguration.getAccessToken(),xeroConfiguration.getXeroTenantId(),
                xeroInvoices,true, 1);

Initially the exception was with the format for both date and dueDate which I then formatted  to ISO_DATE_TIME to look like this e.g. Local Date is: 2020-12-01T10:30:28

Below are the exception stack trace
**com.fasterxml.jackson.databind.JsonMappingException: Wrong date format (through reference chain: com.xero.models.accounting.Invoices["Invoices"]->java.util.ArrayList[0]->com.xero.models.accounting.Invoice["dateAsDate"])**

Caused by: java.lang.IllegalArgumentException: Wrong date format
	at com.xero.api.StringUtil.convertStringToDate(StringUtil.java:89)
	at com.xero.models.accounting.Invoice.getDateAsDate(Invoice.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by SidneyAllen** [comment]
@bolarge - Is this your helper method? 

XeroUtils.convertToLocalDate()

Note, we are using org.threeten.bp.LocalDate;
https://www.threeten.org/threetenbp/

**Comment by bolarge** [comment]
Hi Sidney.

You are right, my further review narrowed the issue to same spot (wrong package reference). 

Thanks
