### ISSUE TITLE
contactPersons array is always empty

### ISSUE THREAD

**Issue by MatusiakMichal** [XeroAPI/Xero-Java#245]
**SDK you're using (please complete the following information):**
 - Version 4.5.0

**Describe the bug**
"contactPersons" is always an empty array despite being filled in contact when requesting by where condition
```java
public Contacts getContacts(
      String accessToken,
      String xeroTenantId,
      OffsetDateTime ifModifiedSince,
      String where,
      String order,
      List<UUID> ids,
      Integer page,
      Boolean includeArchived)
```

**To Reproduce**
1. Create contact in xero either via api or manually
2. Call getContact with WHERE condition ContactNumber==""
3. returned contacts have always contactPersons as empty array

**Expected behavior**
contactPersons should be filled with proper data

**Comment by SidneyAllen** [comment]
@MatusiakMichal - thanks for your question.

When calling "getContacts" method Xero's API does not return all the details for each contact.  To get full details you should use the "getContact" method and pass in a specific contactID.

You can also try passing the page param when using getContacts.  This will return the first 100 contacts with some additional details.
