### ISSUE TITLE
Xero Put items endpoint failing

### ISSUE THREAD

**Issue by cb-madhukiran** [XeroAPI/Xero-Java#246]
**SDK you're using (please complete the following information):**
 - Version [e.g. 4.4.0]

**Describe the bug**
I m trying to use the put endpoint for creating items. I m trying to create multiple items with one of the account code is wrong it is throwing an exception as **XeroServerException** but the same thing is working if all the account codes are correct
com.google.api.client.http.HttpResponseException: 500 Internal Server Error
{"Title":"An error occurred","Detail":"An error occurred in Xero. Check the API Status page http://status.developer.xero.com for current service status.","Status":500,"Instance":"10579380-fb6b-483d-8182-b59e5aca10d4"}

We are using the function create items in AccountingApi class and summarize errors param was false

**Expected behavior**
It should provide item-level validation errors instead of throwing 500 errors

**Comment by SidneyAllen** [comment]
@cb-madhukiran - Thanks for the question

The purpose of summarizeErrors=false when used in the creation of multiple objects is to either return a 200 (if one or more objects are successfully created - the response will include ALL objects both successful and those with validation errors).

summarizeErrors=true when used will return a 400 and the response will ONLY include objects with validation errors.

This doesn't sound like an issue with the SDK, and may require some one on one investigation with our API support team.  Please drop them a message at api@xero.com with details like your APP_ID and specifics around the 500 error so they can assist.

I did a test with the following code - I changed the 3rd argument on the method to true and false and received a 200 or 400.

    // Modify Item and FORCE error to test SummarizeError
    Item item3 = new Item();
    item3.setCode("abc123");
    item3.setDescription("foobar");
    item3.setName("Hello" + loadRandomNum());
    newItems.addItemsItem(item3);

    Items newItemsToUpdate = new Items();
    newItemsToUpdate.addItemsItem(item3);
                
    Item item4 = new Item();
    item4.setItemID(newItems.getItems().get(1).getItemID());
    item4.setCode("abc");
    newItemsToUpdate.addItemsItem(item4);
                
    Item item5 = new Item();
    item5.setCode("abc");
    item5.setDescription("foobar");
    item5.setName("Hello");
    newItemsToUpdate.addItemsItem(item5);
               
    // CREATE or UPDATE multiple items
    Items udpatedItems = accountingApi.updateOrCreateItems(accessToken, xeroTenantId, newItemsToUpdate,false,2);

**Comment by SidneyAllen** [comment]
@cb-madhukiran - did my response above help?

**Comment by SidneyAllen** [comment]
Closing as it appears issue has been resolved.
