### ISSUE TITLE
Connection Reset when refreshing token

### ISSUE THREAD

**Issue by felipeo0611** [XeroAPI/Xero-Java#248]
Hi,

I'm intermittently getting a connection reset error when trying to refresh the token. This isn't really an issue with the sdk but I was wondering if you could point me in the right direction on why this might be happening or if it might be a known issue from your side?

We are using spring social to handle the authorization and token refresh and we often get this exception:
I/O error on POST request for "https://identity.xero.com/connect/token": Connection reset; nested exception is javax.net.ssl.SSLException: Connection reset java.net.SocketException: Connection reset at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186) ~[na:na] at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)

Kind regards,
Felipe

**Comment by SidneyAllen** [comment]
@felipeo0611 - can you contact our support team at api@xero.com as this isn't and SDK issue.

**Comment by felipeo0611** [comment]
Yes I did and they told me to contact you, I replied that it wasn't an SDK issue as refreshing tokens is not handled by the SDK and they replied with "yes it is" and they referred to the RefreshToken.java example here in github. I replied that they were wrong about that but that I would still contact you since they insist, but I guess I'll go back to them and link your reply then.
