### ISSUE TITLE
Credit Note - Warnings List is missing

### ISSUE THREAD

**Issue by jawad-r3** [XeroAPI/Xero-Java#254]
**SDK you're using (please complete the following information):**
 - Version 4.5.3

**Describe the bug**
I have been looking into Credit Note Endpoint and noticed that although in API Previewer we get Warning List response its corresponding object is missing from Java API Models.

**To Reproduce**
1. Go to API Previewer
2. Click on Credit Notes from Dropdown and Select with Minimum XML
3. Submit POST request.
4. Check Warning List returned in Response.
5. Check-in Credit Note model that warning object is missing but its available in Invoice object.

**Expected behavior**
Warnings must be part of the Credit note model schema as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/70772716/106770867-33fc5300-6660-11eb-98a2-b572477b9537.png)

**Comment by SidneyAllen** [comment]
@jawad-r3 - please look at release 4.6.0 when you have a moment.

If you can confirm the fix we made works, then I'll close this issue.

**Comment by jawad-r3** [comment]
@SidneyAllen I have tested it from App and I can see Warning nows. Thanks, you may close this issue.
