### ISSUE TITLE
Create/Update Credit Note - Line Item Identifier is missing in response

### ISSUE THREAD

**Issue by jawad-r3** [XeroAPI/Xero-Java#255]
SDK you're using (please complete the following information):

Version 4.5.3

**Describe the bug**
I am trying to create a credit note via the REST API client. When creating a credit note API returns 200 OK responses but created item lines don't have identifiers attached to them.

**To Reproduce**

Go to API Previewer
Click on Credit Notes from Dropdown and Select with Minimum XML
Submit PUT request.
Check Item Lines in response.
Notice that Line Item ID is missing, Same is the case for SDK calls.

**Expected behavior**
Line Item must have a valid identifier on it as its the case for Invoice Line items as well.

**Comment by SidneyAllen** [comment]
Hi @jawad-r3 

Thanks for raising the issue.

Regarding the line_item_id not being returned with CreditNotes. This is a known issue with the API and therefore can't be addressed in client SDK. I have followed up with our API team to see if we can get it addressed in the future.

I do want to set your expectations properly. We receive a significant number of requests for our API team and they prioritize these requests accordingly.

I'll be closing this issue as it's not directly related to the SDK.  I will update this issue when it's been addresses in the API and rolled into our SDKs.
