### ISSUE TITLE
No way to set payment type in Payment object

### ISSUE THREAD

**Issue by irahavoi-veem** [XeroAPI/Xero-Java#256]
I am migraring my application from Xero Java SDK version 2 to version 4.5.3

In the old version of SDK I was able to set payment type via setter:

`xeroPayment.setPaymentType(paymentType);`

New SDK does not provide a setter for paymentType attribute. Neither does it allow to set it via constructor:

https://github.com/XeroAPI/Xero-Java/blob/9f38fdf88c313845bfd2e3ff6777cd70c5e89c41/src/main/java/com/xero/models/accounting/Payment.java#L152

How should the clients of the new SDK define payment type?

**Comment by SidneyAllen** [comment]
@irahavoi-veem - Thanks for reaching out.  The paymentType property on the Payment Object is readOnly.

That property is determine by the object the payment is being applied to Invoice AR, AP, etc.  Xero sets the property type to read.

If there was a setter previously, that may have been an accident.  Setting the paymentType for a create or update method would be ignored by the API.
