### ISSUE TITLE
HTTP read timeout exception

### ISSUE THREAD

**Issue by lancedfr** [XeroAPI/Xero-Java#259]
**SDK you're using (please complete the following information):**
 - Version 4.4.0

**Describe the bug**
When making an HTTP connection to Xero we get HTTP socket read timeout errors. 

Root cause exception: java.net.SocketTimeoutException
Parent exception type: java.io.IOException

Below the stack trace is trying to get once invoice by number results in HTTP read timeout exception
`
{"method":"execute","line":105,"class":"com.google.api.client.http.javanet.NetHttpRequest"}
{"method":"execute","line":981,"class":"com.google.api.client.http.HttpRequest"}
{"method":"getInvoicesForHttpResponse","line":13068,"class":"com.xero.api.client.AccountingApi"}
{"method":"getInvoices","line":12879,"class":"com.xero.api.client.AccountingApi"}
{"method":"getInvoiceByNumber","line":323,"class":"com.billdoza.service.xero.XeroApiService"}
`

Below the stack trace is trying to get a items results in HTTP read timeout exception
`
{"method":"execute","line":105,"class":"com.google.api.client.http.javanet.NetHttpRequest"}
{"method":"execute","line":981,"class":"com.google.api.client.http.HttpRequest"}
{"method":"getItemsForHttpResponse","line":13354,"class":"com.xero.api.client.AccountingApi"}
{"method":"getItems","line":13262,"class":"com.xero.api.client.AccountingApi"}
{"method":"getItems","line":357,"class":"com.billdoza.service.xero.XeroApiService"}
`

**To Reproduce**
Use the SDK to fetch 

**Expected behaviour**
Timeout exception not to occurred  

**Screenshots**

**Additional context**
In the past month we got 272 HTTP read timeout exceptions. Our current read timeout is set to 60000ms.

**Comment by lancedfr** [comment]
We tested this again using timeout of 120000ms (2 minutes) and still ran into HTTP timeout error

```      
ApiClient apiClient = new ApiClient();
apiClient.setConnectionTimeout(120000);
apiClient.setReadTimeout(120000);
```

**Comment by SidneyAllen** [comment]
@lancedfr - I don't think this issue is SDK related but is more around response time from the API.

I checked with the engineering team and many calls will run for as long as 5min, so you could try setting that as your timeout.

As to why it takes this long, it could be network connectivity /latency issues at any of the hops, or it could be dealing with a large amount of data, or some other connection could be slowing the responsiveness of the server due to concurrently loading a lot of data.

**Comment by lancedfr** [comment]
Thanks for the feedback @SidneyAllen, we will test this with a 5 minute timeout. Our error logs defiantly show something strange. Will provide feedback soonest.

**Comment by U3R1YXJ0** [comment]
@lancedfr I previously opened https://github.com/XeroAPI/Xero-Java/issues/200 regarding this. We are also on a 5 min socket timeout now after finding 2min still gave up fairly regular timeouts. 5min seems OK. I can't recall if we've go to zero failures but its certainly very rare now.

**Comment by lancedfr** [comment]
Thanks Stuart for this feedback. We suspect its the HTTP connection pooling and/or stale connection check being disabled. Depending on the HTTP client implementation, the Google HTTP client library creates a pool of HTTP connections (which may be problematic if the HTTP resource does not support "keep alive" connections), it also disables stale connection checking (which will result in the connection failing immediately). Unfortunately we have not tested the above theories, or tested 5 minute timeout yet.

https://hc.apache.org/httpclient-legacy/performance.html#Stale_connection_check
//cant find link to connection pooling, but the Google HTTP client library creates a pool of 20 per http route

We have found the connection timing out on fetching invoice by ID, which I'd think should not take more than 20 seconds. In some cases 5 minutes might be too long for us to wait as we strive towards short time to reach consistency between our system and Xero :(

**Comment by lancedfr** [comment]
Hi @SidneyAllen, last week we increased our timeout to 5 minutes which has helped, we only had 2 read timeouts. The week prior our read timeout was 4 minutes where we had 33 read timeouts. For added measure we have disabled HTTP connection pooling and enabled stale connection checking. We do not think these 2 setting will make a difference, we still testing them.

We have changed our event processing to retry at a later stage if there any read timeouts so this issue is solved for us.

If your engineering team say many calls will run for as long as 5 minutes, perhaps the default timeout in the SDK should be set to 5 minutes and not 2 minutes :)
