### ISSUE TITLE
EarningsRate.EarningsTypeEnum missing entries

### ISSUE THREAD

**Issue by andyatwebscale** [XeroAPI/Xero-Java#260]
**SDK you're using (please complete the following information):**
 - Version 3.14.2

**Describe the bug**
An error has been returned when calling GetEarningsRatesAsync - 

`Error converting value "StatutoryBereavementPay" to type 'Xero.NetStandard.OAuth2.Model.PayrollUk.EarningsRate+EarningsTypeEnum'. Path 'earningsRates[13].earningsType', line 1, position 4721.`

**To Reproduce**
1. Make a call to the SDK GetEarningsRatesAsync endpoint, passing in a valid access token, tenant id and (optional) page

**Expected behavior**
The endpoint should return all the earnings rates or an empty collection if none. It returns null

**Additional context**
This could potentially be linked to [this bug](https://github.com/XeroAPI/Xero-NetStandard/issues/201) which hasn't seen any movement since December 2020

**Comment by SidneyAllen** [comment]
@andyatwebscale - I know you've got a PR open on the .NET SDK - so going to close this issue.

But for any Java developers - this enum issue is resolved in version 4.7.1 of the Xero-Java SDK
https://github.com/XeroAPI/Xero-Java/releases/tag/4.7.1
