### ISSUE TITLE
Add sending Purchase Orders feature

### ISSUE THREAD

**Issue by ArtemGro** [XeroAPI/Xero-Java#262]
**SDK you're using (please complete the following information):**
 - Version 4.7.0

**Is your feature request related to a problem? Please describe.**
I'm creating purchase orders by using this API. Unfortunately, there's no way I can email it to the contact.

**Describe the solution you'd like**
Add a feature to send/email purchase orders to the appropriate contact.

**Describe alternatives you've considered**
Send an email manually.

**Additional context**
NA

**Comment by SidneyAllen** [comment]
Hey @ArtemGro 

Xero supports triggering the emailing on Invoices via the API but not PurchaseOrders.  This is not something we can address via the SDK, so I'll be closing this issue.

You can vote for this feature on uservoice
https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/40703965-send-purchase-order-email-to-suppliers-via-api

**Comment by ArtemGro** [comment]
Hi Sidney, 

Thank you for your quick response.

I did vote for that feature.

Hopefully, it will be implemented soon.

Cheers!
Artem
