### ISSUE TITLE
XeroRateLimitException subtypes

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#264]
**SDK you're using (please complete the following information):**
4.1.4

**Is your feature request related to a problem? Please describe.**
We need to catch and handle this exception:
com.xero.api.XeroRateLimitException: You've exceeded the per [day] rate limit

The problem is that XeroRateLimitException actually covers (I think) 3 different rate limit constraints (https://developer.xero.com/documentation/oauth2/limits). Therefore, to catch the day limit specifically, we need to catch all XeroRateLimitException, check the message and re-throw anything we're not intending to catch.

**Describe the solution you'd like**
We would XeroRateLimitException to be a parent with with subtypes relating to the different rate limits that can be encountered. This will allow more accurate catching of specific rate limit exceptions.

**Describe alternatives you've considered**
We're going to catch all XeroRateLimitException and parse the exception message.

**Additional context**
NA

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - thanks for sharing the feedback.

I'll tag this as a feature request.  If you've got some time to work on this and submit a PR, the exception handling is outside our code generation and PRs are easy to merge. 

Maybe @lancedfr is interested in helping out?

**Comment by lancedfr** [comment]
Hi @SidneyAllen, I'm happy to help. You are welcome to assign this to me. I'll work on this over the weekend

**Comment by SidneyAllen** [comment]
@lancedfr and @U3R1YXJ0  - thanks for your patience.  Turns out comments for javadoc creation was missing in a lot of places including these exception classes.  Took a bit of time to work through them all.

This issue is resolved in 4.8.0 - please let me know how it's working for you.
https://github.com/XeroAPI/Xero-Java/releases/tag/4.8.0
