### ISSUE TITLE
PARTNER  Application

### ISSUE THREAD

**Issue by bshiroya** [XeroAPI/Xero-Java#27]
I have created PARTNER application in xero but they give null error

I have also created certificate
openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out publickey.cer -days 1825
openssl pkcs12 -export -out public_privatekey.pfx -inkey privatekey.pem -in publickey.cer

Also add cert folder and also change cred in json file  and run .

**Comment by SidneyAllen** [comment]
If you haven't already - please drop a note to api@xero.com for help specific to your application.

**Comment by bshiroya** [comment]
Thanks
