### ISSUE TITLE
Xero SDK v0.4.4 through Maven.

### ISSUE THREAD

**Issue by tamvu82** [XeroAPI/Xero-Java#281]
**SDK you're using (please complete the following information):**
 - Xero SDK v0.4.4 through Maven.
**Describe the bug**

Been using Xero SDK v0.4.4 through Maven.

The SDK dependency ‘xero-accounting-api-schema’ v0.0.5 is no longer available through Maven – as off Wednesday 15/4/2021.

Error message:
Could not find artifact com.xero:xero-accounting-api-schema:jar:0.0.5 in xero-accounting-api-schema-mvn-repo (https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo/)

We note that the relevant endpoint (below) is throwing a 400 Bad Request error.
https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo/

The result is that we are unable to build and deploy until the dependency is made available again, or a replacement SDK can be found (which would require material effort to implement).
**To Reproduce**
As part of build and deploy process, there is a
SDK dependency on ‘xero-accounting-api-schema’ v0.0.5. It is no longer available through Maven. 
**Expected behavior**
Endpoint through maven below should be working 
https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo/   

Availability of SDK dependency ‘xero-accounting-api-schema’ v0.0.5. 
A replacement SDK would require material effort to implement.

![Screenshot_20210419-122524_Slack](https://user-images.githubusercontent.com/82789468/115173329-6b7c8680-a10a-11eb-9a4c-7afe3717f368.jpg)

**Screenshots**

**Additional context**

**Comment by SidneyAllen** [comment]
@tamvu82 - thank you for letting us know.

We mistakenly deleted this repository, but have now restored it.
https://github.com/XeroAPI/XeroAPI-Schemas

Please let us know if this corrected the issue for you.

**Comment by tamvu82** [comment]
Thank you, this has resolved the issue. Thanks for your prompt reply.
