### ISSUE TITLE
Custom Connection support for API calls

### ISSUE THREAD

**Issue by stuartclayton** [XeroAPI/Xero-Java#291]
Currently all calls are validated to require the xeroTenantId.  Are there plans to support the new Custom Connection that lack this header?

**Comment by SerKnight** [comment]
Hey @stuartclayton,

We have support for this in the SDK. In progress of updating the readme with proper examples ⛅ 
For now the approach is to setup the `client_credentials` grant and set an empty string on the `xero_tenant_id` header.

```java
String xeroTenantId = "";
accountingApi.getContacts(accessToken,xeroTenantId)
```

* [SDK Docs](https://github.com/XeroAPI/Xero-Java/blob/e2dfa107032892cd102eeab2cdfa4510493749b1/README.md#client-credential-grant-type)
* [Sample App](https://github.com/XeroAPI/Xero-Java-custom-connections-starter)

**Comment by SerKnight** [comment]
Please re-open if you can't get it sorted and/or have feedback to improve the docs or the sample app!
