### ISSUE TITLE
External link provider name is not available in Invoice model

### ISSUE THREAD

**Issue by seos131** [XeroAPI/Xero-Java#292]
Hi there!

My company has recently migrated from Xero OAuth1 to OAuth2 recently and I have a question about one missing property in the Invoice model. 
We used to send the ExternalLinkProviderName with the company name, but it looks like the property is no longer available in the Invoice object.
Do I need to populate the value in the different property or is the property no longer required?

**Comment by SerKnight** [comment]
Hi @seos131  - that is a legacy field that we don't recommend using in your application logic anymore. I'd encourage you to leverage the `Reference` field or tracking categories to store anything related to classifications, outside of using the `Id` uuid.
