### ISSUE TITLE
Xero Api Bug - JAVA SDK: String ifModifiedSince

### ISSUE THREAD

**Issue by fatihperth** [XeroAPI/Xero-Java#294]
**SDK you're using (please complete the following information):**
 - Version [4.11.0]

**Describe the bug**
For PayrollAu Api, date/time filtering does not work in your java SDK but on your API Explorer. It produces variable-type mismatch errors.

In your source code, the type of variable is:
"String ifModifiedSince"

but in ( HttpHeaders extends GenericData )
it is required as List as indicate here:
"private List<String> ifModifiedSince"
and the variable name is colliding with google's variable name..if you change your variable name or make the type compatible with the one in HttpHeader, the issue will be resolved I guess..please advise if you need any further details or some screenshots, but your timely response will be highly appreciated.

![Screenshot from 2021-07-13 14-29-20](https://user-images.githubusercontent.com/84755908/125403339-fe664d80-e3e7-11eb-8e75-613b4d5b554e.png)
![Screenshot from 2021-07-13 14-30-09](https://user-images.githubusercontent.com/84755908/125403346-ff977a80-e3e7-11eb-8ed7-60ada32c7e28.png)

**Comment by rdemarco-xero** [comment]
Hi @fatihperth, thanks for bringing this to our attention! 

It appears the route cause stems back to our AU Payroll API spec not indicating the param format is date-time. We will get this change implemented in our next release.

Apologies for the inconvenience.

**Comment by fatihperth** [comment]
Hi @rdemarco-xero, thanks for the response..now three quick questions: 

1. When is it the new release going to be out? Because I need it ASAP.
2. The ifModifiedSince is not available in your UK payroll api at all, there is one field called "filter" only??
![UK Payroll APi](https://user-images.githubusercontent.com/84755908/126733302-66aff994-1b44-4e78-8a5e-ca74a564e751.png)

Many Thanks
Fatih

**Comment by rdemarco-xero** [comment]
Hi @fatihperth , version 4.13.0 has the fix for ifModifiedSince which is now a Java OffsetDateTime.

UK Payroll does not support this header param so the only solution currently would be to retrieve all the employees and then filter by UpdatedDateUTC in your own application.
