### ISSUE TITLE
Termination Reason missing from the payrollau employee object

### ISSUE THREAD

**Issue by rkennewell** [XeroAPI/Xero-Java#295]
**SDK you're using (please complete the following information):**
 - Version 4.11.0

**Describe the bug**
There is a new field called TerminationReason which must be supplied when setting the TerminationDate for an employee. Does not appear to be available in the current build of Xero-Java.

**To Reproduce**
Set the TerminationDate on an employee then try to save. Get an Error 400 Bad Request

"ErrorNumber":10,"Type":"ValidationException","Message":"A validation exception occurred","Employees":[{"ValidationErrors":[{"Message":"Termination reason is required"}],

**Expected behavior**
Need to be able to update an employee with a TerminationDate and TerminationReason. At this stage unable to Terminate an employee via the java-sdkl

**Additional context**
Refer to the following [Termination Reason](https://developer.xero.com/documentation/api/payrollau/stp-changes#termination-reason)

**Comment by rdemarco-xero** [comment]
@rkennewell, good catch! 

Looks like this feature slipped past us when it was released earlier this year. We will add it to the OpenAPI spec and generate new SDKs soon.

**Comment by rkennewell** [comment]
@rdemarco-xero Thanks!

**Comment by rkennewell** [comment]
Termination Reason has now been added.
