### ISSUE TITLE
The field "Item" is missing in entity LineItem

### ISSUE THREAD

**Issue by P3R3** [XeroAPI/Xero-Java#305]
### **SDK you're using: Xero-Java OAuth 2.0**
com.github.xeroapi : xero-java : 4.13.0

### **Describe the bug**
The field "Item" is missing in entity com.xero.models.accounting.LineItem class. 

### **To Reproduce**
In order to reproduce it, I will try to retrieve invoices first page :
1. I invoke the method com.xero.api.client.AccountingApi#getInvoices with page = 1 parameter
2. And this method generates a single API call:
GET https://api.xero.com/api.xro/2.0/Invoices?Statuses=VOIDED&Statuses=PAID&Statuses=AUTHORISED&Statuses=SUBMITTED&page=1&includeArchived=true
**Response HTTP Status:** 
200 OK
**Response body:** (the field "Invoices[0].LineItems[0].Item" is returned)
```
{
  "Id": "56f42d70-4d83-4c98-a4f9-22faeeb08efd",
  "Status": "OK",
  "ProviderName": "OpenHub OAuth2",
  "DateTimeUTC": "\/Date(1643374706266)\/",
  "Invoices": [
    {
      "Type": "ACCREC",
      "InvoiceID": "9da7f4f8-eb46-47a0-a8b8-4c96791d3a7d",
      "InvoiceNumber": "INV-0001",
      ...
      "LineItems": [
        {
          "ItemCode": "100",
          "Description": "toma item",
          "UnitAmount": 9999999.00,
          "TaxType": "NONE",
          "TaxAmount": 0.00,
          "LineAmount": 19999998.00,
          "AccountCode": "200",
          "Item": {
            "ItemID": "de4d9e8f-f7ae-4c30-8ff6-e514381167cb",
            "Code": "100"
          },
          "Tracking": [],
          "Quantity": 2.0000,
          "LineItemID": "d8d96947-b9d2-4c90-a95b-9693d08a9e87"
        }
      ],
      "SubTotal": 19999998.00,
      "TotalTax": 0.00,
      "Total": 19999998.00,
      "UpdatedDateUTC": "\/Date(1643374651953+0000)\/",
      "CurrencyCode": "GBP"
    }
  ]
}
```
3. The fields "Item.ItemID" and "Item.Code" are returned but is not deserialized into com.xero.models.accounting.LineItem 

### **Question**
Would be posible to modify the com.xero.models.accounting.LineItem implementation in order to contain the @JsonProperty("Item") field?

**Comment by rdemarco-xero** [comment]
This issue is fixed from version 4.15.0 on.
