### ISSUE TITLE
Java SDK Tax Object Missing Methods

### ISSUE THREAD

**Issue by fatihsevimtc** [XeroAPI/Xero-Java#318]
**SDK you're using (please complete the following information):**
 - Version 4.11.0

**Describe the bug**
Missing set/get methods in the SDK:
    • setHasLoanOrStudentDebt()
    • getHasLoanOrStudentDebt()
![Screenshot from 2022-08-03 10-59-17](https://user-images.githubusercontent.com/84755908/182516293-155ba768-e3d6-40ec-a260-b3dfcb8fbed5.png)

**Comment by RettBehrens** [comment]
This was resolved with the release of v4.20.0
