### ISSUE TITLE
Getting Wrong date format Exception when creating an invoice

### ISSUE THREAD

**Issue by arifainchtein** [XeroAPI/Xero-Java#333]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]
4.14
**Describe the bug**
When creating an invoice, i set the date and the due date as:
line 400, dateValue=2023-03-16
line 407, dueDateValue=2023-04-30
which is in the YYYY-MM-DD format described in the docs. yet i stil get the exception:

`com.fasterxml.jackson.databind.JsonMappingException: Wrong date format (through reference chain: com.xero.models.accounting.Invoices["Invoices"]->java.util.ArrayList[0]->
Caused by: java.lang.IllegalArgumentException: Wrong date format
`

**To Reproduce**

Run this code:

       ` Invoice invoice = new Invoice();
        invoice.setType(com.xero.models.accounting.Invoice.TypeEnum.ACCREC);
        invoice.setContact(contact);
        SimpleDateFormat invoiceDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateValue = invoiceDateFormat.format(new Date());
        System.out.println("line 400, dateValue=" + dateValue);
        invoice.setDate(dateValue);
        YearMonth ym = YearMonth.now( ZoneId.of( "Australia/Melbourne" ) ) ;
        YearMonth ymNext = ym.plusMonths( 1 ) ;
        java.time.LocalDate ld = ymNext.atEndOfMonth() ;
        String dueDateValue = ld.toString() ;
        invoice.setDueDate(dueDateValue);
        System.out.println("line 407, dueDateValue=" + dueDateValue);
        invoice.setLineItems(lineItems);
        invoice.setReference("Website Design");
        invoice.setStatus(com.xero.models.accounting.Invoice.StatusEnum.DRAFT);
        
        Invoices invoices = new Invoices();
        invoices.addInvoicesItem(invoice);
        boolean summarizeErrors=false;
        int unitdp=2;
        try {
            Invoices result = accountingApi.createInvoices(access_token, xero_tenant_id, invoices, summarizeErrors, unitdp);
            System.out.println(result);
        } catch (Exception e) {
            System.err.println("Exception when calling AccountingApi#createInvoices");
           
            e.printStackTrace();
        }`

in the code above, the outout of the System.out.println is:
`line 400, dateValue=2023-03-16
line 407, dueDateValue=2023-04-30`

**Expected behavior**
The invoice should be created

**Screenshots**

**Additional context**

**Comment by rdemarco-xero** [comment]
Hi @arifainchtein - in your code you are providing the date as a String. You need to provide a LocalDate type instead.
