### ISSUE TITLE
Resource can not be found when createInvoiceAttachmentByFileName

### ISSUE THREAD

**Issue by arifainchtein** [XeroAPI/Xero-Java#335]
**SDK you're using (please complete the following information):**
4.14
**Describe the bug**
After creating an invoice, i try uploading a pdf as attachement using this method:

` accountingApi.createInvoiceAttachmentByFileName(access_token, xero_tenant_id, invoiceid, filename, invoicePDFFile, includeonline);
`
The invoiceid i got it after creating the new invoice.  The  createInvoiceAttachmentByFileName has 4 parameters and i have verified that each one is valid:

access_token, xero_tenant_id, these two are valid because in the line above i created the invoice and there was no proble
invoiceid = i verified that this was a valid one because after creating the invoice, i extracted the returning uuid and then sent a request 
                  for the invoice using the UUID and i got a valid response with the correct data
 filename, invoicePDFFile = I verified these two by checking that the file actually exist in the local drive

 includeonline = set this one to true;

i get the following error:<br>

`com.xero.api.XeroNotFoundException: The resource you're looking for cannot be found`

**To Reproduce**
Here is the code that i am using:

<code>
try {
            Invoices result = accountingApi.createInvoices(access_token, xero_tenant_id, invoices, summarizeErrors, unitdp);
            System.out.println("line 484, invoice created for customerorder " + customerorderid );
            //
            // create pdf file and upload it to xero
            //
            UUID invoiceid = result.getInvoices().get(0).getInvoiceID();
            System.out.println("line 489, invoice created for customerorder " + customerorderid + " invoiceid=" + invoiceid );
            Invoices retinvoices = accountingApi.getInvoice(access_token, xero_tenant_id, invoiceid, null);
            System.out.println("line 491, returning invoice=" + retinvoices.getInvoices().get(0).toString());
            SaleInvoicePDFGenerator aSaleInvoicePDFGenerator = new SaleInvoicePDFGenerator(contact, quote);
            String filename = aSaleInvoicePDFGenerator.process(customerorder);
            File invoicePDFFile = new File(filename);
            System.out.println("line 495, created pdf file " + filename + " is file=" + invoicePDFFile.isFile() );
            accountingApi.createInvoiceAttachmentByFileName(access_token, xero_tenant_id, invoiceid, filename, invoicePDFFile, includeonline);
            System.out.println("line 497, uploaded pdf file " );
        } catch (Exception e) {
            e.printStackTrace();
        }
</code>

**Expected behavior**
I would expect to see the pdf file in the invoice in xero

**Screenshots**

**Additional context**

**Comment by rdemarco-xero** [comment]
Hi @arifainchtein, please check to make sure the filename you are providing is not a path. Filenames including any of the characters <, >, :, ", /, \, |, ?, *, \0 will be rejected as a Bad Request.

**Comment by arifainchtein** [comment]
Hello,
Thanks for that.  I was doing that, passing 
`/home/arifainchtein/lucille/salesinvoices/EL1281122.pdf`

in the filename parameter.  
After your suggestion, i changed the code so that the filename parameter is just 
`EL1281122`

and that took me further, however, now the problem i am facing is that i get an exception, it reads:

`Error {
    statusCode: 400
    type: Attachments
    message: null
    elements: [class Element {
        validationErrors: [class ValidationError {
            message: The file couldn't be uploaded because it isn't a supported file type.
        }]
        batchPaymentID: null
        bankTransactionID: null
        creditNoteID: null
        contactID: null
        invoiceID: null
        itemID: null
        purchaseOrderID: null
    }]
}
`

I am uploading a pdf which i have verified is a valid file type

Here is the file i am uploading it:

[EL1281122.pdf](https://github.com/XeroAPI/Xero-Java/files/11074775/EL1281122.pdf)

The pdf template was created using LibreOffice, and here is how i configured the creation of the pdf:

![CreatePDF](https://user-images.githubusercontent.com/7456552/227844837-40d08c35-0905-44d2-9807-e639d8f369b1.png)


Any suggestions as to what am i doing wrong?

thanks

**Comment by arifainchtein** [comment]
Hello,
I just realised that i did not include the other part of the error message returned, here it is:

`{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "AttachmentID": "00000000-0000-0000-0000-000000000000",
      "FileName": "SO5004",
      "MimeType": "application/pdf",
      "ContentLength": 103264,
      "ValidationErrors": [
        {
          "Message": "The file couldn't be uploaded because it isn't a supported file type."
        }
      ]
    }
`

**Comment by rdemarco-xero** [comment]
Hi @arifainchtein , glad to hear that worked! The final step is to include the ".pdf" to the end of "EL1281122" so that you are sending "EL1281122.pdf" as the filename. This should resolve your final issue.

**Comment by arifainchtein** [comment]
hello,
thanks for that, it works now.
i have uploaded the file and when i go to zero i can see it there.

the problem i have is that mt co worker who is the real xero user uses the other interface, and i cant find the file there.
fuethermore, when in the classic interface i click on the pdf button it actually creates a new invoice.  how can i make
the call so that when uploading a file, it ks the pdf that appears when i click the pdf button in the classic invoice view?

thanks

**Comment by rdemarco-xero** [comment]
With new invoicing, you can find attachments in the lower left.
![image](https://user-images.githubusercontent.com/80783917/228294815-24d9d0d4-3033-43a7-a3e9-b371cd82cc54.png)

With Classic Invoicing, you can find attachments under the file icon.
![image](https://user-images.githubusercontent.com/80783917/228295094-f85dd2c0-6fde-47cc-b0b6-1410cdeb9485.png)
