### ISSUE TITLE
Get Invoice URL?

### ISSUE THREAD

**Issue by marcosbis** [XeroAPI/Xero-Java#35]
Is it possible to get the invoice online URL via
 xeroClient.getInvoice(invoiceId+"/OnlineInvoice"); 

what is the correct way to get the invoice online url.

Thanks
Marcos

**Comment by SidneyAllen** [comment]
Updated Xero-Schemas to 0.0.5 to support OnlineInvoice
Updated Xero-Java SDK to version 0.4.2 with helper methods in XeroClient to support OnlineInvoice
