### ISSUE TITLE
GST on Expenses for LineItems

### ISSUE THREAD

**Issue by arifainchtein** [XeroAPI/Xero-Java#371]
Hello,
I am using the api to create a payment , i need to set the tax rate for each line item to GST On Expenses, however, that option is not available on the TaxType class.  If i dont put anything, it defaults to BASEXCLUDED which is wrong.  How can i set the taxrate of a lineitem to GST n Expenses?
thanks

**Comment by dev-welli** [comment]
To override the default tax rate of an account, you'll need to use the TaxType field and specify it to the value that you want to use. For "GST on Expenses" in AUstralia, the TaxType is INPUT

Xero Developer Center: [Tax Types](https://developer.xero.com/documentation/api/accounting/types/#tax-rates)
