### ISSUE TITLE
Can`t load private key form absolute file path.

### ISSUE THREAD

**Issue by radomich** [XeroAPI/Xero-Java#38]
Hi!
Can`t load private key form absolute file path because RsaSigner uses only Class.getResourceAsStream approach.

**Comment by SidneyAllen** [comment]
Yep - valid point.  Any reason you can't place the private key cert in the Resources Dir?  If you wish to submit a pull request with a patch - that would be great.

**Comment by GuiSim** [comment]
@SidneyAllen There's currently 3 pull requests that have been pending with no feedback for several days

https://github.com/XeroAPI/Xero-Java/pulls

If I were to rework the signing process, is there any chance that the PR would be merged?

**Comment by SidneyAllen** [comment]
Hi @GuiSim - yep - I'll set aside time on Friday to review the 3 open PR and merge them in.  Thanks for the bump.

**Comment by GuiSim** [comment]
Awesome! I'll have a PR ready by then @SidneyAllen 🙌

**Comment by GuiSim** [comment]
@SidneyAllen https://github.com/XeroAPI/Xero-Java/pull/56

**Comment by SidneyAllen** [comment]
@radomich - I've merged PR #56 and deployed as version 0.6.0 to maven.   

@GuiSim - since you made this update - would you mind updating the README to explain how to load the private key with an absolute path?

**Comment by GuiSim** [comment]
👍 
https://github.com/XeroAPI/Xero-Java/pull/58
