### ISSUE TITLE
NullPointerException on exceptions other than HttpResponseException

### ISSUE THREAD

**Issue by GuiSim** [XeroAPI/Xero-Java#39]
https://github.com/XeroAPI/Xero-Java/blob/master/src/main/java/com/xero/api/XeroClient.java#L288

```
		try {
			resp = req.execute();
			return unmarshallResponse(resp.parseAsString(), Response.class);
		} catch (IOException ioe) {
			if (ioe instanceof HttpResponseException) {
				HttpResponseException googleException = (HttpResponseException)ioe;
		           
				if (googleException.getStatusCode() == 400 ||
	            		googleException.getStatusCode() == 401 ||
	            		googleException.getStatusCode() == 404 ||
	            		googleException.getStatusCode() == 500 ||
	            		googleException.getStatusCode() == 503) {
					throw newApiException(googleException);
	            } else {
	            	System.out.println("Error - not tested with newApiException method");
	            	System.out.println(googleException.getStatusCode());
		            System.out.println(googleException.getContent());	
		            throw newApiException(googleException);
	            }
	        }
			return null;
		}
``` 

The `return null;` is problematic as more often than not, it'll end up causing a NullPointerException.

e.g.

```
  public List<BankTransaction> createBankTransactions(List<BankTransaction> bankTransactions) throws IOException {
    ArrayOfBankTransaction array = new ArrayOfBankTransaction();
    array.getBankTransaction().addAll(bankTransactions);
    return this.put("BankTransactions", this.objFactory.createBankTransactions(array)).getBankTransactions().getBankTransaction();
  }
``` 

If an IOException happens, `.getBankTransactions()` will throw a NullPointerException.
This is hard to diagnose and debug. I think a healthier behavior would be to throw the exception.

If we want to avoid throwing a checked Exception, I would suggest wrapping the exception in a RuntimeException, possibly a `XeroRuntimeException` or similar.

If we agree on this, I can implement it.

**Comment by SidneyAllen** [comment]
@GuiSim - Sounds reasonable - please share under what conditions we can trigger the new behavior so I can test it and see how the new exception is being thrown.

**Comment by GuiSim** [comment]
I finally had time to look into this issue again.

If I call `xeroClient.createBankTransactions()` with hundreds of bank transactions I can sometimes get a `java.net.SocketTimeoutException`. This will result in `null` being returned.

Currently in the lib you can override the connect but not the read timeout.

So two things: 
* The lib should throw instead of returning null
* Lib users should be able to configure the lib's read timeout

**Comment by GuiSim** [comment]
@SidneyAllen let me know if the PR fixes this in an appropriate way.
