### ISSUE TITLE
Get Attachment InputStream

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#50]
This is a feature request.

I am using Amazon S3 to store Xero Attachments. The Amazon Java SDK can be given two handles to save a file to S3, either java.io.InputStream or java.io.File.

See http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-com.amazonaws.services.s3.model.ObjectMetadata-

It would be great if the Xero SDK could pass back an InputStream for an Attachment. At the moment I have to download the file to my server disk and then pass a handle for that to S3. I assume it would be a lot quicker if I could pass an InputStream handle to straight to S3.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 - thanks - fixed in version 0.6.1  - Did not test saving to S3 - but returning a ByteArrayIntputStream - please let me know how you make out with this update.  Don't pass the dirPath argument to getAttachmentContent and you'll get the ByteArrayIntputStream returned.

**Comment by U3R1YXJ0** [comment]
@SidneyAllen Thanks very much for this. Do you have a code snippet you could share? I haven't been able to read anything from the returned ByteArrayInputStream.

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 here is the code I used to test the ByteArrayInputStream.  Like I said, I did not save it to S3  just confirmed it was returning data.  

To use this code, you'll want to login to Xero, create an invoice and attach file.  Substitute in your invoiceID (found on the URL of your new invoice) for my InvoiceID

 Invoice InvoiceSpecific = client.getInvoice("3a019892-77bd-4e6b-85bc-6194b383ed25");
							  				  
// GET ATTACHED FILE INPUT STREAM
ByteArrayInputStream in = client.getAttachmentContent("Invoices",InvoiceSpecific.getInvoiceID(),InvoiceSpecific.getAttachments().getAttachment().get(0).getFileName() ,InvoiceSpecific.getAttachments().getAttachment().get(0).getMimeType());

int n = in.available();
byte[] inBytes = new byte[n];
in.read(inBytes, 0, n);

String s = new String(inBytes, StandardCharsets.UTF_8);
System.out.println(s);

**Comment by U3R1YXJ0** [comment]
@SidneyAllen Thanks very much for taking the time to post your code. The problem for me turned out to be a basic build issue, my old xero sdk was being included with the new 0.6.1 sdk, so the new method was not available at runtime.

I was successfully able to pass the Xero ByteArrayInputStream to S3 for downloading the file.
