### ISSUE TITLE
Loading certificate contents from an environmental variable

### ISSUE THREAD

**Issue by maxmumford** [XeroAPI/Xero-Java#54]
Hello,

I have an application hosted on Heroku that needs to use this library. Heroku has a transient file system, meaning we cannot store the certificate directly as a file, and therefore must load its contents as an environmental variable. Is this currently possible?

Max

**Comment by GuiSim** [comment]
I think the signing process would benefit from looser coupling between components.

It would be great if we could provide our own implementation of the `Signer` interface. We could then extend the `RsaSigner` and load the certificates however we see fit.

We face similar issues on our side where we can't save the certificate in a file or embed it in the Jar. We like to write our own logic to provide the certificate values.

**Comment by maxmumford** [comment]
Just checked your PR #56 - great work on decoupling the config. In the meantime if anybody needs this working asap, I made a quick and dirty fix involving programmatically writing the .pfx file to the file system on application startup:

 - Base64 encode the .pfx certificate: openssl base64 -in xero.pfx -out xero.base64.pfx
 - Save the resulting file's contents as a `heroku config var: heroku config:add XER_CERTIFICATE="$(cat ./xero.base64.pfx)"
 - If using Spring Boot, load the XER_CERTIFICATE environmental variable using the @Value annotation
 - Modify the XeroConfig object to allow you to expose the setter for the PATH_TO_PRIVATE_KEY property
 - On application startup (ie using a @PostConstruct hook with spring boot), write the certificate to the file system like so:

```
        FileOutputStream fos = new FileOutputStream("src/main/resources/certs/xero-certificate.pfx");
        byte[] decoded = Base64.getDecoder().decode(XERO_CERTIFICATE); 
        fos.write(decoded, 0, decoded.length);
        fos.flush();
        fos.close();

        XeroConfiguration config = new XeroConfiguration("xero.", environment);
        config.setPathToPrivateKey("certs/xero-certificate.pfx"); // certs folder in /src/main/resources 
        XeroClient client = new XeroClient(config);
        client.setOAuthToken(config.getConsumerKey(), config.getConsumerSecret());
        xeroClient = client;
```

**Comment by SidneyAllen** [comment]
@maxmumford - I've merged @GuiSim PR so you should be good to go - let me know how you get on this this.

**Comment by maxmumford** [comment]
Works perfectly for me with Spring and Heroku:

 - Base64 your certificate with `openssl base64 -in xero.pfx -out xero.base64.pfx`
 - Create a spring config file as described here: https://github.com/XeroAPI/Xero-Java/blob/master/example/src/main/java/example-spring/SpringConfig.java
 - Add your certificate base64 contents as an environmental variable
 - Create your XeroClient instance like so:

```
byte[] decoded = Base64.getDecoder().decode(XERO_CERTIFICATE_BASE64);
InputStream privateKeyInputStream = new ByteArrayInputStream(decoded);
XeroConfiguration config = new XeroConfiguration("xero.", environment);
XeroClient client = new XeroClient(config, new RsaSignerFactory(privateKeyInputStream, config.getPrivateKeyPassword()));
```
