### ISSUE TITLE
Xero validation exception messages aren't returned from createInvoices

### ISSUE THREAD

**Issue by geekatwork** [XeroAPI/Xero-Java#55]
I am creating a batch of invoices and if any have validation exceptions createInvoices throws an IOException which I log. The log shows that a com.xero.api.XeroApiException exception occurred and has the message from the Xero validation exception but none of the other information usually returned from Xero in XML. This makes it hard to identify which invoice creation failed.

Am I doing something wrong or is this part not complete?

**Comment by lancedfr** [comment]
+1
I am having this issue also. **createPayment also** 
This makes it hard to identify which has failed.
For now my work around is ugly and I send one payment/invoice at a time, this way I know which failed.

**Comment by lancedfr** [comment]
according to the xero dev docs 
https://developer.xero.com/documentation/api/http-response-codes#http401
HTTP 400 responses include an “ApiException" element in the response that contains a useful summary of the reason for the error.
I see a Elements contains a xsi:type which we can marshal to a type. I'll investigate and see if I cant pick up this issue and create a PR

**Comment by lancedfr** [comment]
@SidneyAllen, @geekatwork, I am unable to assign this issue; 
can someone assign this one to me please?

**Comment by SidneyAllen** [comment]
Thanks @lancedfr - tried to assign to you - but Github UI doesn't show your name.

I was going to work through some of these issues on Friday - drop in a comment if you do anything  over the next day or two. 

I don't believe the SDK has been tested with the summarizeErrors=true parameter 
https://developer.xero.com/documentation/api/invoices#post

Since the validation errors are structured differently - we will probably need to update the ApiException class to handle it.

**Comment by lancedfr** [comment]
Thanks, I had a quick look at the issue tonight. From what I can see we should be able to utilise the xsi:type="Invoice", xsi:type="Payment", etc from the ApiException XML.. I'll only be able to work on this issue over the weekend. will create a PR and you can review what I've put together.

**Comment by SidneyAllen** [comment]
@lancedfr  that would be awesome - I'll focus on some of the older issues.

**Comment by SidneyAllen** [comment]
V 0.6.2 incorporates PR #62 

how to use summarize errors


try {
	List<Invoice> listOfInvoices = new ArrayList<Invoice>();
	listOfInvoices.add(SampleData.loadBadInvoice().getInvoice().get(0));
	listOfInvoices.add(SampleData.loadBadInvoice2().getInvoice().get(0));
	
	List<Invoice> newInvoice = client.createInvoices(listOfInvoices,null,true);
	System.out.println("Create a new Invoice ID : " + newInvoice.get(0).getInvoiceID() + " - Reference : " +newInvoice.get(0).getReference());
		
} catch (XeroApiException e) {
	System.out.println(e.getResponseCode());

	List<Elements> elements = e.getApiException().getElements();
	Elements element = elements.get(0);
 	List<Object> dataContractBase = element.getDataContractBase();
	for (Object dataContract : dataContractBase) {
		Invoice failedInvoice = (Invoice) dataContract;
		ArrayOfValidationError validationErrors = failedInvoice.getValidationErrors();
            
		System.out.println("Failure message : " + errors.get(0).getMessage());
		System.out.println("Failure invoice Num : " + failedInvoice.getInvoiceNumber());
	}
}
