### ISSUE TITLE
Rounding issues

### ISSUE THREAD

**Issue by paulmarkrussell** [XeroAPI/Xero-Java#60]
Are you able to include functionality to fix the Xero rounding error https://developer.xero.com/documentation/api-guides/rounding-in-xero

**Comment by paulmarkrussell** [comment]
Just had a quick look at the code and the change seems to be a simple enough one on the face of it via the Config Interface and OAuthRequestResource class.

A new field in the Config Interface

`int getDecimalPlaces();`
`void setDecimalPlaces(int consumerSecret);`

and then include the new parameter if it is not null via the OAuthRequestResource Constructor

`if (config.getProxyHost() != null) {
      ...
}`

Again, just had a quick look so of course I'm no expert on the SDK.

Would be great if you could include a fix as we can't actually use the SDK with the 2 decimal places limit.

Thanks
Paul

**Comment by SidneyAllen** [comment]
@paulmarkrussell 

Started by adding DecimalPoint to config.json - then realized handling this globally might not be flexible for all - so added new unitdp argument to methods.

i.e. 
Invoice InvoiceDecimal = client.getInvoice("3a019892-77bd-4e6b-85bc-6194b383ed25",config.getDecimalPlaces());

checkout v. 0.6.1 of SDK

**Comment by paulmarkrussell** [comment]
Are you able to add decimal place support for client.createCreditNotes & client.createReceipts

**Comment by SidneyAllen** [comment]
Hi @paulmarkrussell  - sorry for taking so long on this request.  Added support in version 1.0.1
