### ISSUE TITLE
New method to get some CreditNote from a list of ids

### ISSUE THREAD

**Issue by davidfercas** [XeroAPI/Xero-Java#65]
I am using the method
`    List<Invoice> getInvoices(Date modifiedAfter, String where, String order,String page,String ids)`
 
to get the information about some invoices.

In the same way, I would need to get the information, CreditNote lines included, of some Credit Notes from a list of ids like:

List<CreditNote> getCreditNotes(Date modifiedAfter, String where, String order,String page,String ids)

Is there a workaround to get what I need?
I guess I could try to modify the library and create a method including the  addToMapIfNotNull(params, "Ids", ids); on my own. 

Is there a workaround for this?

PD: If it works, let me know if you want me to create a pull request.

Regards,
David F

**Comment by SidneyAllen** [comment]
Hi @davidfercas,

Sorry for the slow reply - holidays and some health issues - had me sidelined.

Looking at our Release notes and API docs - we only added support for List of IDs to Invoices and Contacts (those have the most traffic).

So, this feature is not supported on Credit Notes.  You can register your interest on our uservoice.

https://xero.uservoice.com/forums/5528-xero-accounting-api
