### ISSUE TITLE
Cannot download file containing certain characters

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#66]
This issue is related to / similar to issue #49 

I cannot download a file (for example an invoice attachment) with a '%' (percent symbol) in the filename. I am using the getAttachmentContent streaming method.

The error message I get is java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern

I am using Xero API Java SDK version 0.6.1

Having done a little testing I know some other characters produce the same issue, although im not sure which ones. The following string contains all characters that are allowed in a windows filename. Assuming this issue is fixed in the future it might be worth creating a file using the string below for testing (single quote is missing as im using that for markup)

` !#$%&\'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{}~
`

**Comment by SidneyAllen** [comment]
Quick update on this reported bug.  We changed to a different httpclient to support TLS 1.2 for Java 1.6 and 1.7.

I did some investigating with current httpclient-4.5.3 and it does not like URIs that have special characters (i've only tested with a "%").  The following code is where we set the URI

HttpGet httpget = new HttpGet(config.getApiUrl() + this.resource + this.resourceName);

This translates to something like ...  /api.xro/2.0/Invoices/6bb31cdd-dd22-42d7-96c5-16537f8fac08/Attachments/my%file.pdf

The above IS what Xero's API wants, but the httpclient we are using throws a similar error mentioned in an earlier version of the SDK.

java.lang.IllegalArgumentException: Malformed escape pair at index 97: https://api.xero.com/api.xro/2.0/Invoices/6bb31cdd-dd22-42d7-96c5-16537f8fac08/Attachments/my%file.pdf
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
		
Unfortunately, I don't have a solution for this.  I've shared this information with Xero's API team to understand if there is anything we can do to accept the encoded URI as that would work properly with our httpclient.

One a related note, when creating Attachments with the JavaSDK, we strip out special characters.  I know this doesn't help where files are uploaded via the Xero UI with a "%" in the filename, but thought I'd mention the attachments you create via the API shouldn't be a problem to retrieve.

**Comment by SidneyAllen** [comment]
Good news @U3R1YXJ0 - I checked with the API team and you can get Attachments using the AttachmentID in the URI.

I've added a new method 

InputStream in = client.getAttachmentContentById("Invoices",newInvoice.get(0).getInvoiceID(),getInvoiceAttachment.get(0).getAttachmentID(),getInvoiceAttachment.get(0).getMimeType());

Pushed as v 1.0.8

**Comment by U3R1YXJ0** [comment]
Great, sounds like a neat solution, thanks Sid.
