### ISSUE TITLE
Mistake in README OAuth flow

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#67]
In OAuth flow part of README change
`OAuthAuthorizeToken authToken = new OAuthAuthorizeToken(requestToken.getTempToken());`

to 

`OAuthAuthorizeToken authToken = new OAuthAuthorizeToken(config, requestToken.getTempToken());`

(Add JsonConfig to argument)

**Comment by SidneyAllen** [comment]
@U3R1YXJ0 thanks for the feedback.
