### ISSUE TITLE
Is the Xero-Java library thread safe?

### ISSUE THREAD

**Issue by gtod** [XeroAPI/Xero-Java#72]
Hi there,

We have been happily using Xero-Java for several weeks now in a backend application that will serve web requests and, at least for some of those requests, talk to Xero to make/view invoices and payments etc.  It's a private app.

So we are in a position to make a single `XeroClient` instance and have it shared across all our web requests which will run in multiple threads.

Hence the question.  Is the Xero-Java library thread safe?  Or should we make a new `XeroClient` instance inside each request that needs to talk to Xero?

Followup question: If we can use just a single long lived `XeroClient` instance does the library ensure the connection is kept alive under the covers or might it just timeout or disconnect at some point?

FYI @JesseSchalken

**Comment by pkohout-profitsee** [comment]
Hi,
we are using the XeroClient in multiple threads to do requests. And so far it works fine. But I think you can only create one XeroClient per company in Xero (because of the OAuth information that is stored on the client).

I do not know if the connection is kept alive.

**Comment by trungie** [comment]
@gtod XeroClient on each request creates a new http client so there is no sharing of state at the connection level.
