### ISSUE TITLE
memory leak in metaspace

### ISSUE THREAD

**Issue by pkohout-profitsee** [XeroAPI/Xero-Java#77]
Hi,

I think there is a memory leak caused by the creation of a new JAXBContext on each Request/Response (in XeroClient.java and XeroJAXBMarshaller). We had the problem that the metaspace of out java application kept growing, because the XeroApi kept loading classes, till there were no memory left. After some research I found out that the JAXBContext should only created once per class, because it causes such a memory leak in the metaspace (see [http://www.scorgar.be/blog/lessons-learned-memory-leak-in-webservices-with-jaxb/](this blogpost) and [https://stackoverflow.com/questions/3584821/jaxbcontext-newinstance-memory-leak/3584944](this question). Today I did a quick fix and, at least locally, the loading of new classes stopped. Is someone else having the same problems, or has been able to see this behaviour too?

regards Peter

**Comment by SidneyAllen** [comment]
Hi @pkohout-profitsee 

Can you share your fix?  Happy  to update the SDK to solve for this.

Thanks

**Comment by SidneyAllen** [comment]
@pkohout-profitsee - thanks for sharing those articles on the topic.  I've updated XeroClient and XeroJAXBMarshaller classes and made the JAXBContext a static variable for release 1.0.0

If you don't mind giving this a look see - happy to modify, if my code change doesn't address the issue - https://github.com/XeroAPI/Xero-Java/releases/tag/1.0.0

**Comment by pkohout-profitsee** [comment]
@SidneyAllen you fix looks good.
