### ISSUE TITLE
Getting HttpResponseException while requesting for accesstoken

### ISSUE THREAD

**Issue by satishetc4288** [XeroAPI/Xero-Java#8]
Getting following message ->
REFRESH EXECPTION
Received HttpException: com.google.api.client.http.HttpResponseException: 400 Bad Request
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>

The file is OauthAccesstoken.java line number 112.

**Comment by SidneyAllen** [comment]
Hi @satishetc4288 

Are you working with a Xero Partner App?  

If you are still having problems refreshing your access tokens, file a ticket with api@xero.com so we can gather more information on your specific issue.

Thanks
Sid
