### ISSUE TITLE
documentation out of date & samples.

### ISSUE THREAD

**Issue by apps4u** [XeroAPI/Xero-Java#85]
Hi I'm currently been using version 0.4.2 in production for close to 2 years now, We are using a springboot application that is using the Accounting API to create contacts, invoices, payments. 

Now I'm in the process of upgrading spring to boot 2.0. And I want to update the Xero Api. Now when I do I have lots of errors in my config, I used the example SpringConfig as my starting point which I haved changed to support two XeroClients (beans) one for Australia and one for New Zealand.

Now when I upgrade the SDK I have to implement more properties from the Config Interface. But their is no documentation as to what each properties is for so some look like they are just renamed others are new. 

So is their anywhere I can get doc's as the current doc's and samples are for the old version of the SDK.

if you diff 0.4.2 to 1.0.5 their is lots of changes in the SDK but not the sample or example or docs.

**Comment by SidneyAllen** [comment]
Hi @apps4u 

I have updated the README to better reflect the v1.0 of the SDK.  I've also created a new video tutorial walking through how to setup a project and use the SDK with code samples in the README for ppl to use.  

As far as the Spring Config - that was contributed by the community and isn't something I am versed in.  If you have suggestions on how to improve the docs around using Spring, I would welcome the pull request.

Hope that helps.
