### ISSUE TITLE
Improve documenation when using openssl

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#89]
I followed the instructions for using openssl to generate my private keys.

I then followed the instructions for setting the config file to point to my keys.

What wasn't clear from the documenation is that the library expects those keys to be in the java cacerts keystore.

Using the keystore is a pain and un-necessary, however the doco needs  to be clear that you need to import the keys.

Also the doco on using your own RsaSignerFactory doesn't say why you might want to use it.

It turns out that if you have used openssl to generate the keys and don't want to use java's cacerts keystore then using the RsaSignerFactory is the way forward.

The doco should be changed to say:

Custom Request Signing

You can provide your own signing mechanism by using the public XeroClient(Config config, SignerFactory signerFactory) constructor. Simply implement the SignerFactory interface with your implementation.

OpenSSL  Private Key

If you used openssl to generate your private key then your keys won't be in the java cacert keystore.
You can either import your keys into the java key store or use a a custom signer factory to directly reference the keys generated by openssl - this is the easier option.

````
		Config config =  new JsonConfig("config.json");
		FileInputStream privateKeyStream 
                                 = new FileInputStream(config.getPathToPrivateKey());
		RsaSignerFactory signerFactory = new RsaSignerFactory(privateKeyStream
                                 , config.getPrivateKeyPassword());
		client = new XeroClient(config, signerFactory);
		client.setOAuthToken(config.getConsumerKey(), config.getConsumerSecret());

````
For the above to work you need to have the following attributes set in config.json

````
"PrivateKeyCert" :  "<path to openssl key>/public_privatekey.pfx",
  "PrivateKeyPassword" :  "<password to the above PrivateKeyCert>",
````

**Comment by trungie** [comment]
@bsutton The private key does not need to be in the keystore. The keystore is used only if you want to use TLS 1.2.

**Comment by bsutton** [comment]
I think the issue is that the defaults expect to find the keys in the key store and this isn't explicitly documented and how you go about using OpenSSO keys isn't documented either which is particularly problematic give the main Xero site explains how to use openssl as the primary method.

**Comment by trungie** [comment]
From the homepage of this repo:

>In a text editor, create a file called config.json (examples are below) Refer to Xero Developer Center Getting Started when you are ready to create a Xero App - this is how you'll create a Consumer Key and Secret. Private and Partner apps require a public/private key pair you'll create using OpenSSL. The private key should be exported as a pfx file and in our example we create a "certs" folder inside the resources folder and place it there.

**Comment by SidneyAllen** [comment]
Hi @bsutton 

It sounds like the was come confusion between certificates for RSA -SHA1 signing and certificates related to TLS 1.2 for Java 6 & 7.  Apologies for any problems that introduced.

I've taken your feedback though and updated the README to be a bit more explicit about  the default location for the config.json file as well as link to an area about customizing your own implementation of the Config class.  I've also created a new video tutorial that walks through how to setup project with the defaults.
