### ISSUE TITLE
Organisation PaysTax element not accessible

### ISSUE THREAD

**Issue by U3R1YXJ0** [XeroAPI/Xero-Java#90]
The Xero API Organisation endpoint exposes a field called PaysTax.
https://developer.xero.com/documentation/api/organisation

It looks like that element is not accessible through the Java SDK?

**Comment by SidneyAllen** [comment]
Hello @U3R1YXJ0 

This field is in our XSDs and therefore available in Xero-Java SDK.

I just tested ...

if(newOrganisation.get(0).isPaysTax()) {
    System.out.println("Yes I Pay Tax");		
} else {
    System.out.println("No I do not Pay Tax" );		
}

**Comment by U3R1YXJ0** [comment]
Thanks. I had missed that on account of it being 'isPaysTax' rather than 'getPaysTax'.
