### ISSUE TITLE
No /history endpoint implementation? How to retrieve Invoice notes?

### ISSUE THREAD

**Issue by tmilar** [XeroAPI/Xero-Java#92]
Hi,
I need to retrieve Invoice notes. 
Per the [documentation](https://developer.xero.com/documentation/api/history-and-notes), the endpoint to do so is https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/history

But I can't find any method to access that endpoint in the Xero-Java SDK.

Am I missing something? Any way to retrieve the invoice notes without re-implementing or extending the SDK to call to the API?

**Comment by SidneyAllen** [comment]
Hi @tmilar 

We haven't added those models yet.  Thanks for the nudge.  Currently working on implementing json support to help extend coverage to our newer APIs that have dropped XML.

**Comment by SidneyAllen** [comment]
Hi @tmilar 

We've just release version 2.0 of the Java SDK and it now has full JSON support for requests and responses.  Please review the README to see how 1.0 and 2.0 of the SDK differ.

History and Notes for all endpoints has been added - there is an issue creating new History notes on some endpoints.  Invoice works fine though.
