### ISSUE TITLE
Custom HttpClient/HttpClientBuilder

### ISSUE THREAD

**Issue by pacey** [XeroAPI/Xero-Java#94]
It would be great if we could pass in our own HttpClient or HttpClientBuilder so we can instrument calls to the Xero API using distributed tracing tools like [Amazon X-Ray](https://aws.amazon.com/xray/).

We have implemented our Xero Integration using AWS StepFunctions and AWS Lambda and all of our external calls are traced using X-Ray which really helps diagnose issues when things inevitably go wrong. Having our calls to Xero traced would be super helpful.

Here are the docs for how to do this in Java https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-httpclients.html

**Comment by SidneyAllen** [comment]
Based on how the HttpClient is baked into the API client classes with responses handling different data types (json and binary) and headers and authentication, I don't see an easy way to implement this and wholesale swapping in of HttpClient.  

For this reason we'll be declining and closing at this time.
