### ISSUE TITLE
Missing Feed Statements Support

### ISSUE THREAD

**Issue by genericmethod** [XeroAPI/Xero-Java#95]
@SidneyAllen is there an ETA 🕐 on Feed Statements support?

Thanks 👍

**Comment by SidneyAllen** [comment]
Hi @genericmethod 

No ETA at this point, but as soon as I get the swagger docs from the team who are building the API I'll begin working on adding support to the Java SDK.  Will keep this issue open so I can ping you when it's ready.

**Comment by genericmethod** [comment]
@SidneyAllen thanks, looking forward to this :)

**Comment by SidneyAllen** [comment]
@genericmethod - quick update that we are making progress.  If you are in a time crunch I can publish the current build for your team to try out.

**Comment by SidneyAllen** [comment]
@genericmethod - I've pushed out version 1.3 of the SDK with Bank Feed Statement support.  Please see the release notes if you've already implemented the feedconnection as I've refactored that code from v 1.1 of the SDK. (Breaking change)
