### ISSUE TITLE
Feed Connnection: No Linking via Account Id possible

### ISSUE THREAD

**Issue by codechimp** [XeroAPI/Xero-Java#98]
Hi,

it seems the current client version does not allow to specify the Bank Account Id for creating a Feed Connection. See also https://developer.xero.com/documentation/bank-feeds-api/feed-connections

**Comment by codechimp** [comment]
Please have a look at [this](https://github.com/XeroAPI/Xero-Java/pull/99) pull request

**Comment by SidneyAllen** [comment]
added in version 1.3.2
